CYCLUS: cyclus::XMLFileLoader Class Reference
cyclus::XMLFileLoader Class Reference
Handles initialization of a database with information from a cyclus xml input file.
#include <xml_file_loader.h>
Public Member Functions
virtual void LoadSim ()
Load an entire simulation from the inputfile.
XMLFileLoader (Recorder *r, QueryableBackend *b, std::string schema_file, const std::string input_file="")
Create a new loader reading from the xml simulation input file and writing to and initializing the backends in r.
virtual ~XMLFileLoader ()
Protected Member Functions
Agent * BuildAgent (std::string proto, Agent *parent)
Creates and builds an agent, notifying its parent.
void LoadControlParams ()
Method to load the simulation control parameters.
virtual void LoadInitialAgents ()
Creates all initial agent instances from the input file.
void LoadRecipe (InfileTree *qe)
loads a specific recipe
void LoadRecipes ()
Method to load recipes from either the primary input file or a recipeBook catalog.
void LoadSolver ()
Method to load the simulation exchange solver.
virtual std::string master_schema ()
void ProcessCommodities (std::map< std::string, double > *commodity_order)
Processes commodity orders, such that any without a defined order (i.e., are nonpositive), are given an order value greater the last known commodity.
Protected Attributes
QueryableBackend * b_
Context * ctx_
std::string file_
the input file name
boost::shared_ptr< XMLParser > parser_
the parser
Recorder * rec_
std::string schema_path_
filepath to the schema
Timer ti_
Detailed Description
Handles initialization of a database with information from a cyclus xml input file.
Warning:
the LoadSim method is NOT idempotent. Only one / simulation should ever be initialized per XMLFileLoader object.
Definition at line 37 of file xml_file_loader.h.
Constructor & Destructor Documentation
cyclus::XMLFileLoader::XMLFileLoader (Recorder * r, QueryableBackend * b, std::string schema_file, const std::string input_file = "")
Create a new loader reading from the xml simulation input file and writing to and initializing the backends in r.
r must already have b registered. schema_file identifies the master xml rng schema used to validate the input file.
Definition at line 102 of file xml_file_loader.cc.
References cyclus::Datum::AddVal(), ctx_, file_, cyclus::LoadStringstreamFromFile(), cyclus::Context::NewDatum(), parser_, rec_, cyclus::Datum::Record(), schema_path_, and ti_.
cyclus::XMLFileLoader::~XMLFileLoader () [virtual]
Definition at line 120 of file xml_file_loader.cc.
References ctx_, cyclus::Recorder::Flush(), and rec_.
Member Function Documentation
Agent * cyclus::XMLFileLoader::BuildAgent (std::string proto, Agent * parent) [protected]
Creates and builds an agent, notifying its parent.
The agent init info is translated and stored in the output db.
Definition at line 278 of file xml_file_loader.cc.
References cyclus::Agent::Build(), cyclus::Agent::BuildNotify(), cyclus::Context::CreateAgent(), and ctx_.
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), and LoadInitialAgents().
void cyclus::XMLFileLoader::LoadControlParams () [protected]
Method to load the simulation control parameters.
Definition at line 287 of file xml_file_loader.cc.
References ctx_, cyclus::InfileTree::GetString(), cyclus::Context::InitSim(), cyclus::InfileTree::NMatches(), parser_, and cyclus::InfileTree::Query().
Referenced by LoadSim().
void cyclus::XMLFileLoader::LoadInitialAgents () [protected, virtual]
Creates all initial agent instances from the input file.
Reimplemented in cyclus::XMLFlatLoader.
Definition at line 202 of file xml_file_loader.cc.
References cyclus::Context::AddPrototype(), b_, BuildAgent(), ctx_, cyclus::Recorder::Flush(), cyclus::InfileTree::GetElementName(), cyclus::InfileTree::GetString(), cyclus::Agent::id(), cyclus::Agent::InfileToDb(), cyclus::Agent::InitFrom(), cyclus::DynamicModule::Make(), cyclus::InfileTree::NMatches(), parser_, cyclus::InfileTree::Query(), rec_, cyclus::Agent::set_agent_impl(), and cyclus::Recorder::sim_id().
Referenced by LoadSim().
void cyclus::XMLFileLoader::LoadRecipe (InfileTree * qe) [protected]
loads a specific recipe
void cyclus::XMLFileLoader::LoadRecipes () [protected]
Method to load recipes from either the primary input file or a recipeBook catalog.
Definition at line 187 of file xml_file_loader.cc.
References cyclus::Context::AddRecipe(), CLOG, ctx_, cyclus::InfileTree::GetString(), cyclus::LEV_DEBUG3, cyclus::InfileTree::NMatches(), parser_, cyclus::InfileTree::Query(), and cyclus::ReadRecipe().
Referenced by LoadSim().
void cyclus::XMLFileLoader::LoadSim () [virtual]
Load an entire simulation from the inputfile.
Parameters:
use_flat_schema whether or not to use the flat schema
Definition at line 129 of file xml_file_loader.cc.
References ctx_, cyclus::Recorder::Flush(), LoadControlParams(), LoadInitialAgents(), LoadRecipes(), LoadSolver(), master_schema(), parser_, rec_, and cyclus::SimInit::Snapshot().
void cyclus::XMLFileLoader::LoadSolver () [protected]
Method to load the simulation exchange solver.
Definition at line 140 of file xml_file_loader.cc.
References cyclus::Datum::AddVal(), ctx_, cyclus::InfileTree::GetString(), cyclus::Context::NewDatum(), cyclus::InfileTree::NMatches(), parser_, ProcessCommodities(), cyclus::InfileTree::Query(), and cyclus::Datum::Record().
Referenced by LoadSim().
std::string cyclus::XMLFileLoader::master_schema () [protected, virtual]
Reimplemented in cyclus::XMLFlatLoader.
Definition at line 125 of file xml_file_loader.cc.
References cyclus::BuildMasterSchema(), and schema_path_.
Referenced by LoadSim().
void cyclus::XMLFileLoader::ProcessCommodities (std::map< std::string, double > * commodity_order) [protected]
Processes commodity orders, such that any without a defined order (i.e., are nonpositive), are given an order value greater the last known commodity.
Definition at line 165 of file xml_file_loader.cc.
References CLOG, and cyclus::LEV_INFO1.
Referenced by LoadSolver().
Member Data Documentation
QueryableBackend* cyclus::XMLFileLoader::b_ [protected]
Definition at line 84 of file xml_file_loader.h.
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), and LoadInitialAgents().
Context* cyclus::XMLFileLoader::ctx_ [protected]
Definition at line 83 of file xml_file_loader.h.
Referenced by BuildAgent(), LoadControlParams(), cyclus::XMLFlatLoader::LoadInitialAgents(), LoadInitialAgents(), LoadRecipes(), LoadSim(), LoadSolver(), XMLFileLoader(), and ~XMLFileLoader().
std::string cyclus::XMLFileLoader::file_ [protected]
the input file name
Definition at line 93 of file xml_file_loader.h.
Referenced by XMLFileLoader().
boost::shared_ptr<XMLParser> cyclus::XMLFileLoader::parser_ [protected]
the parser
Definition at line 90 of file xml_file_loader.h.
Referenced by LoadControlParams(), cyclus::XMLFlatLoader::LoadInitialAgents(), LoadInitialAgents(), LoadRecipes(), LoadSim(), LoadSolver(), and XMLFileLoader().
Recorder* cyclus::XMLFileLoader::rec_ [protected]
Definition at line 81 of file xml_file_loader.h.
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), LoadInitialAgents(), LoadSim(), XMLFileLoader(), and ~XMLFileLoader().
std::string cyclus::XMLFileLoader::schema_path_ [protected]
filepath to the schema
Definition at line 87 of file xml_file_loader.h.
Referenced by cyclus::XMLFlatLoader::master_schema(), master_schema(), and XMLFileLoader().
Timer cyclus::XMLFileLoader::ti_ [protected]
Definition at line 82 of file xml_file_loader.h.
Referenced by XMLFileLoader().
The documentation for this class was generated from the following files:
xml_file_loader.h
xml_file_loader.cc