CYCLUS: cyclus::SupplyDemandManager Class Reference
cyclus::SupplyDemandManager Class Reference
This is a manager class that manages a set of commodities.
#include <supply_demand_manager.h>
Public Member Functions
double Demand (Commodity &commodity, int time)
the demand for a commodity at a given time
SymFunction::Ptr DemandFunction (Commodity &commodity)
returns the demand function for a commodity
bool ManagesCommodity (Commodity &commodity)
void RegisterCommodity (Commodity &commodity, SymFunction::Ptr demand)
register a new commodity with the manager, along with all the necessary information
void RegisterProducerManager (CommodityProducerManager *cpm)
adds a commodity producer manager to the set of producer managers
double Supply (Commodity &commodity)
returns the current supply of a commodity
SupplyDemandManager ()
constructor
void ThrowErrorIfCommodityNotManaged (Commodity &commodity)
checks if ManagesCommodity() is true.
void UnRegisterProducerManager (CommodityProducerManager *cpm)
removes a commodity producer manager from the set of producer managers
virtual ~SupplyDemandManager ()
virtual destructor
Private Attributes
std::map< Commodity,
SymFunction::Ptr,
CommodityCompare > demand_functions_
a container of all demand functions known to the manager
std::set
< CommodityProducerManager * > managers_
a container of all production managers known to the manager
Detailed Description
This is a manager class that manages a set of commodities.
Those commodities have a certain demand function associated with them and a list of producers who can produce the commodities.
The SupplyDemandManager simply keeps track of this information and provides the demand and supply of a commodity at a given time. What to do with this information is left to the user of the SupplyDemandManager.
Definition at line 23 of file supply_demand_manager.h.
Constructor & Destructor Documentation
cyclus::SupplyDemandManager::SupplyDemandManager ()
constructor
Definition at line 8 of file supply_demand_manager.cc.
cyclus::SupplyDemandManager::~SupplyDemandManager () [virtual]
virtual destructor
Definition at line 11 of file supply_demand_manager.cc.
Member Function Documentation
double cyclus::SupplyDemandManager::Demand (Commodity & commodity, int time)
the demand for a commodity at a given time
Parameters:
commodity the commodity
time the time
Definition at line 49 of file supply_demand_manager.cc.
References demand_functions_, and ThrowErrorIfCommodityNotManaged().
SymFunction::Ptr cyclus::SupplyDemandManager::DemandFunction (Commodity & commodity)
returns the demand function for a commodity
Parameters:
commodity the commodity being queried
Definition at line 55 of file supply_demand_manager.cc.
References demand_functions_, and ThrowErrorIfCommodityNotManaged().
bool cyclus::SupplyDemandManager::ManagesCommodity (Commodity & commodity)
Returns:
true if the demand for a commodity is managed by this entity
Parameters:
commodity the commodity in question
Definition at line 20 of file supply_demand_manager.cc.
References demand_functions_.
Referenced by ThrowErrorIfCommodityNotManaged().
void cyclus::SupplyDemandManager::RegisterCommodity (Commodity & commodity, SymFunction::Ptr demand)
register a new commodity with the manager, along with all the necessary information
Parameters:
commodity the commodity
demand a smart pointer to the demand function
Definition at line 14 of file supply_demand_manager.cc.
References demand_functions_.
void cyclus::SupplyDemandManager::RegisterProducerManager (CommodityProducerManager * cpm)
adds a commodity producer manager to the set of producer managers
Definition at line 26 of file supply_demand_manager.cc.
References managers_.
double cyclus::SupplyDemandManager::Supply (Commodity & commodity)
returns the current supply of a commodity
Parameters:
commodity the commodity
Returns:
the current supply of the commodity
Definition at line 38 of file supply_demand_manager.cc.
References managers_, and ThrowErrorIfCommodityNotManaged().
void cyclus::SupplyDemandManager::ThrowErrorIfCommodityNotManaged (Commodity & commodity)
checks if ManagesCommodity() is true.
if it is false, an error is thrown.
Parameters:
commodity the commodity in question
Definition at line 61 of file supply_demand_manager.cc.
References ManagesCommodity(), and cyclus::Commodity::name().
Referenced by Demand(), DemandFunction(), and Supply().
void cyclus::SupplyDemandManager::UnRegisterProducerManager (CommodityProducerManager * cpm)
removes a commodity producer manager from the set of producer managers
Definition at line 32 of file supply_demand_manager.cc.
References managers_.
Member Data Documentation
std::map<Commodity, SymFunction::Ptr, CommodityCompare> cyclus::SupplyDemandManager::demand_functions_ [private]
a container of all demand functions known to the manager
Definition at line 91 of file supply_demand_manager.h.
Referenced by Demand(), DemandFunction(), ManagesCommodity(), and RegisterCommodity().
std::set<CommodityProducerManager*> cyclus::SupplyDemandManager::managers_ [private]
a container of all production managers known to the manager
Definition at line 94 of file supply_demand_manager.h.
Referenced by RegisterProducerManager(), Supply(), and UnRegisterProducerManager().
The documentation for this class was generated from the following files:
supply_demand_manager.h
supply_demand_manager.cc