CYCLUS: cyclus::BuildingManager Class Reference
cyclus::BuildingManager Class Reference
The BuildingManager class is a managing entity that makes decisions about which objects to build given certain conditions.
#include <building_manager.h>
Public Member Functions
void AddProducerVariableToProblem (CommodityProducer *producer, Builder *builder, ProblemInstance &problem)
add a variable to the constraint problem
const std::set< Builder * > & builders ()
BuildingManager ()
constructor
void ConstructBuildOrdersFromSolution (std::vector< BuildOrder > &orders, std::vector< Variable::Ptr > &solution)
given a solution to the constraint problem, construct the appropriate set of build orders
std::vector< BuildOrder > MakeBuildDecision (Commodity &commodity, double unmet_demand)
given a certain commodity and demand, a decision is made as to how many producers of each available type to build this function constructs an integer program through the SolverInterface
void RegisterBuilder (Builder *builder)
register a builder with the manager
void SetUpProblem (ProblemInstance &problem)
set up the constraint problem
void UnRegisterBuilder (Builder *builder)
unregister a builder with the manager
virtual ~BuildingManager ()
virtual destructor
Private Attributes
std::set< Builder * > builders_
the set of registered builders
std::map< Variable::Ptr,
std::pair< Builder
*, CommodityProducer * > > solution_map_
a map of variables to their associated builder and producer
Detailed Description
The BuildingManager class is a managing entity that makes decisions about which objects to build given certain conditions.
Specifically, the BuildingManager queries the SupplyDemandManager to determine if there exists unmet demand for a Commodity, and then decides which object(s) amongst that Commodity's producers should be built to meet that demand. This decision takes the form of an integer program:
Where n_i is the number of objects of type i to build, c_i is the cost to build the object of type i, is the nameplate capacity of the object, and is the capacity demand. Here the set I corresponds to all producers of a given commodity.
Definition at line 64 of file building_manager.h.
Constructor & Destructor Documentation
cyclus::BuildingManager::BuildingManager ()
constructor
Definition at line 34 of file building_manager.cc.
cyclus::BuildingManager::~BuildingManager () [virtual]
virtual destructor
Definition at line 37 of file building_manager.cc.
Member Function Documentation
void cyclus::BuildingManager::AddProducerVariableToProblem (CommodityProducer * producer, Builder * builder, ProblemInstance & problem)
add a variable to the constraint problem
Parameters:
producer the producer to add
builder the builder of that producer
problem the problem instance
Definition at line 138 of file building_manager.cc.
References cyclus::SolverInterface::AddVarToConstraint(), cyclus::SolverInterface::AddVarToObjFunction(), cyclus::ProblemInstance::commodity, cyclus::ProblemInstance::constraint, cyclus::Variable::INF, cyclus::ProblemInstance::interface, cyclus::CommodityProducer::ProductionCapacity(), cyclus::CommodityProducer::ProductionCost(), cyclus::SolverInterface::RegisterVariable(), cyclus::ProblemInstance::solution, and solution_map_.
Referenced by SetUpProblem().
const std::set<Builder*>& cyclus::BuildingManager::builders () [inline]
Definition at line 128 of file building_manager.h.
References builders_.
void cyclus::BuildingManager::ConstructBuildOrdersFromSolution (std::vector< BuildOrder > & orders, std::vector< Variable::Ptr > & solution)
given a solution to the constraint problem, construct the appropriate set of build orders
Parameters:
orders the set of orders to fill
solution the solution determining how to fill the orders
Definition at line 158 of file building_manager.cc.
References boost::spirit::any_cast(), and solution_map_.
Referenced by MakeBuildDecision().
std::vector< BuildOrder > cyclus::BuildingManager::MakeBuildDecision (Commodity & commodity, double unmet_demand)
given a certain commodity and demand, a decision is made as to how many producers of each available type to build this function constructs an integer program through the SolverInterface
Parameters:
commodity the commodity being demanded
unmet_demand the additional capacity required
Returns:
a vector of build orders as decided
Definition at line 59 of file building_manager.cc.
References boost::spirit::any_cast(), ConstructBuildOrdersFromSolution(), cyclus::Constraint::GTEQ, cyclus::LEV_DEBUG2, LOG, cyclus::ObjectiveFunction::MIN, cyclus::SolverInterface::RegisterConstraint(), cyclus::SolverInterface::RegisterObjFunction(), SetUpProblem(), and cyclus::SolverInterface::Solve().
void cyclus::BuildingManager::RegisterBuilder (Builder * builder)
register a builder with the manager
Parameters:
builder the builder
Definition at line 40 of file building_manager.cc.
References builders_.
void cyclus::BuildingManager::SetUpProblem (ProblemInstance & problem)
set up the constraint problem
Parameters:
problem the problem instance
Definition at line 117 of file building_manager.cc.
References AddProducerVariableToProblem(), cyclus::Builder::BeginningProducer(), builders_, cyclus::ProblemInstance::commodity, cyclus::Builder::EndingProducer(), cyclus::CommodityProducer::ProducesCommodity(), and solution_map_.
Referenced by MakeBuildDecision().
void cyclus::BuildingManager::UnRegisterBuilder (Builder * builder)
unregister a builder with the manager
Parameters:
builder the builder
Definition at line 49 of file building_manager.cc.
References builders_.
Member Data Documentation
std::set<Builder*> cyclus::BuildingManager::builders_ [private]
the set of registered builders
Definition at line 134 of file building_manager.h.
Referenced by builders(), RegisterBuilder(), SetUpProblem(), and UnRegisterBuilder().
std::map< Variable::Ptr, std::pair<Builder*, CommodityProducer*> > cyclus::BuildingManager::solution_map_ [private]
a map of variables to their associated builder and producer
Definition at line 138 of file building_manager.h.
Referenced by AddProducerVariableToProblem(), ConstructBuildOrdersFromSolution(), and SetUpProblem().
The documentation for this class was generated from the following files:
building_manager.h
building_manager.cc