CYCLUS: cyclus::Trader Class Reference
cyclus::Trader Class Reference
A simple API for agents that wish to exchange resources in the simulation.
#include <trader.h>
Public Member Functions
virtual void AcceptMatlTrades (const std::vector< std::pair< Trade< Material >, Material::Ptr > > &responses)
default implementation for material trade acceptance
virtual void AcceptProductTrades (const std::vector< std::pair< Trade< Product >, Product::Ptr > > &responses)
default implementation for product trade acceptance
virtual void AdjustMatlPrefs (PrefMap< Material >::type &prefs)
default implementation for material preferences.
virtual void AdjustProductPrefs (PrefMap< Product >::type &prefs)
default implementation for material preferences.
virtual std::set< BidPortfolio
< Material >::Ptr > GetMatlBids (const CommodMap< Material >::type &commod_requests)
default implementation for material requests
virtual std::set
< RequestPortfolio< Material >
::Ptr > GetMatlRequests ()
default implementation for material requests
virtual void GetMatlTrades (const std::vector< Trade< Material > > &trades, std::vector< std::pair< Trade< Material >, Material::Ptr > > &responses)
default implementation for responding to material trades
virtual std::set< BidPortfolio
< Product >::Ptr > GetProductBids (const CommodMap< Product >::type &commod_requests)
default implementation for product requests
virtual std::set
< RequestPortfolio< Product >
::Ptr > GetProductRequests ()
default implementation for product requests
virtual void GetProductTrades (const std::vector< Trade< Product > > &trades, std::vector< std::pair< Trade< Product >, Product::Ptr > > &responses)
default implementation for responding to product trades
virtual Agent * manager ()
Trader (Agent *manager)
Private Attributes
Agent * manager_
Detailed Description
A simple API for agents that wish to exchange resources in the simulation.
A Trader is a mixin class designed for agents that wish to exchange resources. It defines the API for the querying of requests, offers, and the corresponding exchanges.
Definition at line 24 of file trader.h.
Constructor & Destructor Documentation
cyclus::Trader::Trader (Agent * manager) [inline]
Definition at line 26 of file trader.h.
Member Function Documentation
virtual void cyclus::Trader::AcceptMatlTrades (const std::vector< std::pair< Trade< Material >, Material::Ptr > > & responses) [inline, virtual]
default implementation for material trade acceptance
Definition at line 79 of file trader.h.
Referenced by cyclus::AcceptTrades().
virtual void cyclus::Trader::AcceptProductTrades (const std::vector< std::pair< Trade< Product >, Product::Ptr > > & responses) [inline, virtual]
default implementation for product trade acceptance
Definition at line 84 of file trader.h.
Referenced by cyclus::AcceptTrades().
virtual void cyclus::Trader::AdjustMatlPrefs (PrefMap< Material >::type & prefs) [inline, virtual]
default implementation for material preferences.
Definition at line 58 of file trader.h.
Referenced by cyclus::AdjustPrefs().
virtual void cyclus::Trader::AdjustProductPrefs (PrefMap< Product >::type & prefs) [inline, virtual]
default implementation for material preferences.
Definition at line 61 of file trader.h.
Referenced by cyclus::AdjustPrefs().
virtual std::set<BidPortfolio<Material>::Ptr> cyclus::Trader::GetMatlBids (const CommodMap< Material >::type & commod_requests) [inline, virtual]
default implementation for material requests
Definition at line 46 of file trader.h.
virtual std::set<RequestPortfolio<Material>::Ptr> cyclus::Trader::GetMatlRequests () [inline, virtual]
default implementation for material requests
Definition at line 34 of file trader.h.
virtual void cyclus::Trader::GetMatlTrades (const std::vector< Trade< Material > > & trades, std::vector< std::pair< Trade< Material >, Material::Ptr > > & responses) [inline, virtual]
default implementation for responding to material trades
Parameters:
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
Definition at line 66 of file trader.h.
virtual std::set<BidPortfolio<Product>::Ptr> cyclus::Trader::GetProductBids (const CommodMap< Product >::type & commod_requests) [inline, virtual]
default implementation for product requests
Definition at line 52 of file trader.h.
virtual std::set<RequestPortfolio<Product>::Ptr> cyclus::Trader::GetProductRequests () [inline, virtual]
default implementation for product requests
Definition at line 40 of file trader.h.
virtual void cyclus::Trader::GetProductTrades (const std::vector< Trade< Product > > & trades, std::vector< std::pair< Trade< Product >, Product::Ptr > > & responses) [inline, virtual]
default implementation for responding to product trades
Parameters:
trades all trades in which this trader is the supplier
responses a container to populate with responses to each trade
Definition at line 73 of file trader.h.
virtual Agent* cyclus::Trader::manager () [inline, virtual]
Definition at line 28 of file trader.h.
References manager_.
Referenced by cyclus::ResourceExchange< T >::AdjustPrefs_().
Member Data Documentation
Agent* cyclus::Trader::manager_ [private]
Definition at line 89 of file trader.h.
Referenced by manager().
The documentation for this class was generated from the following file:
trader.h