CYCLUS: cyclus::ExchangeGraph Class Reference
cyclus::ExchangeGraph Class Reference
An ExchangeGraph is a resource-neutral representation of a ResourceExchange.
#include <exchange_graph.h>
Public Types
typedef boost::shared_ptr
< ExchangeGraph > Ptr
Public Member Functions
void AddArc (const Arc &a)
adds an arc to the graph
void AddMatch (const Arc &a, double qty)
adds a match for a quanity of flow along an arc
void AddRequestGroup (RequestGroup::Ptr prs)
adds a request group to the graph
void AddSupplyGroup (ExchangeNodeGroup::Ptr prs)
adds a supply group to the graph
const std::map< int, Arc > & arc_by_id () const
std::map< int, Arc > & arc_by_id ()
const std::map< Arc, int > & arc_ids () const
std::map< Arc, int > & arc_ids ()
const std::vector< Arc > & arcs () const
std::vector< Arc > & arcs ()
ExchangeGraph ()
const std::vector< Match > & matches ()
const std::map
< ExchangeNode::Ptr,
std::vector< Arc > > & node_arc_map ()
const std::vector
< RequestGroup::Ptr > & request_groups () const
std::vector< RequestGroup::Ptr > & request_groups ()
const std::vector
< ExchangeNodeGroup::Ptr > & supply_groups () const
std::vector
< ExchangeNodeGroup::Ptr > & supply_groups ()
Private Attributes
std::map< int, Arc > arc_by_id_
std::map< Arc, int > arc_ids_
std::vector< Arc > arcs_
std::vector< Match > matches_
int next_arc_id_
std::map< ExchangeNode::Ptr,
std::vector< Arc > > node_arc_map_
std::vector< RequestGroup::Ptr > request_groups_
std::vector
< ExchangeNodeGroup::Ptr > supply_groups_
Detailed Description
An ExchangeGraph is a resource-neutral representation of a ResourceExchange.
In general, it is produced via translation by an ExchangeTranslator. It is comprised of ExchangeNodes that are collected into ExchangeNodeGroups. Arcs are defined, connecting ExchangeNodes to each other. An ExchangeSolver can solve a given instance of an ExchangeGraph, and the solution is stored on the Graph in the form of Matches.
Definition at line 181 of file exchange_graph.h.
Member Typedef Documentation
typedef boost::shared_ptr<ExchangeGraph> cyclus::ExchangeGraph::Ptr
Definition at line 183 of file exchange_graph.h.
Constructor & Destructor Documentation
cyclus::ExchangeGraph::ExchangeGraph ()
Definition at line 121 of file exchange_graph.cc.
Member Function Documentation
void cyclus::ExchangeGraph::AddArc (const Arc & a)
adds an arc to the graph
Definition at line 134 of file exchange_graph.cc.
References arc_by_id_, arc_ids_, arcs_, cyclus::Arc::first, next_arc_id_, node_arc_map_, and cyclus::Arc::second.
void cyclus::ExchangeGraph::AddMatch (const Arc & a, double qty)
adds a match for a quanity of flow along an arc
Parameters:
pa the arc corresponding to a match
qty the amount of flow corresponding to a match
Definition at line 144 of file exchange_graph.cc.
References cyclus::Arc::first, matches_, cyclus::Arc::second, and cyclus::UpdateCapacity().
Referenced by cyclus::ProgTranslator::FromProg(), and cyclus::GreedySolver::GreedilySatisfySet_().
void cyclus::ExchangeGraph::AddRequestGroup (RequestGroup::Ptr prs)
adds a request group to the graph
Definition at line 124 of file exchange_graph.cc.
References request_groups_.
void cyclus::ExchangeGraph::AddSupplyGroup (ExchangeNodeGroup::Ptr prs)
adds a supply group to the graph
Definition at line 129 of file exchange_graph.cc.
References supply_groups_.
const std::map<int, Arc>& cyclus::ExchangeGraph::arc_by_id () const [inline]
Definition at line 228 of file exchange_graph.h.
References arc_by_id_.
Referenced by cyclus::ProgTranslator::FromProg().
std::map<int, Arc>& cyclus::ExchangeGraph::arc_by_id () [inline]
Definition at line 229 of file exchange_graph.h.
References arc_by_id_.
const std::map<Arc, int>& cyclus::ExchangeGraph::arc_ids () const [inline]
Definition at line 225 of file exchange_graph.h.
References arc_ids_.
Referenced by cyclus::ProgTranslator::Populate(), and cyclus::ProgTranslator::XlateGrp_().
std::map<Arc, int>& cyclus::ExchangeGraph::arc_ids () [inline]
Definition at line 226 of file exchange_graph.h.
References arc_ids_.
const std::vector<Arc>& cyclus::ExchangeGraph::arcs () const [inline]
Definition at line 222 of file exchange_graph.h.
References arcs_.
Referenced by cyclus::ProgTranslator::FromProg(), cyclus::ProgTranslator::Populate(), cyclus::ProgTranslator::ProgTranslator(), and cyclus::ProgTranslator::Translate().
std::vector<Arc>& cyclus::ExchangeGraph::arcs () [inline]
Definition at line 223 of file exchange_graph.h.
References arcs_.
const std::vector<Match>& cyclus::ExchangeGraph::matches () [inline]
Definition at line 220 of file exchange_graph.h.
References matches_.
const std::map<ExchangeNode::Ptr, std::vector<Arc> >& cyclus::ExchangeGraph::node_arc_map () [inline]
Definition at line 216 of file exchange_graph.h.
References node_arc_map_.
Referenced by cyclus::GreedySolver::GreedilySatisfySet_().
const std::vector<RequestGroup::Ptr>& cyclus::ExchangeGraph::request_groups () const [inline]
Definition at line 202 of file exchange_graph.h.
References request_groups_.
Referenced by cyclus::GreedyPreconditioner::Condition(), cyclus::ProgTranslator::ProgTranslator(), cyclus::GreedySolver::Solve(), and cyclus::ProgTranslator::Translate().
std::vector<RequestGroup::Ptr>& cyclus::ExchangeGraph::request_groups () [inline]
Definition at line 205 of file exchange_graph.h.
References request_groups_.
const std::vector<ExchangeNodeGroup::Ptr>& cyclus::ExchangeGraph::supply_groups () const [inline]
Definition at line 209 of file exchange_graph.h.
References supply_groups_.
Referenced by cyclus::ProgTranslator::Translate().
std::vector<ExchangeNodeGroup::Ptr>& cyclus::ExchangeGraph::supply_groups () [inline]
Definition at line 212 of file exchange_graph.h.
References supply_groups_.
Member Data Documentation
std::map<int, Arc> cyclus::ExchangeGraph::arc_by_id_ [private]
Definition at line 238 of file exchange_graph.h.
Referenced by AddArc(), and arc_by_id().
std::map<Arc, int> cyclus::ExchangeGraph::arc_ids_ [private]
Definition at line 237 of file exchange_graph.h.
Referenced by AddArc(), and arc_ids().
std::vector<Arc> cyclus::ExchangeGraph::arcs_ [private]
Definition at line 236 of file exchange_graph.h.
Referenced by AddArc(), and arcs().
std::vector<Match> cyclus::ExchangeGraph::matches_ [private]
Definition at line 235 of file exchange_graph.h.
Referenced by AddMatch(), and matches().
int cyclus::ExchangeGraph::next_arc_id_ [private]
Definition at line 239 of file exchange_graph.h.
Referenced by AddArc().
std::map<ExchangeNode::Ptr, std::vector<Arc> > cyclus::ExchangeGraph::node_arc_map_ [private]
Definition at line 234 of file exchange_graph.h.
Referenced by AddArc(), and node_arc_map().
std::vector<RequestGroup::Ptr> cyclus::ExchangeGraph::request_groups_ [private]
Definition at line 232 of file exchange_graph.h.
Referenced by AddRequestGroup(), and request_groups().
std::vector<ExchangeNodeGroup::Ptr> cyclus::ExchangeGraph::supply_groups_ [private]
Definition at line 233 of file exchange_graph.h.
Referenced by AddSupplyGroup(), and supply_groups().
The documentation for this class was generated from the following files:
exchange_graph.h
exchange_graph.cc