CYCLUS: cyclus::ExchangeSolver Class Reference
cyclus::ExchangeSolver Class Reference
a very simple interface for solving translated resource exchanges
#include <exchange_solver.h>
Public Member Functions
ExchangeSolver (bool exclusive_orders=false)
void Solve (ExchangeGraph *graph)
interface for solving a given exchange graph
virtual ~ExchangeSolver ()
Protected Member Functions
virtual void Solve ()=0
Worker function for solving a graph.
Protected Attributes
bool exclusive_orders_
ExchangeGraph * graph_
Detailed Description
a very simple interface for solving translated resource exchanges
Definition at line 11 of file exchange_solver.h.
Constructor & Destructor Documentation
cyclus::ExchangeSolver::ExchangeSolver (bool exclusive_orders = false) [inline, explicit]
Definition at line 13 of file exchange_solver.h.
virtual cyclus::ExchangeSolver::~ExchangeSolver () [inline, virtual]
Definition at line 14 of file exchange_solver.h.
Member Function Documentation
void cyclus::ExchangeSolver::Solve (ExchangeGraph * graph) [inline]
interface for solving a given exchange graph
Parameters:
a pointer to the graph to be solved
Definition at line 18 of file exchange_solver.h.
References graph_, and Solve().
Referenced by cyclus::ExchangeManager< T >::Execute().
virtual void cyclus::ExchangeSolver::Solve () [protected, pure virtual]
Worker function for solving a graph.
This must be implemented by any solver.
Implemented in cyclus::GreedySolver, and cyclus::ProgSolver.
Referenced by Solve().
Member Data Documentation
bool cyclus::ExchangeSolver::exclusive_orders_ [protected]
Definition at line 28 of file exchange_solver.h.
Referenced by cyclus::ProgSolver::Solve().
ExchangeGraph* cyclus::ExchangeSolver::graph_ [protected]
Definition at line 27 of file exchange_solver.h.
Referenced by cyclus::GreedySolver::GreedilySatisfySet_(), Solve(), cyclus::ProgSolver::Solve(), and cyclus::GreedySolver::Solve().
The documentation for this class was generated from the following file:
exchange_solver.h