CYCLUS: cyclus::SolverInterface Class Reference
cyclus::SolverInterface Class Reference
A general interface class for all derived optim solvers to set up and solve a constraint program.
#include <solver_interface.h>
Public Member Functions
void AddVarToConstraint (Variable::Ptr v, double modifier, Constraint::Ptr c)
add a variable to a constraint
void AddVarToObjFunction (Variable::Ptr v, double modifier)
add a variable to the objective function
void RegisterConstraint (Constraint::Ptr c)
add a constraint
void RegisterObjFunction (ObjectiveFunction::Ptr obj)
set the objective function
void RegisterVariable (Variable::Ptr v)
add a variable
void Solve ()
solve the constraint program
SolverInterface (Solver::Ptr solver)
constructor
Private Member Functions
void CheckModifierBounds (double modifier)
checks if a modifier is within the acceptable bounds for modifiers
Private Attributes
std::vector< Constraint::Ptr > constraints_
the constraints
double modifier_limit_
a limit on the modifiers of constraints
ObjectiveFunction::Ptr obj_
the objective function
Solver::Ptr solver_
the solver
std::vector< Variable::Ptr > variables_
the variables
Detailed Description
A general interface class for all derived optim solvers to set up and solve a constraint program.
Definition at line 14 of file solver_interface.h.
Constructor & Destructor Documentation
cyclus::SolverInterface::SolverInterface (Solver::Ptr solver)
constructor
Parameters:
solver a pointer to the concrete solver to which an interface will be provided.
Definition at line 13 of file solver_interface.cc.
References constraints_, cyclus::kModifierLimit, modifier_limit_, and variables_.
Member Function Documentation
void cyclus::SolverInterface::AddVarToConstraint (Variable::Ptr v, double modifier, Constraint::Ptr c)
add a variable to a constraint
Parameters:
v the variable to add to a constraint
modifier the modifier for that variable in the constraint
c the constraint to add it to
Definition at line 42 of file solver_interface.cc.
References CheckModifierBounds(), and constraints_.
Referenced by cyclus::BuildingManager::AddProducerVariableToProblem().
void cyclus::SolverInterface::AddVarToObjFunction (Variable::Ptr v, double modifier)
add a variable to the objective function
Parameters:
v the variable to add to the obj function
modifier the modifier for that variable in the obj function
Definition at line 30 of file solver_interface.cc.
References CheckModifierBounds(), and obj_.
Referenced by cyclus::BuildingManager::AddProducerVariableToProblem().
void cyclus::SolverInterface::CheckModifierBounds (double modifier) [private]
checks if a modifier is within the acceptable bounds for modifiers
Definition at line 59 of file solver_interface.cc.
References modifier_limit_.
Referenced by AddVarToConstraint(), and AddVarToObjFunction().
void cyclus::SolverInterface::RegisterConstraint (Constraint::Ptr c)
add a constraint
Parameters:
c a pointer to a constraint function to register
Definition at line 37 of file solver_interface.cc.
References constraints_.
Referenced by cyclus::BuildingManager::MakeBuildDecision().
void cyclus::SolverInterface::RegisterObjFunction (ObjectiveFunction::Ptr obj)
set the objective function
Parameters:
obj a pointer to the objective function to register
Definition at line 25 of file solver_interface.cc.
References obj_.
Referenced by cyclus::BuildingManager::MakeBuildDecision().
void cyclus::SolverInterface::RegisterVariable (Variable::Ptr v)
add a variable
Parameters:
v a pointer to the variable to register with the problem
Definition at line 20 of file solver_interface.cc.
References variables_.
Referenced by cyclus::BuildingManager::AddProducerVariableToProblem().
void cyclus::SolverInterface::Solve ()
solve the constraint program
Definition at line 54 of file solver_interface.cc.
References constraints_, obj_, solver_, and variables_.
Referenced by cyclus::BuildingManager::MakeBuildDecision().
Member Data Documentation
std::vector<Constraint::Ptr> cyclus::SolverInterface::constraints_ [private]
the constraints
Definition at line 59 of file solver_interface.h.
Referenced by AddVarToConstraint(), RegisterConstraint(), Solve(), and SolverInterface().
double cyclus::SolverInterface::modifier_limit_ [private]
a limit on the modifiers of constraints
Definition at line 62 of file solver_interface.h.
Referenced by CheckModifierBounds(), and SolverInterface().
ObjectiveFunction::Ptr cyclus::SolverInterface::obj_ [private]
the objective function
Definition at line 56 of file solver_interface.h.
Referenced by AddVarToObjFunction(), RegisterObjFunction(), and Solve().
Solver::Ptr cyclus::SolverInterface::solver_ [private]
the solver
Definition at line 50 of file solver_interface.h.
Referenced by Solve().
std::vector<Variable::Ptr> cyclus::SolverInterface::variables_ [private]
the variables
Definition at line 53 of file solver_interface.h.
Referenced by RegisterVariable(), Solve(), and SolverInterface().
The documentation for this class was generated from the following files:
solver_interface.h
solver_interface.cc