CYCLUS: cyclus::Decayer Class Reference
cyclus::Decayer Class Reference
#include <decayer.h>
Public Member Functions
void Decay (double secs)
decay the material
Decayer (const CompMap &comp)
void GetResult (CompMap &comp)
set the composition from a CompMap
int n_tracked_nuclides ()
the number of tracked nuclides
int TrackedNuclide (int i)
the tracked nuclide at position i
Static Private Member Functions
static void AddNucToList (int nuc)
Add the nuclide to our list of tracked nuclides IFF it is not in the list.
static void AddNucToMaps (int nuc)
Add the nuclide to the parent/daughter maps IFF it is not in the tracked list.
static void BuildDecayMatrix ()
Builds the decay matrix needed for the decay calculations from the parent and daughters map variables.
static bool IsNucTracked (int nuc)
Checks if the nuclide is tracked.
Private Attributes
Vector post_vect_
Vector pre_vect_
The atomic composition map.
Static Private Attributes
static DaughtersMap daughters_ = DaughtersMap()
The CompMap's daughters.
static Matrix decay_matrix_ = Matrix()
The decay matrix.
static NucList nuclides_tracked_ = NucList()
the list of tracked nuclides
static ParentMap parent_ = ParentMap()
The CompMap's parent.
Detailed Description
Definition at line 29 of file decayer.h.
Constructor & Destructor Documentation
cyclus::Decayer::Decayer (const CompMap & comp)
Definition at line 20 of file decayer.cc.
References AddNucToMaps(), BuildDecayMatrix(), IsNucTracked(), parent_, and pre_vect_.
Member Function Documentation
void cyclus::Decayer::AddNucToList (int nuc) [static, private]
Add the nuclide to our list of tracked nuclides IFF it is not in the list.
Definition at line 82 of file decayer.cc.
References IsNucTracked(), and nuclides_tracked_.
Referenced by AddNucToMaps().
void cyclus::Decayer::AddNucToMaps (int nuc) [static, private]
Add the nuclide to the parent/daughter maps IFF it is not in the tracked list.
Definition at line 49 of file decayer.cc.
References AddNucToList(), daughters_, IsNucTracked(), and parent_.
Referenced by Decayer().
void cyclus::Decayer::BuildDecayMatrix () [static, private]
Builds the decay matrix needed for the decay calculations from the parent and daughters map variables.
The resulting matrix is stored in the static variable decayMatrix.
Definition at line 112 of file decayer.cc.
References daughters_, decay_matrix_, and parent_.
Referenced by Decayer().
void cyclus::Decayer::Decay (double secs)
decay the material
Parameters:
secs the number of seconds to decay
Definition at line 151 of file decayer.cc.
References decay_matrix_, cyclus::UniformTaylor::MatrixExpSolver(), post_vect_, and pre_vect_.
Referenced by cyclus::Composition::NewDecay().
void cyclus::Decayer::GetResult (CompMap & comp)
set the composition from a CompMap
Definition at line 89 of file decayer.cc.
References cyclus::LEV_ERROR, LOG, cyclus::LMatrix::NumRows(), parent_, and post_vect_.
Referenced by cyclus::Composition::NewDecay().
bool cyclus::Decayer::IsNucTracked (int nuc) [static, private]
Checks if the nuclide is tracked.
Definition at line 76 of file decayer.cc.
References nuclides_tracked_.
Referenced by AddNucToList(), AddNucToMaps(), and Decayer().
int cyclus::Decayer::n_tracked_nuclides () [inline]
the number of tracked nuclides
Definition at line 45 of file decayer.h.
References nuclides_tracked_.
int cyclus::Decayer::TrackedNuclide (int i) [inline]
the tracked nuclide at position i
Definition at line 52 of file decayer.h.
References nuclides_tracked_.
Member Data Documentation
DaughtersMap cyclus::Decayer::daughters_ = DaughtersMap() [static, private]
The CompMap's daughters.
Definition at line 72 of file decayer.h.
Referenced by AddNucToMaps(), and BuildDecayMatrix().
Matrix cyclus::Decayer::decay_matrix_ = Matrix() [static, private]
The decay matrix.
Definition at line 77 of file decayer.h.
Referenced by BuildDecayMatrix(), and Decay().
NucList cyclus::Decayer::nuclides_tracked_ = NucList() [static, private]
the list of tracked nuclides
Definition at line 88 of file decayer.h.
Referenced by AddNucToList(), IsNucTracked(), n_tracked_nuclides(), and TrackedNuclide().
ParentMap cyclus::Decayer::parent_ = ParentMap() [static, private]
The CompMap's parent.
Definition at line 67 of file decayer.h.
Referenced by AddNucToMaps(), BuildDecayMatrix(), Decayer(), and GetResult().
Vector cyclus::Decayer::post_vect_ [private]
Definition at line 83 of file decayer.h.
Referenced by Decay(), and GetResult().
Vector cyclus::Decayer::pre_vect_ [private]
The atomic composition map.
Definition at line 82 of file decayer.h.
Referenced by Decay(), and Decayer().
The documentation for this class was generated from the following files:
decayer.h
decayer.cc