CYCLUS: cyclus::Material Class Reference
cyclus::Material Class Reference
The material class is primarily responsible for enabling basic material manipulation while helping enforce mass conservation.
#include <material.h>
Public Types
typedef boost::shared_ptr
< Material > Ptr
Public Member Functions
void Absorb (Ptr mat)
Combines material mat with this one. mat's quantity becomes zero.
virtual Resource::Ptr Clone () const
Returns an untracked (not part of the simulation) copy of the resource.
Composition::Ptr comp () const
Returns the nuclide composition of this material.
void Decay (int curr_time)
A special case of Transmute where the new composition is calculated by performing a decay calculation on the material's composition.
Ptr ExtractComp (double qty, Composition::Ptr c, double threshold=eps_rsrc())
Creates a new material by extracting from this one.
Ptr ExtractQty (double qty)
Same as ExtractComp with c = this->comp().
virtual Resource::Ptr ExtractRes (double qty)
Splits the resource and returns the extracted portion as a new resource object.
virtual double quantity () const
Returns the mass of this material in kg.
virtual void Record (Context *ctx) const
Records the internal nuclide composition of this resource.
virtual int state_id () const
Returns the id of the material's internal nuclide composition.
void Transmute (Composition::Ptr c)
Changes the material's composition to c without changing its mass.
virtual const ResourceType type () const
Returns Material::kType.
virtual std::string units () const
Returns "kg".
virtual ~Material ()
Static Public Member Functions
static Ptr Create (Agent *creator, double quantity, Composition::Ptr c)
Creates a new material resource that is "live" and tracked.
static Ptr CreateUntracked (double quantity, Composition::Ptr c)
Creates a new material resource that does not actually exist as part of the simulation and is untracked.
static void DecayAll (int curr_time)
Calls Decay for all materials currently existing in the simulation.
Static Public Attributes
static const ResourceType kType = "Material"
Protected Member Functions
Material (Context *ctx, double quantity, Composition::Ptr c)
Private Attributes
Composition::Ptr comp_
Context * ctx_
int prev_decay_time_
double qty_
ResTracker tracker_
Static Private Attributes
static std::map< Material *, bool > all_mats_
Friends
class SimInit
Detailed Description
The material class is primarily responsible for enabling basic material manipulation while helping enforce mass conservation.
It also provides the ability to easily decay a material up to the current simulation time; it does not perform any decay related logic itself.
There are four basic operations that can be performed on materials: create, transmute (change material composition - e.g. fission by reactor), absorb (combine materials), extract (split a material). All material handling/manipulation will be performed using these operations - and all operations performed will be tracked and recorded. Usage examples:
A mining facility that "creates" new material
   Composition::Ptr nat_u = ...
   double qty = 10.0;
   Material::Ptr m = Material::Create(qty, nat_u, ctx);
A conversion facility mixing uranium and flourine:
   Material::Ptr uf6 = uranium_buf.Pop();
   Material::Ptr f = flourine_buf.Pop();
   uf6.Absorb(f);
A reactor transmuting fuel:
   Composition::Ptr burned_comp = ... // fancy code to calculate burned nuclides
   Material::Ptr assembly = core_fuel.Pop();
   assembly.Transmute(burned_comp);
A separations plant extracting stuff from spent fuel:
   Composition::Ptr comp = ... // fancy code to calculate extracted nuclides
   Material::Ptr bucket = spent_fuel.Pop();
   double qty = 3.0;
   Material::Ptr mox = bucket.ExtractComp(qty, comp);
Definition at line 71 of file material.h.
Member Typedef Documentation
typedef boost::shared_ptr<Material> cyclus::Material::Ptr
Reimplemented from cyclus::Resource.
Definition at line 75 of file material.h.
Constructor & Destructor Documentation
cyclus::Material::~Material () [virtual]
Definition at line 16 of file material.cc.
References all_mats_.
cyclus::Material::Material (Context * ctx, double quantity, Composition::Ptr c) [protected]
Definition at line 159 of file material.cc.
References cyclus::ResTracker::DontTrack(), prev_decay_time_, cyclus::Context::time(), and tracker_.
Referenced by Clone(), Create(), CreateUntracked(), and ExtractComp().
Member Function Documentation
void cyclus::Material::Absorb (Material::Ptr mat)
Combines material mat with this one. mat's quantity becomes zero.
Definition at line 99 of file material.cc.
References cyclus::ResTracker::Absorb(), cyclus::compmath::Add(), comp_, cyclus::Composition::CreateFromAtom(), cyclus::compmath::Normalize(), qty_, and tracker_.
Resource::Ptr cyclus::Material::Clone () const [virtual]
Returns an untracked (not part of the simulation) copy of the resource.
A cloned resource should never record anything in the output database.
Implements cyclus::Resource.
Definition at line 42 of file material.cc.
References cyclus::ResTracker::DontTrack(), Material(), and tracker_.
Composition::Ptr cyclus::Material::comp () const
Returns the nuclide composition of this material.
Definition at line 155 of file material.cc.
References comp_.
Material::Ptr cyclus::Material::Create (Agent * creator, double quantity, Composition::Ptr c) [static]
Creates a new material resource that is "live" and tracked.
creator is a pointer to the agent creating the resource (usually will be the caller's "this" pointer). All future output data recorded will be done using the creator's context.
Definition at line 20 of file material.cc.
References all_mats_, cyclus::Agent::context(), Material(), and quantity().
Referenced by cyclus::SimInit::LoadMaterial().
Material::Ptr cyclus::Material::CreateUntracked (double quantity, Composition::Ptr c) [static]
Creates a new material resource that does not actually exist as part of the simulation and is untracked.
Definition at line 28 of file material.cc.
References Material().
Referenced by cyclus::NewBlankMaterial().
void cyclus::Material::Decay (int curr_time)
A special case of Transmute where the new composition is calculated by performing a decay calculation on the material's composition.
The time delta is calculated as the difference between curr_time and the last time Decay was invoked.
Definition at line 118 of file material.cc.
References comp_, cyclus::eps(), prev_decay_time_, and Transmute().
void cyclus::Material::DecayAll (int curr_time) [static]
Calls Decay for all materials currently existing in the simulation.
Definition at line 148 of file material.cc.
References all_mats_.
Referenced by cyclus::Timer::RunSim().
Material::Ptr cyclus::Material::ExtractComp (double qty, Composition::Ptr c, double threshold = eps_rsrc())
Creates a new material by extracting from this one.
Parameters:
qty the mass quantity to extract
c the composition the extracted/returned material
threshold an absolute mass cutoff below which constituent nuclide quantities of the remaining unextracted material are set to zero.
Returns:
a new material with quantity qty and composition c
Definition at line 75 of file material.cc.
References cyclus::compmath::ApplyThreshold(), comp_, cyclus::Composition::CreateFromMass(), ctx_, cyclus::ResTracker::Extract(), Material(), cyclus::compmath::Normalize(), qty_, cyclus::compmath::Sub(), and tracker_.
Referenced by ExtractQty().
Material::Ptr cyclus::Material::ExtractQty (double qty)
Same as ExtractComp with c = this->comp().
Definition at line 71 of file material.cc.
References comp_, and ExtractComp().
Referenced by ExtractRes().
Resource::Ptr cyclus::Material::ExtractRes (double quantity) [virtual]
Splits the resource and returns the extracted portion as a new resource object.
Allows for things like ResourceBuff and Traders to split offers/requests of arbitrary resource implementation type.
Returns:
a new resource object with same state id and quantity == quantity
Implements cyclus::Resource.
Definition at line 67 of file material.cc.
References ExtractQty().
double cyclus::Material::quantity () const [virtual]
Returns the mass of this material in kg.
Implements cyclus::Resource.
Definition at line 63 of file material.cc.
References qty_.
Referenced by Create().
void cyclus::Material::Record (Context * ctx) const [virtual]
Records the internal nuclide composition of this resource.
Implements cyclus::Resource.
Definition at line 49 of file material.cc.
References cyclus::Datum::AddVal(), comp_, ctx_, cyclus::Context::NewDatum(), prev_decay_time_, cyclus::Datum::Record(), and cyclus::Context::time().
int cyclus::Material::state_id () const [virtual]
Returns the id of the material's internal nuclide composition.
Implements cyclus::Resource.
Definition at line 34 of file material.cc.
References comp_.
void cyclus::Material::Transmute (Composition::Ptr c)
Changes the material's composition to c without changing its mass.
Use this method for things like converting fresh to spent fuel via burning in a reactor.
Definition at line 113 of file material.cc.
References comp_, cyclus::ResTracker::Modify(), and tracker_.
Referenced by Decay().
const ResourceType cyclus::Material::type () const [virtual]
Returns Material::kType.
Implements cyclus::Resource.
Definition at line 38 of file material.cc.
References kType.
std::string cyclus::Material::units () const [virtual]
Returns "kg".
Implements cyclus::Resource.
Definition at line 59 of file material.cc.
Friends And Related Function Documentation
friend class SimInit [friend]
Reimplemented from cyclus::Resource.
Definition at line 72 of file material.h.
Member Data Documentation
std::map< Material *, bool > cyclus::Material::all_mats_ [static, private]
Definition at line 145 of file material.h.
Referenced by Create(), DecayAll(), and ~Material().
Composition::Ptr cyclus::Material::comp_ [private]
Definition at line 149 of file material.h.
Referenced by Absorb(), comp(), Decay(), ExtractComp(), ExtractQty(), Record(), state_id(), and Transmute().
Context* cyclus::Material::ctx_ [private]
Definition at line 147 of file material.h.
Referenced by ExtractComp(), and Record().
const ResourceType cyclus::Material::kType = "Material" [static]
Definition at line 76 of file material.h.
Referenced by cyclus::SimInit::LoadResource(), and type().
int cyclus::Material::prev_decay_time_ [private]
Definition at line 150 of file material.h.
Referenced by Decay(), Material(), and Record().
double cyclus::Material::qty_ [private]
Definition at line 148 of file material.h.
Referenced by Absorb(), ExtractComp(), and quantity().
ResTracker cyclus::Material::tracker_ [private]
Definition at line 151 of file material.h.
Referenced by Absorb(), Clone(), ExtractComp(), Material(), and Transmute().
The documentation for this class was generated from the following files:
material.h
material.cc