CYCLUS: cyclus::BidPortfolio< T > Class Template Reference
cyclus::BidPortfolio< T > Class Template Reference
A BidPortfolio is a collection of bids as responses to requests for resources and associated constraints on those bids.
#include <bid_portfolio.h>
Public Types
typedef boost::shared_ptr
< BidPortfolio< T > > Ptr
Public Member Functions
Bid< T >::Ptr AddBid (typename Request< T >::Ptr request, boost::shared_ptr< T > offer, Trader *bidder, bool exclusive=false)
add a bid to the portfolio
void AddConstraint (const CapacityConstraint< T > &c)
add a capacity constraint associated with the portfolio
Trader * bidder () const
BidPortfolio ()
default constructor
const std::set< typename Bid
< T >::Ptr > & bids () const
std::string commodity () const
const std::set
< CapacityConstraint< T > > & constraints () const
Private Member Functions
BidPortfolio (const BidPortfolio &rhs)
copy constructor is private to prevent copying and preserve explicit single-ownership of bids
void VerifyCommodity_ (const typename Bid< T >::Ptr r)
if the commodity has not been determined yet, it is set.
void VerifyResponder_ (typename Bid< T >::Ptr b)
if the bidder has not been determined yet, it is set.
Private Attributes
Trader * bidder_
std::set< typename Bid< T >::Ptr > bids_
std::string commodity_
std::set< CapacityConstraint< T > > constraints_
Detailed Description
template<class T>
class cyclus::BidPortfolio< T >
A BidPortfolio is a collection of bids as responses to requests for resources and associated constraints on those bids.
A BidPortfolio contains all the information corresponding to a bidder's response to resource requests. It is a light wrapper around the set of bids and constraints for a given bidder, guaranteeing a single bidder and commodity per portfolio. Responses are grouped by both the bidder and the commodity that it produces. Constraints are assumed to act over the entire set of possible bids.
Definition at line 29 of file bid_portfolio.h.
Member Typedef Documentation
template<class T> typedef boost::shared_ptr< BidPortfolio<T> > cyclus::BidPortfolio< T >::Ptr
Definition at line 31 of file bid_portfolio.h.
Constructor & Destructor Documentation
template<class T> cyclus::BidPortfolio< T >::BidPortfolio () [inline]
default constructor
Definition at line 34 of file bid_portfolio.h.
template<class T> cyclus::BidPortfolio< T >::BidPortfolio (const BidPortfolio< T > & rhs) [inline, private]
copy constructor is private to prevent copying and preserve explicit single-ownership of bids
Definition at line 88 of file bid_portfolio.h.
References cyclus::BidPortfolio< T >::bidder_, cyclus::BidPortfolio< T >::bids_, cyclus::BidPortfolio< T >::commodity_, and cyclus::BidPortfolio< T >::constraints_.
Member Function Documentation
template<class T> Bid<T>::Ptr cyclus::BidPortfolio< T >::AddBid (typename Request< T >::Ptr request, boost::shared_ptr< T > offer, Trader * bidder, bool exclusive = false) [inline]
add a bid to the portfolio
Parameters:
request the request being responded to by this bid
offer the resource being offered in response to the request
bidder the bidder
Exceptions:
KeyError if a bid is added from a different bidder than the original or if the bid commodity is different than the original
Definition at line 44 of file bid_portfolio.h.
References cyclus::BidPortfolio< T >::bids_, cyclus::BidPortfolio< T >::VerifyCommodity_(), and cyclus::BidPortfolio< T >::VerifyResponder_().
template<class T> void cyclus::BidPortfolio< T >::AddConstraint (const CapacityConstraint< T > & c) [inline]
add a capacity constraint associated with the portfolio
Parameters:
c the constraint to add
Definition at line 59 of file bid_portfolio.h.
References cyclus::BidPortfolio< T >::constraints_.
template<class T> Trader* cyclus::BidPortfolio< T >::bidder () const [inline]
Returns:
the agent associated with the portfolio. If no bids have been added, the bidder is NULL.
Definition at line 65 of file bid_portfolio.h.
References cyclus::BidPortfolio< T >::bidder_.
template<class T> const std::set<typename Bid<T>::Ptr>& cyclus::BidPortfolio< T >::bids () const [inline]
Returns:
const access to the bids
Definition at line 76 of file bid_portfolio.h.
References cyclus::BidPortfolio< T >::bids_.
Referenced by cyclus::ExchangeContext< T >::AddBidPortfolio(), and cyclus::TranslateBidPortfolio().
template<class T> std::string cyclus::BidPortfolio< T >::commodity () const [inline]
Returns:
the commodity associated with the portfolio. If no bids have been added, the commodity is 'NO_COMMODITY_SET'.
Definition at line 71 of file bid_portfolio.h.
References cyclus::BidPortfolio< T >::commodity_.
template<class T> const std::set< CapacityConstraint<T> >& cyclus::BidPortfolio< T >::constraints () const [inline]
Returns:
the set of constraints over the bids
Definition at line 81 of file bid_portfolio.h.
References cyclus::BidPortfolio< T >::constraints_.
Referenced by cyclus::TranslateArc(), and cyclus::TranslateBidPortfolio().
template<class T> void cyclus::BidPortfolio< T >::VerifyCommodity_ (const typename Bid< T >::Ptr r) [inline, private]
if the commodity has not been determined yet, it is set.
Otherwise VerifyCommodity() verifies the commodity is associated with the portfolio's commodity
Exceptions:
KeyError if a commodity is added that is a different commodity from the original
Definition at line 118 of file bid_portfolio.h.
References cyclus::BidPortfolio< T >::commodity_, and cyclus::Bid< T >::request().
Referenced by cyclus::BidPortfolio< T >::AddBid().
template<class T> void cyclus::BidPortfolio< T >::VerifyResponder_ (typename Bid< T >::Ptr b) [inline, private]
if the bidder has not been determined yet, it is set.
Otherwise VerifyResponder() verifies the bid is associated with the portfolio's bidder
Exceptions:
KeyError if a bid is added from a different bidder than the original
Definition at line 104 of file bid_portfolio.h.
References cyclus::Bid< T >::bidder(), and cyclus::BidPortfolio< T >::bidder_.
Referenced by cyclus::BidPortfolio< T >::AddBid().
Member Data Documentation
template<class T> Trader* cyclus::BidPortfolio< T >::bidder_ [private]
Definition at line 136 of file bid_portfolio.h.
Referenced by cyclus::BidPortfolio< T >::bidder(), cyclus::BidPortfolio< T >::BidPortfolio(), and cyclus::BidPortfolio< T >::VerifyResponder_().
template<class T> std::set< typename Bid<T>::Ptr > cyclus::BidPortfolio< T >::bids_ [private]
Definition at line 130 of file bid_portfolio.h.
Referenced by cyclus::BidPortfolio< T >::AddBid(), cyclus::BidPortfolio< T >::BidPortfolio(), and cyclus::BidPortfolio< T >::bids().
template<class T> std::string cyclus::BidPortfolio< T >::commodity_ [private]
Definition at line 135 of file bid_portfolio.h.
Referenced by cyclus::BidPortfolio< T >::BidPortfolio(), cyclus::BidPortfolio< T >::commodity(), and cyclus::BidPortfolio< T >::VerifyCommodity_().
template<class T> std::set< CapacityConstraint<T> > cyclus::BidPortfolio< T >::constraints_ [private]
Definition at line 133 of file bid_portfolio.h.
Referenced by cyclus::BidPortfolio< T >::AddConstraint(), cyclus::BidPortfolio< T >::BidPortfolio(), and cyclus::BidPortfolio< T >::constraints().
The documentation for this class was generated from the following file:
bid_portfolio.h