CYCLUS: cyclus::ResourceBuff Class Reference
cyclus::ResourceBuff Class Reference
ResourceBuff is a helper function that provides semi-automated management of resource buffers (e.g.
#include <resource_buff.h>
Public Types
enum AccessDir { FRONT, BACK }
Public Member Functions
double capacity () const
capacity returns the maximum resource quantity this store can hold (units based on constituent resource objects' units).
int count () const
count returns the total number of constituent resource objects in the store.
bool empty () const
returns true if there are no mats in mats_
Resource::Ptr Pop (AccessDir dir=FRONT)
Pop pops one resource object from the store.
template<class T >
T::Ptr Pop ()
A convenience method identical to Pop for auto-casting to specific Resource types.
Manifest PopN (int num)
PopN pops the specified number or count of resource objects from the store.
Manifest PopQty (double qty)
PopQty pops the specified quantity of resources from the store.
void Push (Resource::Ptr r)
Push pushs a single resource object to the store.
template<class B >
void PushAll (std::vector< B > rs)
PushAll pushess one or more resource objects (as a std::vector) to the store.
double quantity () const
quantity returns the total resource quantity of constituent resource objects in the store.
ResourceBuff ()
void set_capacity (double cap)
set_capacity sets the maximum quantity this store can hold (units based on constituent resource objects' units).
double space () const
space returns the quantity of space remaining in this store.
virtual ~ResourceBuff ()
Private Attributes
double capacity_
maximum quantity of resources this store can hold
std::list< Resource::Ptr > mats_
list of constituent resource objects forming the store's inventory
std::set< Resource::Ptr > mats_present_
double qty_
Detailed Description
ResourceBuff is a helper function that provides semi-automated management of resource buffers (e.g.
agent stocks and inventories).
Methods that begin with a "set", "make", "push", or "pop" prefix change the state/behavior of the store; other methods do not. Default constructed resource store has infinite capacity. Resource popping occurs in the order the resources were pushed (i.e. oldest resources are popped first), unless explicitly specified otherwise.
Definition at line 46 of file resource_buff.h.
Member Enumeration Documentation
enum cyclus::ResourceBuff::AccessDir
Enumerator:
FRONT
BACK
Definition at line 48 of file resource_buff.h.
Constructor & Destructor Documentation
cyclus::ResourceBuff::ResourceBuff () [inline]
Definition at line 53 of file resource_buff.h.
virtual cyclus::ResourceBuff::~ResourceBuff () [inline, virtual]
Definition at line 55 of file resource_buff.h.
Member Function Documentation
double cyclus::ResourceBuff::capacity () const [inline]
capacity returns the maximum resource quantity this store can hold (units based on constituent resource objects' units).
Never throws.
Definition at line 60 of file resource_buff.h.
References capacity_.
int cyclus::ResourceBuff::count () const [inline]
count returns the total number of constituent resource objects in the store.
Never throws.
Definition at line 73 of file resource_buff.h.
References mats_.
Referenced by PopQty().
bool cyclus::ResourceBuff::empty () const [inline]
returns true if there are no mats in mats_
Definition at line 92 of file resource_buff.h.
References mats_.
Resource::Ptr cyclus::ResourceBuff::Pop (AccessDir dir = FRONT)
Pop pops one resource object from the store.
Resources are not split. Resources are retrieved by default in the order they were pushed (i.e. oldest first).
Parameters:
dir the access direction, which is the front by default
Exceptions:
ValueError the store is empty.
Definition at line 65 of file resource_buff.cc.
References FRONT, mats_, mats_present_, and qty_.
template<class T > T::Ptr cyclus::ResourceBuff::Pop () [inline]
A convenience method identical to Pop for auto-casting to specific Resource types.
Definition at line 130 of file resource_buff.h.
Manifest cyclus::ResourceBuff::PopN (int num)
PopN pops the specified number or count of resource objects from the store.
Resources are not split. Resources are retrieved in the order they were pushed (i.e. oldest first).
Exceptions:
ValueError the specified pop number is larger than the store's current inventoryNum or the specified number is negative.
Definition at line 47 of file resource_buff.cc.
References mats_, mats_present_, and qty_.
Manifest cyclus::ResourceBuff::PopQty (double qty)
PopQty pops the specified quantity of resources from the store.
Resources are split if necessary in order to pop the exact quantity specified (within cyclus::eps_rsrc()). Resources are retrieved in the order they were pushed (i.e. oldest first).
Exceptions:
ValueError the specified pop quantity is larger (by cyclus::eps_rsrc()) than the store's current quantity.
Definition at line 15 of file resource_buff.cc.
References count(), mats_, mats_present_, qty_, and quantity().
void cyclus::ResourceBuff::Push (Resource::Ptr r)
Push pushs a single resource object to the store.
Resource objects are never combined in the store; they are stored as unique objects. The resource object is only pushed to the store if it does not cause the store to exceed its capacity
Exceptions:
ValueError the pushing of the given resource object would cause the store to exceed its capacity.
KeyError the resource object to be pushed is already present in the store.
Definition at line 85 of file resource_buff.cc.
References cyclus::eps_rsrc(), mats_, mats_present_, qty_, and space().
template<class B > void cyclus::ResourceBuff::PushAll (std::vector< B > rs) [inline]
PushAll pushess one or more resource objects (as a std::vector) to the store.
Resource objects are never combined in the store; they are stored as unique objects. The resource objects are only pushed to the store if they do not cause the store to exceed its capacity; otherwise none of the given resource objects are pushed to the store.
Exceptions:
ValueError the pushing of the given resource objects would cause the store to exceed its capacity.
KeyError one or more of the resource objects to be pushed are already present in the store.
Definition at line 160 of file resource_buff.h.
References cyclus::eps_rsrc(), mats_, mats_present_, qty_, and space().
double cyclus::ResourceBuff::quantity () const [inline]
quantity returns the total resource quantity of constituent resource objects in the store.
Never throws.
Definition at line 79 of file resource_buff.h.
References qty_.
Referenced by PopQty(), and set_capacity().
void cyclus::ResourceBuff::set_capacity (double cap)
set_capacity sets the maximum quantity this store can hold (units based on constituent resource objects' units).
Exceptions:
ValueError the new capacity is lower (by cyclus::eps_rsrc()) than the quantity of resources that already exist in the store.
Definition at line 7 of file resource_buff.cc.
References capacity_, cyclus::eps_rsrc(), and quantity().
double cyclus::ResourceBuff::space () const [inline]
space returns the quantity of space remaining in this store.
It is effectively the difference between the capacity and the quantity. Never throws.
Definition at line 87 of file resource_buff.h.
References capacity_, and qty_.
Referenced by Push(), and PushAll().
Member Data Documentation
double cyclus::ResourceBuff::capacity_ [private]
maximum quantity of resources this store can hold
Definition at line 186 of file resource_buff.h.
Referenced by capacity(), set_capacity(), and space().
std::list<Resource::Ptr> cyclus::ResourceBuff::mats_ [private]
list of constituent resource objects forming the store's inventory
Definition at line 189 of file resource_buff.h.
Referenced by count(), empty(), Pop(), PopN(), PopQty(), Push(), and PushAll().
std::set<Resource::Ptr> cyclus::ResourceBuff::mats_present_ [private]
Definition at line 190 of file resource_buff.h.
Referenced by Pop(), PopN(), PopQty(), Push(), and PushAll().
double cyclus::ResourceBuff::qty_ [private]
Definition at line 180 of file resource_buff.h.
Referenced by Pop(), PopN(), PopQty(), Push(), PushAll(), quantity(), and space().
The documentation for this class was generated from the following files:
resource_buff.h
resource_buff.cc