CYCLUS: cyclus::ExchangeTranslator< T > Class Template Reference
cyclus::ExchangeTranslator< T > Class Template Reference
An ExchangeTranslator facilitates translation from a resource specific exchange to a resource-neutral exchange, upon which generic solvers can be applied.
#include <exchange_translator.h>
Public Member Functions
void BackTranslateSolution (const std::vector< Match > &matches, std::vector< Trade< T > > &ret)
Provide a vector of Trades given a vector of Matches.
ExchangeTranslator (ExchangeContext< T > *ex_ctx)
default constructor
ExchangeGraph::Ptr Translate ()
translate the ExchangeContext into an ExchangeGraph
const
ExchangeTranslationContext< T > & translation_ctx () const
ExchangeTranslationContext< T > & translation_ctx ()
Private Attributes
ExchangeContext< T > * ex_ctx_
ExchangeTranslationContext< T > xlation_ctx_
Detailed Description
template<class T>
class cyclus::ExchangeTranslator< T >
An ExchangeTranslator facilitates translation from a resource specific exchange to a resource-neutral exchange, upon which generic solvers can be applied.
Specifically, the ExchangeTranslator constructor takes a resource-specific exchange context and provides a Translate() method to make a resource-neutral ExchangeGraph. State is maintained in the ExchangeTranslator class, mapping Requests and Bids to ExchangeNodes in the ExchangeGraph. Accordingly, the solution to the ExchangeGraph, i.e., it's Matches, can be back-translated to the original Requests and Bids via a BackTranslateSolution() method.
Definition at line 30 of file exchange_translator.h.
Constructor & Destructor Documentation
template<class T > cyclus::ExchangeTranslator< T >::ExchangeTranslator (ExchangeContext< T > * ex_ctx) [inline]
default constructor
Parameters:
ex_ctx the exchance context
Definition at line 35 of file exchange_translator.h.
References cyclus::ExchangeTranslator< T >::ex_ctx_.
Member Function Documentation
template<class T > void cyclus::ExchangeTranslator< T >::BackTranslateSolution (const std::vector< Match > & matches, std::vector< Trade< T > > & ret) [inline]
Provide a vector of Trades given a vector of Matches.
Definition at line 95 of file exchange_translator.h.
References cyclus::BackTranslateMatch(), CLOG, cyclus::LEV_DEBUG1, and cyclus::ExchangeTranslator< T >::xlation_ctx_.
template<class T > ExchangeGraph::Ptr cyclus::ExchangeTranslator< T >::Translate () [inline]
translate the ExchangeContext into an ExchangeGraph
Definition at line 40 of file exchange_translator.h.
References CLOG, cyclus::ExchangeTranslator< T >::ex_ctx_, cyclus::Arc::first, cyclus::LEV_DEBUG5, cyclus::Bid< T >::request(), cyclus::Request< T >::requester(), cyclus::TranslateArc(), cyclus::TranslateBidPortfolio(), cyclus::TranslateRequestPortfolio(), and cyclus::ExchangeTranslator< T >::xlation_ctx_.
template<class T > const ExchangeTranslationContext<T>& cyclus::ExchangeTranslator< T >::translation_ctx () const [inline]
Definition at line 105 of file exchange_translator.h.
References cyclus::ExchangeTranslator< T >::xlation_ctx_.
template<class T > ExchangeTranslationContext<T>& cyclus::ExchangeTranslator< T >::translation_ctx () [inline]
Definition at line 109 of file exchange_translator.h.
References cyclus::ExchangeTranslator< T >::xlation_ctx_.
Member Data Documentation
template<class T > ExchangeContext<T>* cyclus::ExchangeTranslator< T >::ex_ctx_ [private]
Definition at line 112 of file exchange_translator.h.
Referenced by cyclus::ExchangeTranslator< T >::ExchangeTranslator(), and cyclus::ExchangeTranslator< T >::Translate().
template<class T > ExchangeTranslationContext<T> cyclus::ExchangeTranslator< T >::xlation_ctx_ [private]
Definition at line 113 of file exchange_translator.h.
Referenced by cyclus::ExchangeTranslator< T >::BackTranslateSolution(), cyclus::ExchangeTranslator< T >::Translate(), and cyclus::ExchangeTranslator< T >::translation_ctx().
The documentation for this class was generated from the following file:
exchange_translator.h