CYCLUS: cyclus::enrichment::Assays Class Reference
cyclus::enrichment::Assays Class Reference
a simple container class for enrichment assays
#include <enrichment.h>
Public Member Functions
Assays (double feed, double product, double tails)
constructor
double Feed () const
double Product () const
double Tails () const
Private Attributes
double feed_
double product_
double tails_
Detailed Description
a simple container class for enrichment assays
Definition at line 13 of file enrichment.h.
Constructor & Destructor Documentation
cyclus::enrichment::Assays::Assays (double feed, double product, double tails)
constructor
Definition at line 14 of file enrichment.cc.
Member Function Documentation
double cyclus::enrichment::Assays::Feed () const
Returns:
the feed assay as an atomic fraction, i.e. for 0.711% U-235 in natural uranium, this will return 0.00711.
Definition at line 20 of file enrichment.cc.
Referenced by cyclus::enrichment::FeedQty(), cyclus::enrichment::SwuRequired(), and cyclus::enrichment::TailsQty().
double cyclus::enrichment::Assays::Product () const
Returns:
the product assay as an atomic fraction, i.e. for 3% U-235 in enriched uranium, this will return 0.03.
Definition at line 25 of file enrichment.cc.
Referenced by cyclus::enrichment::FeedQty(), cyclus::enrichment::SwuRequired(), and cyclus::enrichment::TailsQty().
double cyclus::enrichment::Assays::Tails () const
Returns:
the tails assay as an atomic fraction, i.e. for 0.2% U-235 in depleted uranium, this will return 0.002.
Definition at line 30 of file enrichment.cc.
Referenced by cyclus::enrichment::FeedQty(), cyclus::enrichment::SwuRequired(), and cyclus::enrichment::TailsQty().
Member Data Documentation
double cyclus::enrichment::Assays::feed_ [private]
Definition at line 31 of file enrichment.h.
double cyclus::enrichment::Assays::product_ [private]
Definition at line 31 of file enrichment.h.
double cyclus::enrichment::Assays::tails_ [private]
Definition at line 31 of file enrichment.h.
The documentation for this class was generated from the following files:
enrichment.h
enrichment.cc