CYCLUS: cyclus::Datum Class Reference
cyclus::Datum Class Reference
#include <datum.h>
Public Types
typedef std::pair< const char
*, boost::spirit::hold_any > Entry
typedef std::vector< Entry > Vals
Public Member Functions
Datum * AddVal (const char *field, boost::spirit::hold_any val)
void Record ()
std::string title ()
Returns the datum's title as specified during the datum's creation.
const Vals & vals ()
Returns a map of all field-value pairs that have been added to this datum.
virtual ~Datum ()
Static Public Member Functions
static void operator delete (void *rawMemory) throw ()
static void * operator new (size_t size)
Private Member Functions
Datum (Recorder *m, std::string title)
Datum objects should generally not be created using a constructor (i.e.
Private Attributes
Recorder * manager_
std::string title_
Vals vals_
Friends
class Recorder
Detailed Description
Used to specify and send a collection of key-value pairs to the Recorder for recording.
Definition at line 17 of file datum.h.
Member Typedef Documentation
typedef std::pair<const char*, boost::spirit::hold_any> cyclus::Datum::Entry
Definition at line 21 of file datum.h.
typedef std::vector<Entry> cyclus::Datum::Vals
Definition at line 22 of file datum.h.
Constructor & Destructor Documentation
cyclus::Datum::~Datum () [virtual]
Definition at line 32 of file datum.cc.
cyclus::Datum::Datum (Recorder * m, std::string title) [private]
Datum objects should generally not be created using a constructor (i.e.
use the recorder interface).
Definition at line 24 of file datum.cc.
References vals_.
Member Function Documentation
Datum * cyclus::Datum::AddVal (const char * field, boost::spirit::hold_any val)
Add an arbitrary field-value pair to the datum.
Parameters:
field a label or key for a value. Loosely analogous to a column label.
val a value of any type (int, bool, string, vector) supported by the backends being used.
Warning:
for the val argument - what variable types are supported depends on what the backend(s) in use are designed to handle.
Definition at line 13 of file datum.cc.
References vals_.
Referenced by cyclus::Context::AddPrototype(), cyclus::Context::AddRecipe(), cyclus::Agent::AddToTable(), cyclus::Product::Create(), cyclus::ResTracker::Create(), cyclus::Agent::Decommission(), cyclus::CommodityRecipeContext::InfileToDb(), cyclus::Agent::InfileToDb(), cyclus::Context::InitSim(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadSolver(), cyclus::DbInit::NewDatum(), cyclus::ResTracker::Record(), cyclus::Composition::Record(), cyclus::Material::Record(), cyclus::TradeExecutor< T >::RecordTrades(), cyclus::Context::SchedBuild(), cyclus::Context::SchedDecom(), cyclus::Recorder::set_dump_count(), cyclus::SimInit::SnapAgent(), cyclus::SimInit::Snapshot(), cyclus::CommodityRecipeContext::Snapshot(), cyclus::Agent::Snapshot(), and cyclus::XMLFileLoader::XMLFileLoader().
void cyclus::Datum::operator delete (void * rawMemory) throw () [static]
Definition at line 68 of file datum.cc.
void * cyclus::Datum::operator new (size_t size) [static]
Definition at line 45 of file datum.cc.
void cyclus::Datum::Record ()
Record this datum to its Recorder. Recorded Datum objects of the same title (e.g. same table) must not contain any fields that were not present in the first datum recorded of that title.
Definition at line 19 of file datum.cc.
References cyclus::Recorder::AddDatum(), and manager_.
Referenced by cyclus::Agent::AddToTable(), cyclus::Product::Create(), cyclus::Agent::InfileToDb(), cyclus::Context::InitSim(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadSolver(), cyclus::ResTracker::Record(), cyclus::Composition::Record(), cyclus::Material::Record(), cyclus::Context::SchedBuild(), cyclus::Context::SchedDecom(), cyclus::SimInit::SnapAgent(), cyclus::SimInit::Snapshot(), cyclus::CommodityRecipeContext::Snapshot(), cyclus::Agent::Snapshot(), and cyclus::XMLFileLoader::XMLFileLoader().
std::string cyclus::Datum::title ()
Returns the datum's title as specified during the datum's creation.
Definition at line 35 of file datum.cc.
References title_.
Referenced by cyclus::Hdf5Back::CreateTable(), cyclus::SqliteBack::CreateTable(), cyclus::CsvBack::WriteDatum(), and cyclus::SqliteBack::WriteDatum().
const Datum::Vals & cyclus::Datum::vals ()
Returns a map of all field-value pairs that have been added to this datum.
Definition at line 40 of file datum.cc.
References vals_.
Referenced by cyclus::Hdf5Back::CreateTable(), cyclus::SqliteBack::CreateTable(), cyclus::CsvBack::WriteDatum(), and cyclus::SqliteBack::WriteDatum().
Friends And Related Function Documentation
friend class Recorder [friend]
Definition at line 18 of file datum.h.
Member Data Documentation
Recorder* cyclus::Datum::manager_ [private]
Definition at line 61 of file datum.h.
Referenced by Record().
std::string cyclus::Datum::title_ [private]
Definition at line 62 of file datum.h.
Referenced by cyclus::Recorder::NewDatum(), and title().
Vals cyclus::Datum::vals_ [private]
Definition at line 63 of file datum.h.
Referenced by AddVal(), Datum(), cyclus::Recorder::NewDatum(), and vals().
The documentation for this class was generated from the following files:
datum.h
datum.cc