CYCLUS: cyclus::Recorder Class Reference
cyclus::Recorder Class Reference
Collects and manages output data generation for the cyclus core and agents during a simulation.
#include <recorder.h>
Public Member Functions
void Close ()
Flushes all buffered Datum objects and flushes all registered backends.
unsigned int dump_count ()
Return the dump frequency, # Datum objects buffered between flushes to backends.
void Flush ()
Flushes all buffered Datum objects and flushes all registered backends.
Datum * NewDatum (std::string title)
Creates a new datum namespaced under the specified title.
Recorder ()
create a new recorder with default dump frequency and random simulation id.
Recorder (boost::uuids::uuid simid)
create a new recorder with default dump frequency and the specified simulation id.
void RegisterBackend (RecBackend *b)
Registers b to receive Datum notifications for all Datum objects collected by the Recorder and to receive a flush notification when there are no more Datum objects.
void set_dump_count (unsigned int count)
set the Recorder to flush its collected Datum objects to registered backends every [count] Datum objects.
boost::uuids::uuid sim_id ()
returns the unique id associated with this cyclus simulation.
~Recorder ()
Private Member Functions
void AddDatum (Datum *d)
void NotifyBackends ()
Private Attributes
std::list< RecBackend * > backs_
DatumList data_
unsigned int dump_count_
int index_
boost::uuids::uuid uuid_
Friends
class Datum
Detailed Description
Collects and manages output data generation for the cyclus core and agents during a simulation.
By default, datum managers are auto-initialized with a unique uuid simulation id.
Example usage:
 Recorder* manager = new Recorder();
 CustomBackend* myback = new CustomBackend();
 manager->RegisterBackend(myback);
 ...
 ...
 manager->NewDatum("CapacityFactor");
        ->AddVal("Name", aname)
        ->AddVal("Capacity", cap)
        ->Record();
 ...
 ...
 manager->Close();
Definition at line 45 of file recorder.h.
Constructor & Destructor Documentation
cyclus::Recorder::Recorder ()
create a new recorder with default dump frequency and random simulation id.
Definition at line 15 of file recorder.cc.
References cyclus::kDefaultDumpCount, set_dump_count(), and uuid_.
cyclus::Recorder::Recorder (boost::uuids::uuid simid)
create a new recorder with default dump frequency and the specified simulation id.
Definition at line 20 of file recorder.cc.
References cyclus::kDefaultDumpCount, and set_dump_count().
cyclus::Recorder::~Recorder ()
Definition at line 25 of file recorder.cc.
References data_, and Flush().
Member Function Documentation
void cyclus::Recorder::AddDatum (Datum * d) [private]
Definition at line 66 of file recorder.cc.
Referenced by cyclus::Datum::Record().
void cyclus::Recorder::Close ()
Flushes all buffered Datum objects and flushes all registered backends.
Unregisters all backends and resets.
Definition at line 91 of file recorder.cc.
References backs_, and Flush().
unsigned int cyclus::Recorder::dump_count ()
Return the dump frequency, # Datum objects buffered between flushes to backends.
Definition at line 32 of file recorder.cc.
References dump_count_.
void cyclus::Recorder::Flush ()
Flushes all buffered Datum objects and flushes all registered backends.
Definition at line 68 of file recorder.cc.
References backs_, data_, and index_.
Referenced by Close(), cyclus::SimInit::InitBase(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadSim(), ~Recorder(), and cyclus::XMLFileLoader::~XMLFileLoader().
Datum * cyclus::Recorder::NewDatum (std::string title)
Creates a new datum namespaced under the specified title.
Warning:
choose title carefully to not conflict with Datum objects from other agents. Also note that a static title (e.g. an unchanging string) will result in multiple instances of this agent storing datum data together (e.g. the same table).
Definition at line 54 of file recorder.cc.
References data_, index_, NotifyBackends(), cyclus::Datum::title_, and cyclus::Datum::vals_.
Referenced by cyclus::Context::NewDatum().
void cyclus::Recorder::NotifyBackends () [private]
Definition at line 79 of file recorder.cc.
References backs_, data_, and index_.
Referenced by NewDatum().
void cyclus::Recorder::RegisterBackend (RecBackend * b)
Registers b to receive Datum notifications for all Datum objects collected by the Recorder and to receive a flush notification when there are no more Datum objects.
Parameters:
b backend to receive Datum objects
Definition at line 87 of file recorder.cc.
References backs_.
void cyclus::Recorder::set_dump_count (unsigned int count)
set the Recorder to flush its collected Datum objects to registered backends every [count] Datum objects.
If count == 0 then Datum objects will be flushed immediately as they come.
Parameters:
count # Datum objects to buffer before flushing to backends.
Warning:
this deletes all buffered data from the recorder.
Definition at line 40 of file recorder.cc.
References cyclus::Datum::AddVal(), data_, Datum, dump_count_, and uuid_.
Referenced by cyclus::SimInit::InitBase(), and Recorder().
boost::uuids::uuid cyclus::Recorder::sim_id ()
returns the unique id associated with this cyclus simulation.
Definition at line 36 of file recorder.cc.
References uuid_.
Referenced by cyclus::SimInit::Init(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadInitialAgents(), and cyclus::Context::sim_id().
Friends And Related Function Documentation
friend class Datum [friend]
Definition at line 46 of file recorder.h.
Referenced by set_dump_count().
Member Data Documentation
std::list<RecBackend*> cyclus::Recorder::backs_ [private]
Definition at line 102 of file recorder.h.
Referenced by Close(), Flush(), NotifyBackends(), and RegisterBackend().
DatumList cyclus::Recorder::data_ [private]
Definition at line 100 of file recorder.h.
Referenced by Flush(), NewDatum(), NotifyBackends(), set_dump_count(), and ~Recorder().
unsigned int cyclus::Recorder::dump_count_ [private]
Definition at line 103 of file recorder.h.
Referenced by dump_count(), and set_dump_count().
int cyclus::Recorder::index_ [private]
Definition at line 101 of file recorder.h.
Referenced by Flush(), NewDatum(), and NotifyBackends().
boost::uuids::uuid cyclus::Recorder::uuid_ [private]
Definition at line 104 of file recorder.h.
Referenced by Recorder(), set_dump_count(), and sim_id().
The documentation for this class was generated from the following files:
recorder.h
recorder.cc