CYCLUS: cyclus::CommodityRecipeContext Class Reference
cyclus::CommodityRecipeContext Class Reference
a CommodityRecipeContext contains relationships between commodities, recipes and resources
#include <commodity_recipe_context.h>
Public Member Functions
void AddInCommod (std::string in_commod, std::string in_recipe, std::string out_commod, std::string out_recipe)
add an input commodity and its relations
void AddRsrc (std::string commod, Resource::Ptr rsrc)
add a resource and its commodity affiliation
virtual CommodityRecipeContext * Clone ()
Return a newly created/allocated object that is an exact copy of this.
std::string commod (Resource::Ptr rsrc)
const std::vector< std::string > & in_commods () const
std::string in_recipe (std::string in_commod)
virtual void InfileToDb (InfileTree *qe, DbInit di)
Translates info for the object from input file information to the database by reading parameters from the passed InfileTree and recording data via the DbInit variable.
virtual void InitFrom (QueryableBackend *b)
Intializes an agent's internal state from an output database.
bool operator!= (const CommodityRecipeContext &other) const
bool operator== (const CommodityRecipeContext &other) const
std::string out_commod (std::string in_commod)
const std::vector< std::string > & out_commods () const
std::string out_recipe (std::string in_recipe)
void RemoveRsrc (Resource::Ptr rsrc)
removes a resource from the context
virtual std::string schema ()
Returns an object's xml rng schema for initializing from input files.
virtual void Snapshot (DbInit di)
Snapshots agent-internal state to the output db via di.
void UpdateInRec (std::string in_commod, std::string recipe)
update an input recipe and its commodity affiliation
void UpdateRsrc (std::string commod, Resource::Ptr rsrc)
update a resource and its commodity affiliation
Private Attributes
std::vector< std::string > in_commods_
std::map< std::string,
std::string > in_recipes_
std::map< std::string,
std::string > out_commod_map_
std::vector< std::string > out_commods_
std::map< std::string,
std::string > out_recipes_
std::map< int, std::string > rsrc_commod_map_
Detailed Description
a CommodityRecipeContext contains relationships between commodities, recipes and resources
Definition at line 18 of file commodity_recipe_context.h.
Member Function Documentation
void cyclus::CommodityRecipeContext::AddInCommod (std::string in_commod, std::string in_recipe, std::string out_commod, std::string out_recipe)
add an input commodity and its relations
Definition at line 8 of file commodity_recipe_context.cc.
References in_commods_, in_recipes_, out_commod_map_, out_commods_, and out_recipes_.
Referenced by InitFrom().
void cyclus::CommodityRecipeContext::AddRsrc (std::string commod, Resource::Ptr rsrc)
add a resource and its commodity affiliation
Definition at line 20 of file commodity_recipe_context.cc.
References commod(), and rsrc_commod_map_.
CommodityRecipeContext * cyclus::CommodityRecipeContext::Clone () [virtual]
Return a newly created/allocated object that is an exact copy of this.
Subclasses are expected to override the return type with their own concrete type.
Implements cyclus::StateWrangler.
Definition at line 41 of file commodity_recipe_context.cc.
std::string cyclus::CommodityRecipeContext::commod (Resource::Ptr rsrc) [inline]
Returns:
commodity of a material
Warning:
returns a blank string if material isn't found
Definition at line 65 of file commodity_recipe_context.h.
References rsrc_commod_map_.
Referenced by AddRsrc(), InitFrom(), and UpdateRsrc().
const std::vector<std::string>& cyclus::CommodityRecipeContext::in_commods () const [inline]
Returns:
input commodities
Definition at line 39 of file commodity_recipe_context.h.
References in_commods_.
std::string cyclus::CommodityRecipeContext::in_recipe (std::string in_commod) [inline]
Returns:
input recipe of an input commodity
Definition at line 54 of file commodity_recipe_context.h.
References in_recipes_.
Referenced by out_recipe().
void cyclus::CommodityRecipeContext::InfileToDb (InfileTree * qe, DbInit di) [virtual]
Translates info for the object from input file information to the database by reading parameters from the passed InfileTree and recording data via the DbInit variable.
The simulation and agent id's are automatically injected in all data transfered through di.
Agent parameters in the InfileTree are scoped in the "agent/[agent-class-name]" path. The agent's class-name can be retrieved from the agent_impl method. The superclass InitFrom expects the InfileTree passed to it to be scoped identically - do NOT pass a changed-scope InfileTree to the superclass.
Warning:
this method MUST NOT modify the object's state.
Implements cyclus::StateWrangler.
Definition at line 45 of file commodity_recipe_context.cc.
References cyclus::Datum::AddVal(), cyclus::InfileTree::GetString(), cyclus::DbInit::NewDatum(), cyclus::InfileTree::NMatches(), and cyclus::InfileTree::Query().
void cyclus::CommodityRecipeContext::InitFrom (QueryableBackend * b) [virtual]
Intializes an agent's internal state from an output database.
Appropriate simulation id, agent id, and time filters are automatically included in all queries.
Implements cyclus::StateWrangler.
Definition at line 58 of file commodity_recipe_context.cc.
References AddInCommod(), commod(), cyclus::QueryResult::GetVal(), cyclus::QueryableBackend::Query(), cyclus::QueryResult::rows, and rsrc_commod_map_.
bool cyclus::CommodityRecipeContext::operator!= (const CommodityRecipeContext & other) const [inline]
Definition at line 78 of file commodity_recipe_context.h.
References operator==().
bool cyclus::CommodityRecipeContext::operator== (const CommodityRecipeContext & other) const [inline]
Definition at line 69 of file commodity_recipe_context.h.
References in_commods_, in_recipes_, cyclus::map_compare(), out_commod_map_, out_commods_, out_recipes_, and rsrc_commod_map_.
Referenced by operator!=().
std::string cyclus::CommodityRecipeContext::out_commod (std::string in_commod) [inline]
Returns:
output commodity of an input commodity
Definition at line 49 of file commodity_recipe_context.h.
References out_commod_map_.
const std::vector<std::string>& cyclus::CommodityRecipeContext::out_commods () const [inline]
Returns:
output commodities
Definition at line 44 of file commodity_recipe_context.h.
References out_commods_.
std::string cyclus::CommodityRecipeContext::out_recipe (std::string in_recipe) [inline]
Returns:
output recipe of an input recipe
Definition at line 59 of file commodity_recipe_context.h.
References in_recipe(), and out_recipes_.
void cyclus::CommodityRecipeContext::RemoveRsrc (Resource::Ptr rsrc)
removes a resource from the context
Definition at line 25 of file commodity_recipe_context.cc.
References rsrc_commod_map_.
std::string cyclus::CommodityRecipeContext::schema () [virtual]
Returns an object's xml rng schema for initializing from input files.
Implements cyclus::StateWrangler.
Definition at line 97 of file commodity_recipe_context.cc.
void cyclus::CommodityRecipeContext::Snapshot (DbInit di) [virtual]
Snapshots agent-internal state to the output db via di.
This method MUST call the superclass' Snapshot method before doing any work. The simulation and agent id's in addition to the snapshot time are automatically included in all information transfered through di.
Warning:
because a 'Time' field is automatically injected, that label cannot be used for any other fields.
This method MUST NOT modify the agent's state.
Implements cyclus::StateWrangler.
Definition at line 77 of file commodity_recipe_context.cc.
References cyclus::Datum::AddVal(), in_commods_, in_recipes_, cyclus::DbInit::NewDatum(), out_commod_map_, out_recipes_, cyclus::Datum::Record(), and rsrc_commod_map_.
void cyclus::CommodityRecipeContext::UpdateInRec (std::string in_commod, std::string recipe)
update an input recipe and its commodity affiliation
Definition at line 35 of file commodity_recipe_context.cc.
References in_recipes_, and out_recipes_.
void cyclus::CommodityRecipeContext::UpdateRsrc (std::string commod, Resource::Ptr rsrc)
update a resource and its commodity affiliation
Definition at line 30 of file commodity_recipe_context.cc.
References commod(), and rsrc_commod_map_.
Member Data Documentation
std::vector<std::string> cyclus::CommodityRecipeContext::in_commods_ [private]
Definition at line 89 of file commodity_recipe_context.h.
Referenced by AddInCommod(), in_commods(), operator==(), and Snapshot().
std::map<std::string, std::string> cyclus::CommodityRecipeContext::in_recipes_ [private]
Definition at line 92 of file commodity_recipe_context.h.
Referenced by AddInCommod(), in_recipe(), operator==(), Snapshot(), and UpdateInRec().
std::map<std::string, std::string> cyclus::CommodityRecipeContext::out_commod_map_ [private]
Definition at line 91 of file commodity_recipe_context.h.
Referenced by AddInCommod(), operator==(), out_commod(), and Snapshot().
std::vector<std::string> cyclus::CommodityRecipeContext::out_commods_ [private]
Definition at line 90 of file commodity_recipe_context.h.
Referenced by AddInCommod(), operator==(), and out_commods().
std::map<std::string, std::string> cyclus::CommodityRecipeContext::out_recipes_ [private]
Definition at line 93 of file commodity_recipe_context.h.
Referenced by AddInCommod(), operator==(), out_recipe(), Snapshot(), and UpdateInRec().
std::map<int, std::string> cyclus::CommodityRecipeContext::rsrc_commod_map_ [private]
Definition at line 94 of file commodity_recipe_context.h.
Referenced by AddRsrc(), commod(), InitFrom(), operator==(), RemoveRsrc(), Snapshot(), and UpdateRsrc().
The documentation for this class was generated from the following files:
commodity_recipe_context.h
commodity_recipe_context.cc