CYCLUS: cyclus::MatQuery Class Reference
cyclus::MatQuery Class Reference
A class that provides convenience methods for querying a material's properties.
#include <mat_query.h>
Public Member Functions
bool AlmostEq (Material::Ptr other, double threshold=eps_rsrc())
Returns true if all nuclide fractions of the material and other are the same within threshold.
double atom_frac (Nuc nuc)
returns the atom/mole fraction of nuclide nuc in the material.
double mass (Nuc nuc)
Returns the mass in kg of nuclide nuc in the material.
double mass_frac (Nuc nuc)
Returns the mass fraction of nuclide nuc in the material.
MatQuery (Material::Ptr m)
Creates a new query object inspecting m.
double moles (Nuc nuc)
Returns the number of moles of nuclide nuc in the material.
double qty ()
Returns the mass in kg of the material.
Private Attributes
Material::Ptr m_
Detailed Description
A class that provides convenience methods for querying a material's properties.
Definition at line 12 of file mat_query.h.
Constructor & Destructor Documentation
cyclus::MatQuery::MatQuery (Material::Ptr m)
Creates a new query object inspecting m.
Definition at line 7 of file mat_query.cc.
Member Function Documentation
bool cyclus::MatQuery::AlmostEq (Material::Ptr other, double threshold = eps_rsrc())
Returns true if all nuclide fractions of the material and other are the same within threshold.
Definition at line 33 of file mat_query.cc.
References m_, and cyclus::compmath::Normalize().
double cyclus::MatQuery::atom_frac (Nuc nuc)
returns the atom/mole fraction of nuclide nuc in the material.
Definition at line 27 of file mat_query.cc.
References m_, and cyclus::compmath::Normalize().
Referenced by cyclus::enrichment::UraniumAssay().
double cyclus::MatQuery::mass (Nuc nuc)
Returns the mass in kg of nuclide nuc in the material.
Definition at line 13 of file mat_query.cc.
References mass_frac(), and qty().
Referenced by moles(), and cyclus::enrichment::UraniumQty().
double cyclus::MatQuery::mass_frac (Nuc nuc)
Returns the mass fraction of nuclide nuc in the material.
Definition at line 21 of file mat_query.cc.
References m_, and cyclus::compmath::Normalize().
Referenced by mass().
double cyclus::MatQuery::moles (Nuc nuc)
Returns the number of moles of nuclide nuc in the material.
Definition at line 17 of file mat_query.cc.
References cyclus::units::g, and mass().
double cyclus::MatQuery::qty ()
Returns the mass in kg of the material.
Definition at line 9 of file mat_query.cc.
References m_.
Referenced by mass().
Member Data Documentation
Material::Ptr cyclus::MatQuery::m_ [private]
Definition at line 37 of file mat_query.h.
Referenced by AlmostEq(), atom_frac(), mass_frac(), and qty().
The documentation for this class was generated from the following files:
mat_query.h
mat_query.cc