CYCLUS: cyclus::Context Class Reference
cyclus::Context Class Reference
A simulation context provides access to necessary simulation-global functions and state.
#include <context.h>
Public Member Functions
void AddPrototype (std::string name, Agent *m)
Adds a prototype to a simulation-wide accessible list.
void AddRecipe (std::string name, Composition::Ptr c)
Adds a composition recipe to a simulation-wide accessible list.
Context (Timer *ti, Recorder *rec)
Creates a new context working with the specified timer and datum manager.
template<class T >
T * CreateAgent (std::string proto_name)
Create a new agent by cloning the named prototype.
void DelAgent (Agent *m)
Destructs and cleans up m (and it's children recursively).
Composition::Ptr GetRecipe (std::string name)
Retrieve a registered recipe.
void InitSim (SimInfo si)
Initializes the simulation time parameters.
Datum * NewDatum (std::string title)
See Recorder::NewDatum documentation.
int NextTransactionID ()
void RegisterTimeListener (TimeListener *tl)
Registers an agent to receive tick/tock notifications every timestep.
void RegisterTrader (Trader *e)
Registers an agent as a participant in resource exchanges.
void SchedBuild (Agent *parent, std::string proto_name, int t=-1)
Schedules the named prototype to be built for the specified parent at timestep t.
void SchedDecom (Agent *m, int time=-1)
Schedules the given Agent to be decommissioned at the specified timestep t.
boost::uuids::uuid sim_id ()
See Recorder::sim_id documentation.
SimInfo sim_info () const
Return static simulation info.
void Snapshot ()
Makes a snapshot of the simulation state to the output database.
ExchangeSolver * solver ()
Returns the exchange solver associated with this context.
void solver (ExchangeSolver *solver)
sets the solver associated with this context
int time ()
Returns the current simulation timestep.
const std::set< Trader * > & traders () const
void UnregisterTimeListener (TimeListener *tl)
Removes an agent from receiving tick/tock notifications.
void UnregisterTrader (Trader *e)
Unregisters an agent as a participant in resource exchanges.
~Context ()
Clean up resources including destructing the solver and all agents the context is aware of.
Private Attributes
std::set< Agent * > agent_list_
std::map< std::string, Agent * > protos_
Recorder * rec_
std::map< std::string,
Composition::Ptr > recipes_
SimInfo si_
ExchangeSolver * solver_
Timer * ti_
std::set< Trader * > traders_
int trans_id_
Friends
class Agent
class SimInit
Detailed Description
A simulation context provides access to necessary simulation-global functions and state.
All code that writes to the output database, needs to know simulation time, creates/builds facilities, and/or uses loaded composition recipes will need a context pointer. In general, all global state should be accessed through a simulation context.
Warning:
the context takes ownership of and manages the lifetime/destruction of all agents constructed with it (including Cloned agents). Agents should generally NEVER be allocated on the stack.
the context takes ownership of the solver and will manage its destruction.
Definition at line 71 of file context.h.
Constructor & Destructor Documentation
cyclus::Context::Context (Timer * ti, Recorder * rec)
Creates a new context working with the specified timer and datum manager.
The timer does not have to be initialized (yet).
Definition at line 13 of file context.cc.
cyclus::Context::~Context ()
Clean up resources including destructing the solver and all agents the context is aware of.
Definition at line 20 of file context.cc.
References agent_list_, DelAgent(), and solver_.
Member Function Documentation
void cyclus::Context::AddPrototype (std::string name, Agent * m)
Adds a prototype to a simulation-wide accessible list.
Definition at line 75 of file context.cc.
References cyclus::Datum::AddVal(), cyclus::Agent::agent_impl(), cyclus::Agent::id(), NewDatum(), and protos_.
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadInitialAgents(), and cyclus::SimInit::LoadPrototypes().
void cyclus::Context::AddRecipe (std::string name, Composition::Ptr c)
Adds a composition recipe to a simulation-wide accessible list.
Agents should NOT add their own recipes.
Definition at line 84 of file context.cc.
References cyclus::Datum::AddVal(), NewDatum(), and recipes_.
Referenced by cyclus::XMLFileLoader::LoadRecipes(), and cyclus::SimInit::LoadRecipes().
template<class T > T* cyclus::Context::CreateAgent (std::string proto_name) [inline]
Create a new agent by cloning the named prototype.
The returned agent is not initialized as a simulation participant.
Warning:
this method should generally NOT be used by agents.
Definition at line 111 of file context.h.
References cyclus::Agent::Clone(), DelAgent(), and protos_.
Referenced by cyclus::XMLFileLoader::BuildAgent(), cyclus::Timer::DoBuild(), and cyclus::SimInit::LoadInitialAgents().
void cyclus::Context::DelAgent (Agent * m)
Destructs and cleans up m (and it's children recursively).
Warning:
this method should generally NOT be used by agents.
Definition at line 39 of file context.cc.
References agent_list_.
Referenced by cyclus::BuildFlatMasterSchema(), cyclus::BuildMasterSchema(), CreateAgent(), cyclus::Agent::Decommission(), cyclus::Agent::~Agent(), and ~Context().
Composition::Ptr cyclus::Context::GetRecipe (std::string name)
Retrieve a registered recipe.
This is intended for retrieving compositions loaded from an input file(s) at the start of a simulation and NOT for communicating compositions between facilities during the simulation.
Definition at line 92 of file context.cc.
References recipes_.
void cyclus::Context::InitSim (SimInfo si)
Initializes the simulation time parameters.
Should only be called once - NOT idempotent.
Definition at line 99 of file context.cc.
References cyclus::Datum::AddVal(), cyclus::SimInfo::branch_time, cyclus::SimInfo::decay_period, cyclus::SimInfo::duration, cyclus::SimInfo::handle, cyclus::Timer::Initialize(), cyclus::SimInfo::m0, NewDatum(), cyclus::SimInfo::parent_sim, cyclus::Datum::Record(), ti_, and cyclus::SimInfo::y0.
Referenced by cyclus::XMLFileLoader::LoadControlParams(), and cyclus::SimInit::LoadInfo().
Datum * cyclus::Context::NewDatum (std::string title)
See Recorder::NewDatum documentation.
Definition at line 124 of file context.cc.
References cyclus::Recorder::NewDatum(), and rec_.
Referenced by AddPrototype(), AddRecipe(), cyclus::Agent::AddToTable(), cyclus::Product::Create(), cyclus::ResTracker::Create(), cyclus::Agent::Decommission(), InitSim(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadSolver(), cyclus::DbInit::NewDatum(), cyclus::ResTracker::Record(), cyclus::Composition::Record(), cyclus::Material::Record(), cyclus::TradeExecutor< T >::RecordTrades(), SchedBuild(), SchedDecom(), cyclus::SimInit::SnapAgent(), cyclus::SimInit::Snapshot(), and cyclus::XMLFileLoader::XMLFileLoader().
int cyclus::Context::NextTransactionID () [inline]
Returns:
the next transaction id
Definition at line 177 of file context.h.
References trans_id_.
Referenced by cyclus::TradeExecutor< T >::RecordTrades().
void cyclus::Context::RegisterTimeListener (TimeListener * tl)
Registers an agent to receive tick/tock notifications every timestep.
Agents should register from their Deploy method.
Definition at line 116 of file context.cc.
References cyclus::Timer::RegisterTimeListener(), and ti_.
Referenced by cyclus::Institution::DoRegistration(), cyclus::Region::DoRegistration(), and cyclus::Facility::DoRegistration().
void cyclus::Context::RegisterTrader (Trader * e) [inline]
Registers an agent as a participant in resource exchanges.
Agents should register from their Deploy method.
Definition at line 92 of file context.h.
References traders_.
Referenced by cyclus::Facility::DoRegistration().
void cyclus::Context::SchedBuild (Agent * parent, std::string proto_name, int t = -1)
Schedules the named prototype to be built for the specified parent at timestep t.
The default t=-1 results in the build being scheduled for the next build phase (i.e. the start of the next timestep).
Definition at line 46 of file context.cc.
References cyclus::Datum::AddVal(), cyclus::Agent::id(), NewDatum(), cyclus::Datum::Record(), cyclus::Timer::SchedBuild(), ti_, and time().
Referenced by cyclus::SimInit::LoadBuildSched().
void cyclus::Context::SchedDecom (Agent * m, int time = -1)
Schedules the given Agent to be decommissioned at the specified timestep t.
The default t=-1 results in the decommission being scheduled for the next decommission phase (i.e. the end of the current timestep).
Definition at line 59 of file context.cc.
References cyclus::Datum::AddVal(), cyclus::Agent::id(), NewDatum(), cyclus::Datum::Record(), cyclus::Timer::SchedDecom(), ti_, and time().
Referenced by cyclus::SimInit::LoadDecomSched(), and cyclus::Institution::Tock().
boost::uuids::uuid cyclus::Context::sim_id ()
See Recorder::sim_id documentation.
Definition at line 71 of file context.cc.
References rec_, and cyclus::Recorder::sim_id().
SimInfo cyclus::Context::sim_info () const [inline]
Return static simulation info.
Definition at line 168 of file context.h.
References si_.
void cyclus::Context::Snapshot ()
Makes a snapshot of the simulation state to the output database.
Definition at line 128 of file context.cc.
References cyclus::Timer::Snapshot(), and ti_.
ExchangeSolver* cyclus::Context::solver () [inline]
Returns the exchange solver associated with this context.
Definition at line 182 of file context.h.
References solver_.
Referenced by cyclus::ExchangeManager< T >::Execute(), cyclus::SimInit::LoadSolverInfo(), and solver().
void cyclus::Context::solver (ExchangeSolver * solver) [inline]
sets the solver associated with this context
Definition at line 187 of file context.h.
References solver(), and solver_.
int cyclus::Context::time ()
Returns the current simulation timestep.
Definition at line 112 of file context.cc.
References ti_, and cyclus::Timer::time().
Referenced by cyclus::Agent::Build(), cyclus::Agent::Decommission(), cyclus::Agent::InformErrorMsg(), cyclus::Material::Material(), cyclus::DbInit::NewDatum(), cyclus::ResTracker::Record(), cyclus::Material::Record(), cyclus::TradeExecutor< T >::RecordTrades(), SchedBuild(), SchedDecom(), cyclus::SimInit::SnapAgent(), and cyclus::SimInit::Snapshot().
const std::set<Trader*>& cyclus::Context::traders () const [inline]
Returns:
the current set of traders registered for resource exchange.
Definition at line 102 of file context.h.
References traders_.
Referenced by cyclus::ResourceExchange< T >::AddAllBids(), and cyclus::ResourceExchange< T >::AddAllRequests().
void cyclus::Context::UnregisterTimeListener (TimeListener * tl)
Removes an agent from receiving tick/tock notifications.
Agents should unregister from their Decommission method.
Definition at line 120 of file context.cc.
References ti_, and cyclus::Timer::UnregisterTimeListener().
Referenced by cyclus::Institution::Decommission(), cyclus::Region::Decommission(), and cyclus::Facility::Decommission().
void cyclus::Context::UnregisterTrader (Trader * e) [inline]
Unregisters an agent as a participant in resource exchanges.
Definition at line 97 of file context.h.
References traders_.
Referenced by cyclus::Facility::Decommission().
Friends And Related Function Documentation
friend class Agent [friend]
Definition at line 74 of file context.h.
friend class SimInit [friend]
Definition at line 73 of file context.h.
Member Data Documentation
std::set<Agent*> cyclus::Context::agent_list_ [private]
Definition at line 194 of file context.h.
Referenced by cyclus::Agent::Agent(), DelAgent(), cyclus::SimInit::Snapshot(), cyclus::Agent::~Agent(), and ~Context().
std::map<std::string, Agent*> cyclus::Context::protos_ [private]
Definition at line 192 of file context.h.
Referenced by AddPrototype(), and CreateAgent().
Recorder* cyclus::Context::rec_ [private]
Definition at line 200 of file context.h.
Referenced by cyclus::SimInit::Init(), NewDatum(), and sim_id().
std::map<std::string, Composition::Ptr> cyclus::Context::recipes_ [private]
Definition at line 193 of file context.h.
Referenced by AddRecipe(), and GetRecipe().
SimInfo cyclus::Context::si_ [private]
Definition at line 197 of file context.h.
Referenced by sim_info().
ExchangeSolver* cyclus::Context::solver_ [private]
Definition at line 199 of file context.h.
Referenced by solver(), and ~Context().
Timer* cyclus::Context::ti_ [private]
Definition at line 198 of file context.h.
Referenced by InitSim(), RegisterTimeListener(), SchedBuild(), SchedDecom(), Snapshot(), time(), and UnregisterTimeListener().
std::set<Trader*> cyclus::Context::traders_ [private]
Definition at line 195 of file context.h.
Referenced by RegisterTrader(), traders(), and UnregisterTrader().
int cyclus::Context::trans_id_ [private]
Definition at line 201 of file context.h.
Referenced by cyclus::SimInit::LoadNextIds(), NextTransactionID(), and cyclus::SimInit::Snapshot().
The documentation for this class was generated from the following files:
context.h
context.cc