CYCLUS: cyclus::Institution Class Reference
cyclus::Institution Class Reference
The Institution class is the abstract class/interface used by all institution agents.
#include <institution.h>
Public Member Functions
virtual void Build (Agent *parent)
perform all tasks required when an inst enters the simulation
virtual void Decommission ()
Decommissions the agent, removing it from the simulation.
virtual void DoRegistration ()
Called to give the agent an opportunity to register for services (e.g.
virtual void InfileToDb (InfileTree *qe, DbInit di)
Translates info for a agent from an input file to the database by reading parameters from the passed InfileTree and recording data via the DbInit variable.
virtual void InitFrom (QueryableBackend *b)
Intializes an agent's internal state from an output database.
virtual void InitInv (Inventories &inv)
Provides an agent's initial inventory of resources before a simulation begins.
Institution (Context *ctx)
Default constructor for Institution Class.
virtual void Snapshot (DbInit di)
Snapshots agent-internal state to the output db via DbInit.
virtual Inventories SnapshotInv ()
Snapshots and agent's resource inventories to the output db.
virtual std::string str ()
every agent should be able to print a verbose description
virtual void Tick (int time)
Simulation agents do their beginning-of-timestep activities in the Tick method.
virtual void Tock (int time)
Simulation agents do their end-of-timestep activities in the Tock method.
virtual ~Institution ()
every agent should be destructable
Protected Member Functions
void InitFrom (Institution *m)
Detailed Description
The Institution class is the abstract class/interface used by all institution agents.
Introduction The Institution type assists in defining the
region-institution-facility hierarchy in Cyclus. A Institution institution is an actor associated with a set of facilities for which it is responsible. An Institution may be used to adjust preferences in the ResourceExchange to make material routing decisions based on interfacility relationships. Deployment is a primary differentiator between different Institution implementations.
Definition at line 32 of file institution.h.
Constructor & Destructor Documentation
cyclus::Institution::Institution (Context * ctx)
Default constructor for Institution Class.
Definition at line 18 of file institution.cc.
References cyclus::Agent::kind_.
virtual cyclus::Institution::~Institution () [inline, virtual]
every agent should be destructable
Definition at line 46 of file institution.h.
Member Function Documentation
void cyclus::Institution::Build (Agent * parent) [virtual]
perform all tasks required when an inst enters the simulation
Reimplemented from cyclus::Agent.
Definition at line 34 of file institution.cc.
void cyclus::Institution::Decommission () [virtual]
Decommissions the agent, removing it from the simulation.
Results in destruction of the agent object. If agents write their own Decommission method, they must call their superclass' Decommission method at the END of their Decommission method.
Reimplemented from cyclus::Agent.
Definition at line 42 of file institution.cc.
References cyclus::Agent::context(), and cyclus::Context::UnregisterTimeListener().
void cyclus::Institution::DoRegistration () [virtual]
Called to give the agent an opportunity to register for services (e.g.
ticks/tocks and resource exchange). Note that this may be called more than once, and so agents should track their registrations carefully.
Reimplemented from cyclus::Agent.
Definition at line 38 of file institution.cc.
References cyclus::Agent::context(), and cyclus::Context::RegisterTimeListener().
virtual void cyclus::Institution::InfileToDb (InfileTree * qe, DbInit di) [inline, virtual]
Translates info for a agent from an input file to the database by reading parameters from the passed InfileTree and recording data via the DbInit variable.
The simulation and agent id's are automatically injected in all data transfered through DbInit. This method must be implemented by all agents. This method must call the superclass' InfileToDb method before doing any other work.
Agent parameters in the InfileTree are scoped in the "agent/[agent-class-name]" path. The agent's class-name can be retrieved from the agent_impl method. The superclass InitFrom expects the InfileTree passed to it to be scoped identically - do NOT pass a changed-scope InfileTree to the superclass.
Example:
 class MyAgentClass : virtual public cyclus::Facility {
   // ...
   void InfileToDb(InfileTree* qe, DbInit di) {
     cyclus::Facility::InitFrom(qe); //
     // now do MyAgentClass' initialitions, e.g.:
     qe = qe->Query("agent/" + agent_impl()); // rescope the InfileTree
     // retrieve all agent params
     std::string recipe = qe->GetString("recipe");
     std::string in_commod = qe->GetString("in_commod");
     std::string out_commod = qe->GetString("out_commod");
     di.NewDatum("MyAgentTable1")
       ->AddVal("recipe", recipe)
       ->AddVal("in_commod", in_commod)
       ->AddVal("out_commod", out_commod)
       ->Record();
     // ...
   };
   // ...
 };
Warning:
this method MUST NOT modify the agent's state.
Reimplemented from cyclus::Agent.
Definition at line 49 of file institution.h.
virtual void cyclus::Institution::InitFrom (QueryableBackend * b) [inline, virtual]
Intializes an agent's internal state from an output database.
Appropriate simulation id, agent id, and time filters are automatically included in all queries.
Warning:
Agents must NOT create any resource objects in this method.
Reimplemented from cyclus::Agent.
Definition at line 52 of file institution.h.
Referenced by InitFrom().
void cyclus::Institution::InitFrom (Institution * m) [protected]
Definition at line 22 of file institution.cc.
References InitFrom().
virtual void cyclus::Institution::InitInv (Inventories & inv) [inline, virtual]
Provides an agent's initial inventory of resources before a simulation begins.
The resources are keyed in the same way the InitInv method returned. Agents should iterate through each named inventory provided and populate the corresponding resource containers.
Warning:
agents should not modify any state outside the container filling
Implements cyclus::Agent.
Definition at line 57 of file institution.h.
virtual void cyclus::Institution::Snapshot (DbInit di) [inline, virtual]
Snapshots agent-internal state to the output db via DbInit.
This method MUST call the superclass' Snapshot method before doing any work. The simulation and agent id's in addition to the snapshot time are automatically included in all information transfered through DbInit.
Warning:
because 'SimId' 'SimTime', and 'AgentId' fields are automatically injected, those labels cannot be used for any other fields.
This method MUST NOT modify the agent's state.
Implements cyclus::Agent.
Definition at line 55 of file institution.h.
virtual Inventories cyclus::Institution::SnapshotInv () [inline, virtual]
Snapshots and agent's resource inventories to the output db.
The set of resources in each container should be stored under a string key specific to that container that will be used when re-initializing inventories for restarted simulations.
Warning:
This method should NOT modify the agent's state.
Implements cyclus::Agent.
Definition at line 59 of file institution.h.
std::string cyclus::Institution::str () [virtual]
every agent should be able to print a verbose description
Reimplemented from cyclus::Agent.
Definition at line 26 of file institution.cc.
References cyclus::Agent::parent(), and cyclus::Agent::prototype().
virtual void cyclus::Institution::Tick (int time) [inline, virtual]
Simulation agents do their beginning-of-timestep activities in the Tick method.
Parameters:
time is the current simulation timestep
Implements cyclus::TimeListener.
Definition at line 75 of file institution.h.
void cyclus::Institution::Tock (int time) [virtual]
Simulation agents do their end-of-timestep activities in the Tock method.
Parameters:
time is the current simulation timestep
Implements cyclus::TimeListener.
Definition at line 47 of file institution.cc.
References cyclus::Facility::CheckDecommissionCondition(), cyclus::Agent::children(), CLOG, cyclus::Agent::context(), cyclus::Agent::enter_time(), cyclus::LEV_INFO3, cyclus::Agent::lifetime(), cyclus::Agent::prototype(), and cyclus::Context::SchedDecom().
The documentation for this class was generated from the following files:
institution.h
institution.cc