CYCLUS: cyclus::Logger Class Reference
cyclus::Logger Class Reference
A logging tool providing finer grained control over standard output for debugging and other purposes.
#include <logger.h>
Public Member Functions
std::ostringstream & Get (LogLevel level, std::string prefix)
Logger ()
virtual ~Logger ()
Static Public Member Functions
static bool & NoAgent ()
Set whether or not agent/agent log entries should be printed.
static bool & NoMem ()
Set whether or not agent/agent log entries should be printed.
static LogLevel & ReportLevel ()
static LogLevel ToLogLevel (std::string text)
static std::string ToString (LogLevel level)
Protected Attributes
std::ostringstream os
Private Member Functions
Logger (const Logger &)
Logger & operator= (const Logger &)
Static Private Member Functions
static void AddLevel (LogLevel level, std::string text)
static void Initialize ()
Static Private Attributes
static int field_width_ = 6
static std::vector< std::string > level_to_string
Used to map LogLevel enum values into strings.
static bool no_agent = false
Indicates whether or not agent/agent log entries should be printed.
static bool no_mem = false
Indicates whether or not memory management log entries should be printed.
static LogLevel report_level = (Logger::Initialize(), LEV_ERROR)
static int spc_per_lev_ = 2
static std::map< std::string,
LogLevel > string_to_level
Used to map strings into LogLevel enum values.
Detailed Description
A logging tool providing finer grained control over standard output for debugging and other purposes.
Warning:
do not place any state-changing expressions with the LOG macro as they may not run if the report level excludes the specified level.
Definition at line 76 of file logger.h.
Constructor & Destructor Documentation
cyclus::Logger::Logger () [inline]
Definition at line 79 of file logger.h.
cyclus::Logger::~Logger () [virtual]
Definition at line 35 of file logger.cc.
References os.
cyclus::Logger::Logger (const Logger &) [private]
Member Function Documentation
void cyclus::Logger::AddLevel (LogLevel level, std::string text) [static, private]
Used by the initialize method to populate the level_to_string and string_to_level static variables.
Definition at line 79 of file logger.cc.
References field_width_, level_to_string, and string_to_level.
Referenced by Initialize().
std::ostringstream & cyclus::Logger::Get (LogLevel level, std::string prefix)
Returns a string stream by reference that is flushed to stdout by the Logger class destructor.
Definition at line 18 of file logger.cc.
References cyclus::LEV_INFO1, os, spc_per_lev_, and ToString().
void cyclus::Logger::Initialize () [static, private]
Used to populate the level_to_string and string_to_level vector/map before cyclus code execution begins
Definition at line 43 of file logger.cc.
References AddLevel(), cyclus::LEV_DEBUG1, cyclus::LEV_DEBUG2, cyclus::LEV_DEBUG3, cyclus::LEV_DEBUG4, cyclus::LEV_DEBUG5, cyclus::LEV_ERROR, cyclus::LEV_INFO1, cyclus::LEV_INFO2, cyclus::LEV_INFO3, cyclus::LEV_INFO4, cyclus::LEV_INFO5, and cyclus::LEV_WARN.
static bool& cyclus::Logger::NoAgent () [inline, static]
Set whether or not agent/agent log entries should be printed.
Definition at line 98 of file logger.h.
References no_agent.
static bool& cyclus::Logger::NoMem () [inline, static]
Set whether or not agent/agent log entries should be printed.
Definition at line 103 of file logger.h.
References no_mem.
Logger& cyclus::Logger::operator= (const Logger &) [private]
static LogLevel& cyclus::Logger::ReportLevel () [inline, static]
Use to get/set the (global) log level report cutoff.
Returns:
the report level cutoff by reference
Definition at line 93 of file logger.h.
References report_level.
LogLevel cyclus::Logger::ToLogLevel (std::string text) [static]
Converts a string into a corresponding LogLevel value.
For strings that do not correspond to any particular LogLevel enum value, the method returns the LogLevel value `LEV_ERROR`. This method is primarily intended for translating command line verbosity argument(s) into appropriate report levels. LOG(level) statements
Definition at line 59 of file logger.cc.
References cyclus::LEV_ERROR, and string_to_level.
std::string cyclus::Logger::ToString (LogLevel level) [static]
Converts a LogLevel enum value into a corrsponding string.
For a level argments that have no corresponding string value, the string `BAD_LEVEL` is returned. This method is primarily intended for translating LOG(level) statement levels into appropriate strings for output to stdout.
Definition at line 68 of file logger.cc.
References level_to_string.
Referenced by Get().
Member Data Documentation
int cyclus::Logger::field_width_ = 6 [static, private]
The width (in characters) of the printed LOG(level) statements' prefixes. This should be equal to or greater than the length of the longest LogLevel enum value converted to a string (i.e. `LEV_WARN` is the longest with 11 characters).
Definition at line 175 of file logger.h.
Referenced by AddLevel().
std::vector< std::string > cyclus::Logger::level_to_string [static, private]
Used to map LogLevel enum values into strings.
Definition at line 147 of file logger.h.
Referenced by AddLevel(), and ToString().
bool cyclus::Logger::no_agent = false [static, private]
Indicates whether or not agent/agent log entries should be printed.
Definition at line 141 of file logger.h.
Referenced by NoAgent().
bool cyclus::Logger::no_mem = false [static, private]
Indicates whether or not memory management log entries should be printed.
Definition at line 144 of file logger.h.
Referenced by NoMem().
std::ostringstream cyclus::Logger::os [protected]
Definition at line 127 of file logger.h.
Referenced by Get(), and ~Logger().
LogLevel cyclus::Logger::report_level = (Logger::Initialize(), LEV_ERROR) [static, private]
Cuttoff for outputing LOG(level) statement content. Statments where level==report_level will print.
Definition at line 138 of file logger.h.
Referenced by ReportLevel().
int cyclus::Logger::spc_per_lev_ = 2 [static, private]
The number of spaces indentation between different LogLevel enum values.
Definition at line 167 of file logger.h.
Referenced by Get().
std::map< std::string, LogLevel > cyclus::Logger::string_to_level [static, private]
Used to map strings into LogLevel enum values.
Definition at line 150 of file logger.h.
Referenced by AddLevel(), and ToLogLevel().
The documentation for this class was generated from the following files:
logger.h
logger.cc