CYCLUS: cyclus::Agent Class Reference
cyclus::Agent Class Reference
The abstract base class used by all types of agents that live and interact in a simulation.
#include <agent.h>
Public Member Functions
virtual void AdjustMatlPrefs (PrefMap< Material >::type &prefs)
default implementation for material preferences.
virtual void AdjustProductPrefs (PrefMap< Product >::type &prefs)
default implementation for material preferences.
Agent (Context *ctx)
Constructor for the Agent Class.
std::string agent_impl ()
get agent implementation
virtual void Build (Agent *parent=NULL)
Called when the agent enters the smiulation as an active participant and is only ever called once.
virtual void BuildNotify (Agent *m)
Called when a new child of this agent has just been built.
Agent * children (int i)
returns the ith child
const std::vector< Agent * > & children () const
returns a list of children this agent has
virtual Agent * Clone ()=0
Return a newly created/allocated prototype that is an exact copy of this.
Context * context () const
Returns this agent's current simulation context.
virtual void Decommission ()
Decommissions the agent, removing it from the simulation.
virtual void DecomNotify (Agent *m)
Called when a new child of this agent is about to be decommissioned.
virtual void DoRegistration ()
Called to give the agent an opportunity to register for services (e.g.
const int enter_time () const
returns the time this agent began operation (-1 if the agent has never been built).
std::vector< std::string > GetTreePrintOuts (Agent *m)
returns a vector of strings representing the parent-child tree at the node for Agent m
const int id () const
get agent instance ID
virtual void InfileToDb (InfileTree *qe, DbInit di)
Translates info for a agent from an input file to the database by reading parameters from the passed InfileTree and recording data via the DbInit variable.
virtual void InitFrom (QueryableBackend *b)
Intializes an agent's internal state from an output database.
virtual void InitInv (Inventories &inv)=0
Provides an agent's initial inventory of resources before a simulation begins.
const std::string kind () const
returns a string that describes the agent subclass (e.g. Region, etc.)
const int lifetime () const
returns the time this agent will cease operation (-1 if the agent is still operating).
Agent * parent () const
returns parent of this agent
const int parent_id () const
returns the parent's id
std::string PrintChildren ()
recursively prints the parent-child tree
const std::string prototype () const
get agent instance name
virtual std::string schema ()
Returns a module's xml rng schema for initializing from input files.
void set_agent_impl (std::string new_impl)
set agent implementation
virtual void Snapshot (DbInit di)=0
Snapshots agent-internal state to the output db via DbInit.
virtual Inventories SnapshotInv ()=0
Snapshots and agent's resource inventories to the output db.
virtual std::string str ()
every agent should be able to print a verbose description
virtual ~Agent ()
Recursively destructs all children and removes references to self form parent.
Protected Member Functions
virtual std::string InformErrorMsg (std::string msg)
adds agent-specific information prefix to an error message
void InitFrom (Agent *m)
Initializes a agent by copying parameters from the passed agent m.
Protected Attributes
std::string kind_
describes the agent subclass (e.g.
Private Member Functions
void AddToTable ()
adds an agent to the transactiont table
Agent (const Agent &m)
Prevents creation/use of copy constructors (including in subclasses).
void Connect (Agent *parent)
connects an agent to its parent.
Private Attributes
std::string agent_impl_
concrete type of a agent (e.g. "MyReactorAgent")
std::vector< Agent * > children_
children of this agent
Context * ctx_
int enter_time_
born on date of this agent
int id_
an instance-unique ID for the agent
int lifetime_
length of time this agent is intended to operate
Agent * parent_
parent of this agent
int parent_id_
parent's ID of this agent Note: we keep the parent id in the agent so we can reference it even if the parent is deallocated.
std::string prototype_
Static Private Attributes
static int next_id_ = 0
Stores the next available facility ID.
Friends
class SimInit
Detailed Description
The abstract base class used by all types of agents that live and interact in a simulation.
There are several methods that must be implemented in support of simulation initialization, snapshotting and restart: InfileToDb, InitFrom(QueryableBackend*), Snapshot, SnapshotInv, and InitInv. These methods all do inter-related things. Notably, the InfileToDb, InitFrom, and Snapshot methods must all write/read to/from the same database tables (and table schemas).
Definition at line 39 of file agent.h.
Constructor & Destructor Documentation
cyclus::Agent::Agent (Context * ctx)
Constructor for the Agent Class.
Warning:
all constructors must set id_ and increment next_id_
Definition at line 60 of file agent.cc.
References cyclus::Context::agent_list_, ctx_, id_, cyclus::LEV_DEBUG3, and MLOG.
cyclus::Agent::~Agent () [virtual]
Recursively destructs all children and removes references to self form parent.
Definition at line 73 of file agent.cc.
References cyclus::Context::agent_list_, children_, CLOG, context(), ctx_, cyclus::Context::DelAgent(), id(), id_, cyclus::LEV_DEBUG2, cyclus::LEV_DEBUG3, cyclus::LEV_DEBUG4, MLOG, parent_, and prototype().
cyclus::Agent::Agent (const Agent & m) [inline, private]
Prevents creation/use of copy constructors (including in subclasses).
Cloning and InitFrom should be used instead.
Definition at line 280 of file agent.h.
Member Function Documentation
void cyclus::Agent::AddToTable () [private]
adds an agent to the transactiont table
Definition at line 172 of file agent.cc.
References cyclus::Datum::AddVal(), agent_impl_, ctx_, enter_time_, id_, kind_, lifetime_, cyclus::Context::NewDatum(), parent_id_, prototype_, and cyclus::Datum::Record().
Referenced by Build().
virtual void cyclus::Agent::AdjustMatlPrefs (PrefMap< Material >::type & prefs) [inline, virtual]
default implementation for material preferences.
Definition at line 193 of file agent.h.
Referenced by cyclus::AdjustPrefs().
virtual void cyclus::Agent::AdjustProductPrefs (PrefMap< Product >::type & prefs) [inline, virtual]
default implementation for material preferences.
Definition at line 196 of file agent.h.
Referenced by cyclus::AdjustPrefs().
std::string cyclus::Agent::agent_impl () [inline]
get agent implementation
Definition at line 211 of file agent.h.
References agent_impl_.
Referenced by cyclus::Context::AddPrototype(), and cyclus::DbInit::NewDatum().
void cyclus::Agent::Build (Agent * parent = NULL) [virtual]
Called when the agent enters the smiulation as an active participant and is only ever called once.
Agents should NOT register for services (such as ticks/tocks and resource exchange) in this method. If agents implement this method, they must call their superclass's Build method at the BEGINING of their Build method.
Parameters:
parent this agent's parent. NULL if this agent has no parent.
Reimplemented in cyclus::Facility, cyclus::Region, and cyclus::Institution.
Definition at line 110 of file agent.cc.
References AddToTable(), agent_impl_, CLOG, Connect(), ctx_, DoRegistration(), enter_time_, id(), cyclus::LEV_DEBUG1, cyclus::LEV_DEBUG3, prototype(), and cyclus::Context::time().
Referenced by cyclus::XMLFileLoader::BuildAgent(), and cyclus::Timer::DoBuild().
virtual void cyclus::Agent::BuildNotify (Agent * m) [inline, virtual]
Called when a new child of this agent has just been built.
It is possible for this method to be called before the simulation has started when initially existing agents are being setup.
Definition at line 176 of file agent.h.
Referenced by cyclus::XMLFileLoader::BuildAgent().
Agent* cyclus::Agent::children (int i) [inline]
returns the ith child
Definition at line 188 of file agent.h.
References children_.
Referenced by GetTreePrintOuts().
const std::vector<Agent*>& cyclus::Agent::children () const [inline]
returns a list of children this agent has
Definition at line 240 of file agent.h.
References children_.
Referenced by cyclus::Region::str(), and cyclus::Institution::Tock().
virtual Agent* cyclus::Agent::Clone () [pure virtual]
Return a newly created/allocated prototype that is an exact copy of this.
All initialization and state cloning operations should be done in the agent's InitFrom method. The new agent instance should generally NOT be created using a default copy-constructor.
Example:
 class MyAgentClass : virtual public Agent {
   ...
   virtual Agent* Clone() {
     MyAgentClass* m = new MyAgentClass(context());
     m->InitFrom(this);
     return m;
   };
   ...
 };
Implements cyclus::StateWrangler.
Implemented in cyclus::Dummy.
Referenced by cyclus::Context::CreateAgent().
void cyclus::Agent::Connect (Agent * parent) [private]
connects an agent to its parent.
Definition at line 123 of file agent.cc.
References children_, id(), parent(), parent_, parent_id_, and prototype().
Referenced by Build(), and cyclus::SimInit::LoadInitialAgents().
Context* cyclus::Agent::context () const [inline]
Returns this agent's current simulation context.
Definition at line 220 of file agent.h.
References ctx_.
Referenced by cyclus::Product::Create(), cyclus::Material::Create(), cyclus::Institution::Decommission(), cyclus::Region::Decommission(), cyclus::Facility::Decommission(), cyclus::Institution::DoRegistration(), cyclus::Region::DoRegistration(), cyclus::Facility::DoRegistration(), InformErrorMsg(), cyclus::DbInit::NewDatum(), cyclus::SimInit::SnapAgent(), cyclus::Institution::Tock(), and ~Agent().
void cyclus::Agent::Decommission () [virtual]
Decommissions the agent, removing it from the simulation.
Results in destruction of the agent object. If agents write their own Decommission method, they must call their superclass' Decommission method at the END of their Decommission method.
Reimplemented in cyclus::Facility, cyclus::Region, and cyclus::Institution.
Definition at line 135 of file agent.cc.
References cyclus::Datum::AddVal(), CLOG, ctx_, cyclus::Context::DelAgent(), cyclus::LEV_INFO3, cyclus::Context::NewDatum(), prototype(), and cyclus::Context::time().
Referenced by cyclus::Timer::DoDecom().
virtual void cyclus::Agent::DecomNotify (Agent * m) [inline, virtual]
Called when a new child of this agent is about to be decommissioned.
Definition at line 179 of file agent.h.
Referenced by cyclus::Timer::DoDecom().
virtual void cyclus::Agent::DoRegistration () [inline, virtual]
Called to give the agent an opportunity to register for services (e.g.
ticks/tocks and resource exchange). Note that this may be called more than once, and so agents should track their registrations carefully.
Reimplemented in cyclus::Facility, cyclus::Region, and cyclus::Institution.
Definition at line 171 of file agent.h.
Referenced by Build(), and cyclus::SimInit::LoadInitialAgents().
const int cyclus::Agent::enter_time () const [inline]
returns the time this agent began operation (-1 if the agent has never been built).
Definition at line 233 of file agent.h.
References enter_time_.
Referenced by cyclus::SimInit::Snapshot(), cyclus::Facility::str(), and cyclus::Institution::Tock().
std::vector< std::string > cyclus::Agent::GetTreePrintOuts (Agent * m)
returns a vector of strings representing the parent-child tree at the node for Agent m
Parameters:
m the agent node to base as the root of this print tree
Definition at line 156 of file agent.cc.
References children(), and prototype().
Referenced by PrintChildren().
const int cyclus::Agent::id () const [inline]
get agent instance ID
Definition at line 208 of file agent.h.
References id_.
Referenced by cyclus::Context::AddPrototype(), Build(), Connect(), cyclus::ResTracker::Create(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadInitialAgents(), cyclus::SimInit::LoadInventories(), cyclus::DbInit::NewDatum(), cyclus::TradeExecutor< T >::RecordTrades(), cyclus::Context::SchedBuild(), cyclus::Context::SchedDecom(), cyclus::SimInit::SnapAgent(), and ~Agent().
void cyclus::Agent::InfileToDb (InfileTree * qe, DbInit di) [virtual]
Translates info for a agent from an input file to the database by reading parameters from the passed InfileTree and recording data via the DbInit variable.
The simulation and agent id's are automatically injected in all data transfered through DbInit. This method must be implemented by all agents. This method must call the superclass' InfileToDb method before doing any other work.
Agent parameters in the InfileTree are scoped in the "agent/[agent-class-name]" path. The agent's class-name can be retrieved from the agent_impl method. The superclass InitFrom expects the InfileTree passed to it to be scoped identically - do NOT pass a changed-scope InfileTree to the superclass.
Example:
 class MyAgentClass : virtual public cyclus::Facility {
   // ...
   void InfileToDb(InfileTree* qe, DbInit di) {
     cyclus::Facility::InitFrom(qe); //
     // now do MyAgentClass' initialitions, e.g.:
     qe = qe->Query("agent/" + agent_impl()); // rescope the InfileTree
     // retrieve all agent params
     std::string recipe = qe->GetString("recipe");
     std::string in_commod = qe->GetString("in_commod");
     std::string out_commod = qe->GetString("out_commod");
     di.NewDatum("MyAgentTable1")
       ->AddVal("recipe", recipe)
       ->AddVal("in_commod", in_commod)
       ->AddVal("out_commod", out_commod)
       ->Record();
     // ...
   };
   // ...
 };
Warning:
this method MUST NOT modify the agent's state.
Implements cyclus::StateWrangler.
Reimplemented in cyclus::Region, cyclus::Facility, and cyclus::Institution.
Definition at line 38 of file agent.cc.
References cyclus::Datum::AddVal(), cyclus::InfileTree::GetString(), lifetime(), cyclus::DbInit::NewDatum(), and cyclus::Datum::Record().
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), and cyclus::XMLFileLoader::LoadInitialAgents().
std::string cyclus::Agent::InformErrorMsg (std::string msg) [protected, virtual]
adds agent-specific information prefix to an error message
Definition at line 29 of file agent.cc.
References agent_impl_, context(), prototype_, and cyclus::Context::time().
void cyclus::Agent::InitFrom (QueryableBackend * b) [virtual]
Intializes an agent's internal state from an output database.
Appropriate simulation id, agent id, and time filters are automatically included in all queries.
Warning:
Agents must NOT create any resource objects in this method.
Implements cyclus::StateWrangler.
Reimplemented in cyclus::Region, cyclus::Facility, and cyclus::Institution.
Definition at line 47 of file agent.cc.
References cyclus::QueryResult::GetVal(), lifetime_, prototype_, and cyclus::QueryableBackend::Query().
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), and cyclus::XMLFileLoader::LoadInitialAgents().
void cyclus::Agent::InitFrom (Agent * m) [protected]
Initializes a agent by copying parameters from the passed agent m.
This method must be implemented by all agents. This method must call the superclass' InitFrom method. The InitFrom method should only initialize this class' members - not inherited state. The superclass InitFrom should generally be called before any other work is done.
Parameters:
m the agent containing state that should be used to initialize this agent.
Example:
 class MyAgentClass : virtual public cyclus::Facility {
   // ...
   void InitFrom(MyAgentClass* m) {
     cyclus::Facility::InitFrom(m); // call superclass' InitFrom
     // now do MyAgentClass' initialitions, e.g.:
     my_var_ = m->my_var_;
     // ...
   };
   // ...
 };
Definition at line 20 of file agent.cc.
References agent_impl_, ctx_, id_, kind_, lifetime_, next_id_, and prototype_.
virtual void cyclus::Agent::InitInv (Inventories & inv) [pure virtual]
Provides an agent's initial inventory of resources before a simulation begins.
The resources are keyed in the same way the InitInv method returned. Agents should iterate through each named inventory provided and populate the corresponding resource containers.
Warning:
agents should not modify any state outside the container filling
Implemented in cyclus::Region, and cyclus::Institution.
Referenced by cyclus::SimInit::LoadInventories().
const std::string cyclus::Agent::kind () const [inline]
returns a string that describes the agent subclass (e.g. Region, etc.)
Definition at line 217 of file agent.h.
References kind_.
Referenced by cyclus::BuildMasterSchema().
const int cyclus::Agent::lifetime () const [inline]
returns the time this agent will cease operation (-1 if the agent is still operating).
Returns -1 for indefinite lifetime.
Definition at line 237 of file agent.h.
References lifetime_.
Referenced by InfileToDb(), cyclus::Facility::str(), and cyclus::Institution::Tock().
Agent* cyclus::Agent::parent () const [inline]
returns parent of this agent
Definition at line 226 of file agent.h.
References parent_.
Referenced by cyclus::ResourceExchange< T >::AdjustPrefs_(), Connect(), cyclus::Timer::DoDecom(), and cyclus::Institution::str().
const int cyclus::Agent::parent_id () const [inline]
returns the parent's id
Definition at line 229 of file agent.h.
References parent_id_.
std::string cyclus::Agent::PrintChildren ()
recursively prints the parent-child tree
Definition at line 144 of file agent.cc.
References children_, GetTreePrintOuts(), and prototype().
const std::string cyclus::Agent::prototype () const [inline]
get agent instance name
Definition at line 205 of file agent.h.
References prototype_.
Referenced by Build(), Connect(), cyclus::Facility::Decommission(), Decommission(), GetTreePrintOuts(), PrintChildren(), cyclus::Institution::str(), cyclus::Institution::Tock(), and ~Agent().
virtual std::string cyclus::Agent::schema () [inline, virtual]
Returns a module's xml rng schema for initializing from input files.
All concrete agents should override this method.
Implements cyclus::StateWrangler.
Definition at line 200 of file agent.h.
Referenced by cyclus::BuildFlatMasterSchema(), and cyclus::BuildMasterSchema().
void cyclus::Agent::set_agent_impl (std::string new_impl) [inline]
set agent implementation
Definition at line 214 of file agent.h.
References agent_impl_.
Referenced by cyclus::XMLFlatLoader::LoadInitialAgents(), and cyclus::XMLFileLoader::LoadInitialAgents().
void cyclus::Agent::Snapshot (DbInit di) [pure virtual]
Snapshots agent-internal state to the output db via DbInit.
This method MUST call the superclass' Snapshot method before doing any work. The simulation and agent id's in addition to the snapshot time are automatically included in all information transfered through DbInit.
Warning:
because 'SimId' 'SimTime', and 'AgentId' fields are automatically injected, those labels cannot be used for any other fields.
This method MUST NOT modify the agent's state.
Implements cyclus::StateWrangler.
Implemented in cyclus::Region, cyclus::Facility, and cyclus::Institution.
Definition at line 53 of file agent.cc.
References cyclus::Datum::AddVal(), lifetime_, cyclus::DbInit::NewDatum(), prototype_, and cyclus::Datum::Record().
Referenced by cyclus::SimInit::SnapAgent().
virtual Inventories cyclus::Agent::SnapshotInv () [pure virtual]
Snapshots and agent's resource inventories to the output db.
The set of resources in each container should be stored under a string key specific to that container that will be used when re-initializing inventories for restarted simulations.
Warning:
This method should NOT modify the agent's state.
Implemented in cyclus::Region, and cyclus::Institution.
Referenced by cyclus::SimInit::SnapAgent().
std::string cyclus::Agent::str () [virtual]
every agent should be able to print a verbose description
Reimplemented in cyclus::Facility, cyclus::Region, and cyclus::Institution.
Definition at line 98 of file agent.cc.
References agent_impl_, id_, kind_, parent_id_, and prototype_.
Friends And Related Function Documentation
friend class SimInit [friend]
Definition at line 40 of file agent.h.
Member Data Documentation
std::string cyclus::Agent::agent_impl_ [private]
concrete type of a agent (e.g. "MyReactorAgent")
Definition at line 311 of file agent.h.
Referenced by AddToTable(), agent_impl(), Build(), InformErrorMsg(), InitFrom(), set_agent_impl(), and str().
std::vector<Agent*> cyclus::Agent::children_ [private]
children of this agent
Definition at line 292 of file agent.h.
Referenced by children(), Connect(), PrintChildren(), and ~Agent().
Context* cyclus::Agent::ctx_ [private]
Definition at line 316 of file agent.h.
Referenced by AddToTable(), Agent(), Build(), context(), Decommission(), InitFrom(), and ~Agent().
int cyclus::Agent::enter_time_ [private]
born on date of this agent
Definition at line 303 of file agent.h.
Referenced by AddToTable(), Build(), and enter_time().
int cyclus::Agent::id_ [private]
an instance-unique ID for the agent
Definition at line 314 of file agent.h.
Referenced by AddToTable(), Agent(), id(), InitFrom(), cyclus::SimInit::LoadInitialAgents(), str(), and ~Agent().
std::string cyclus::Agent::kind_ [protected]
describes the agent subclass (e.g.
Region, Inst, etc.). The in-core subclasses must set this variable in their constructor(s).
Definition at line 275 of file agent.h.
Referenced by AddToTable(), cyclus::Facility::Facility(), InitFrom(), cyclus::Institution::Institution(), kind(), cyclus::Region::Region(), and str().
int cyclus::Agent::lifetime_ [private]
length of time this agent is intended to operate
Definition at line 306 of file agent.h.
Referenced by AddToTable(), InitFrom(), lifetime(), and Snapshot().
int cyclus::Agent::next_id_ = 0 [static, private]
Stores the next available facility ID.
Definition at line 289 of file agent.h.
Referenced by InitFrom(), cyclus::SimInit::LoadNextIds(), and cyclus::SimInit::Snapshot().
Agent* cyclus::Agent::parent_ [private]
parent of this agent
Definition at line 295 of file agent.h.
Referenced by Connect(), parent(), and ~Agent().
int cyclus::Agent::parent_id_ [private]
parent's ID of this agent Note: we keep the parent id in the agent so we can reference it even if the parent is deallocated.
Definition at line 300 of file agent.h.
Referenced by AddToTable(), Connect(), parent_id(), and str().
std::string cyclus::Agent::prototype_ [private]
Definition at line 308 of file agent.h.
Referenced by AddToTable(), InformErrorMsg(), InitFrom(), prototype(), Snapshot(), and str().
The documentation for this class was generated from the following files:
agent.h
agent.cc