CYCLUS: cyclus::Timer Class Reference
cyclus::Timer Class Reference
Controls simulation timestepping and inter-timestep phases.
#include <timer.h>
Public Member Functions
int dur ()
Returns the duration of the simulation this Timer's timing.
void Initialize (Context *ctx, SimInfo si)
Sets intial time-related parameters for the simulation.
void RegisterTimeListener (TimeListener *agent)
Registers an agent to receive tick/tock notifications every timestep.
void Reset ()
resets all data (registered listeners, etc.) to empty or initial state
void RunSim ()
Runs the simulation.
void SchedBuild (Agent *parent, std::string proto_name, int t)
Schedules the named prototype to be built for the specified parent at timestep t.
void SchedDecom (Agent *m, int time)
Schedules the given Agent to be decommissioned at the specified timestep t.
void Snapshot ()
Makes a snapshot of the simulation state to the output database.
int time ()
Returns the current time, in months since the simulation started.
Timer ()
void UnregisterTimeListener (TimeListener *tl)
Removes an agent from receiving tick/tock notifications.
Private Member Functions
void DoBuild ()
builds all agents queued for the current timestep.
void DoDecom ()
decommissions all agents queued for the current timestep.
void DoResEx (ExchangeManager< Material > *matmgr, ExchangeManager< Product > *genmgr)
Runs the resource exchange process for all traders.
void DoTick ()
sends the tick signal to all of the agents receiving time notifications.
void DoTock ()
sends the tock signal to all of the agents receiving time notifications.
Private Attributes
std::map< int, std::vector
< std::pair< std::string,
Agent * > > > build_queue_
Context * ctx_
std::map< int, std::vector
< Agent * > > decom_queue_
SimInfo si_
std::set< TimeListener * > tickers_
Concrete agents that desire to receive tick and tock notifications.
int time_
The current time, measured in months from when the simulation started.
bool want_snapshot_
Detailed Description
Controls simulation timestepping and inter-timestep phases.
Definition at line 20 of file timer.h.
Constructor & Destructor Documentation
cyclus::Timer::Timer ()
Definition at line 140 of file timer.cc.
Member Function Documentation
void cyclus::Timer::DoBuild () [private]
builds all agents queued for the current timestep.
Definition at line 44 of file timer.cc.
References cyclus::Agent::Build(), build_queue_, cyclus::Context::CreateAgent(), ctx_, and time_.
Referenced by RunSim().
void cyclus::Timer::DoDecom () [private]
decommissions all agents queued for the current timestep.
Definition at line 77 of file timer.cc.
References decom_queue_, cyclus::Agent::Decommission(), cyclus::Agent::DecomNotify(), cyclus::Agent::parent(), and time_.
Referenced by RunSim().
void cyclus::Timer::DoResEx (ExchangeManager< Material > * matmgr, ExchangeManager< Product > * genmgr) [private]
Runs the resource exchange process for all traders.
Definition at line 63 of file timer.cc.
References cyclus::ExchangeManager< T >::Execute().
Referenced by RunSim().
void cyclus::Timer::DoTick () [private]
sends the tick signal to all of the agents receiving time notifications.
Definition at line 55 of file timer.cc.
References tickers_, and time_.
Referenced by RunSim().
void cyclus::Timer::DoTock () [private]
sends the tock signal to all of the agents receiving time notifications.
Definition at line 69 of file timer.cc.
References tickers_, and time_.
Referenced by RunSim().
int cyclus::Timer::dur ()
Returns the duration of the simulation this Timer's timing.
Returns:
the duration, in months
Definition at line 136 of file timer.cc.
References cyclus::SimInfo::duration, and si_.
void cyclus::Timer::Initialize (Context * ctx, SimInfo si)
Sets intial time-related parameters for the simulation.
Parameters:
ctx simulation context
Definition at line 120 of file timer.cc.
References ctx_, cyclus::SimInfo::decay_period, cyclus::SimInfo::duration, cyclus::SimInfo::m0, si_, time_, and cyclus::SimInfo::y0.
Referenced by cyclus::Context::InitSim().
void cyclus::Timer::RegisterTimeListener (TimeListener * agent)
Registers an agent to receive tick/tock notifications every timestep.
Agents should register from their Deploy method.
Definition at line 87 of file timer.cc.
References tickers_.
Referenced by cyclus::Context::RegisterTimeListener().
void cyclus::Timer::Reset ()
resets all data (registered listeners, etc.) to empty or initial state
Definition at line 113 of file timer.cc.
References build_queue_, decom_queue_, si_, and tickers_.
void cyclus::Timer::RunSim ()
Runs the simulation.
Definition at line 15 of file timer.cc.
References CLOG, ctx_, cyclus::SimInfo::decay_period, cyclus::Material::DecayAll(), DoBuild(), DoDecom(), DoResEx(), DoTick(), DoTock(), cyclus::SimInfo::duration, cyclus::LEV_INFO1, cyclus::LEV_INFO2, si_, Snapshot(), time_, and want_snapshot_.
void cyclus::Timer::SchedBuild (Agent * parent, std::string proto_name, int t)
Schedules the named prototype to be built for the specified parent at timestep t.
Definition at line 95 of file timer.cc.
References build_queue_, and time_.
Referenced by cyclus::Context::SchedBuild().
void cyclus::Timer::SchedDecom (Agent * m, int time)
Schedules the given Agent to be decommissioned at the specified timestep t.
Definition at line 102 of file timer.cc.
References decom_queue_, and time_.
Referenced by cyclus::Context::SchedDecom().
void cyclus::Timer::Snapshot () [inline]
Makes a snapshot of the simulation state to the output database.
Definition at line 53 of file timer.h.
References want_snapshot_.
Referenced by RunSim(), and cyclus::Context::Snapshot().
int cyclus::Timer::time ()
Returns the current time, in months since the simulation started.
Returns:
the current time
Definition at line 109 of file timer.cc.
References time_.
Referenced by cyclus::Context::time().
void cyclus::Timer::UnregisterTimeListener (TimeListener * tl)
Removes an agent from receiving tick/tock notifications.
Agents should unregister from their Decommission method.
Definition at line 91 of file timer.cc.
References tickers_.
Referenced by cyclus::Context::UnregisterTimeListener().
Member Data Documentation
std::map<int, std::vector<std::pair<std::string, Agent*> > > cyclus::Timer::build_queue_ [private]
Definition at line 98 of file timer.h.
Referenced by DoBuild(), Reset(), and SchedBuild().
Context* cyclus::Timer::ctx_ [private]
Definition at line 84 of file timer.h.
Referenced by DoBuild(), Initialize(), and RunSim().
std::map<int, std::vector<Agent*> > cyclus::Timer::decom_queue_ [private]
Definition at line 101 of file timer.h.
Referenced by DoDecom(), Reset(), and SchedDecom().
SimInfo cyclus::Timer::si_ [private]
Definition at line 90 of file timer.h.
Referenced by dur(), Initialize(), Reset(), and RunSim().
std::set<TimeListener*> cyclus::Timer::tickers_ [private]
Concrete agents that desire to receive tick and tock notifications.
Definition at line 95 of file timer.h.
Referenced by DoTick(), DoTock(), RegisterTimeListener(), Reset(), and UnregisterTimeListener().
int cyclus::Timer::time_ [private]
The current time, measured in months from when the simulation started.
Definition at line 88 of file timer.h.
Referenced by DoBuild(), DoDecom(), DoTick(), DoTock(), Initialize(), RunSim(), SchedBuild(), SchedDecom(), and time().
bool cyclus::Timer::want_snapshot_ [private]
Definition at line 92 of file timer.h.
Referenced by RunSim(), and Snapshot().
The documentation for this class was generated from the following files:
timer.h
timer.cc