CYCLUS: cyclus::Request< T > Class Template Reference
cyclus::Request< T > Class Template Reference
A Request encapsulates all the information required to communicate the needs of an agent in the Dynamic Resource Exchange, including the commodity it needs as well as a resource specification for that commodity.
#include <request.h>
Public Types
typedef boost::shared_ptr
< Request< T > > Ptr
Public Member Functions
std::string commodity () const
bool exclusive () const
RequestPortfolio< T >::Ptr portfolio () const
double preference () const
Trader * requester () const
boost::shared_ptr< T > target () const
Static Public Member Functions
static Request< T >::Ptr Create (boost::shared_ptr< T > target, Trader *requester, typename RequestPortfolio< T >::Ptr portfolio, std::string commodity="", double preference=0, bool exclusive=false)
a factory method for a request
static Request< T >::Ptr Create (boost::shared_ptr< T > target, Trader *requester, std::string commodity="", double preference=0, bool exclusive=false)
a factory method for a bid for a bid without a portfolio
Private Member Functions
Request (boost::shared_ptr< T > target, Trader *requester, std::string commodity="", double preference=0, bool exclusive=false)
constructors are private to require use of factory methods
Request (boost::shared_ptr< T > target, Trader *requester, typename RequestPortfolio< T >::Ptr portfolio, std::string commodity="", double preference=0, bool exclusive=false)
Private Attributes
std::string commodity_
bool exclusive_
RequestPortfolio< T >::Ptr portfolio_
double preference_
Trader * requester_
boost::shared_ptr< T > target_
Detailed Description
template<class T>
class cyclus::Request< T >
A Request encapsulates all the information required to communicate the needs of an agent in the Dynamic Resource Exchange, including the commodity it needs as well as a resource specification for that commodity.
A Request is templated its resource.
Definition at line 21 of file request.h.
Member Typedef Documentation
template<class T> typedef boost::shared_ptr< Request<T> > cyclus::Request< T >::Ptr
Definition at line 23 of file request.h.
Constructor & Destructor Documentation
template<class T> cyclus::Request< T >::Request (boost::shared_ptr< T > target, Trader * requester, std::string commodity = "", double preference = 0, bool exclusive = false) [inline, private]
constructors are private to require use of factory methods
Definition at line 79 of file request.h.
template<class T> cyclus::Request< T >::Request (boost::shared_ptr< T > target, Trader * requester, typename RequestPortfolio< T >::Ptr portfolio, std::string commodity = "", double preference = 0, bool exclusive = false) [inline, private]
Definition at line 88 of file request.h.
Member Function Documentation
template<class T> std::string cyclus::Request< T >::commodity () const [inline]
Returns:
the commodity associated with this request
Definition at line 64 of file request.h.
References cyclus::Request< T >::commodity_.
Referenced by cyclus::ExchangeContext< T >::AddRequest(), and cyclus::Request< T >::Create().
template<class T> static Request<T>::Ptr cyclus::Request< T >::Create (boost::shared_ptr< T > target, Trader * requester, typename RequestPortfolio< T >::Ptr portfolio, std::string commodity = "", double preference = 0, bool exclusive = false) [inline, static]
a factory method for a request
Parameters:
target the target resource associated with this request
requester the requester
portfolio the porftolio of which this request is a part
commodity the commodity associated with this request
preference the preference associated with this request (relative to others in the portfolio)
exclusive a flag denoting that this request must be met exclusively, i.e., in its entirety by a single offer
Definition at line 34 of file request.h.
References cyclus::Request< T >::commodity(), cyclus::Request< T >::exclusive(), and cyclus::Request< T >::preference().
template<class T> static Request<T>::Ptr cyclus::Request< T >::Create (boost::shared_ptr< T > target, Trader * requester, std::string commodity = "", double preference = 0, bool exclusive = false) [inline, static]
a factory method for a bid for a bid without a portfolio
Warning:
this factory should generally only be used for testing
Definition at line 48 of file request.h.
References cyclus::Request< T >::commodity(), cyclus::Request< T >::exclusive(), and cyclus::Request< T >::preference().
template<class T> bool cyclus::Request< T >::exclusive () const [inline]
Returns:
whether or not this an exclusive request
Definition at line 75 of file request.h.
References cyclus::Request< T >::exclusive_.
Referenced by cyclus::Request< T >::Create(), and cyclus::ExclusiveStatus< T >::ExclusiveStatus().
template<class T> RequestPortfolio<T>::Ptr cyclus::Request< T >::portfolio () const [inline]
Returns:
the portfolio of which this request is a part
Definition at line 70 of file request.h.
References cyclus::Request< T >::portfolio_.
Referenced by cyclus::TranslateArc().
template<class T> double cyclus::Request< T >::preference () const [inline]
Returns:
the preference value for this request
Definition at line 67 of file request.h.
References cyclus::Request< T >::preference_.
Referenced by cyclus::Request< T >::Create().
template<class T> Trader* cyclus::Request< T >::requester () const [inline]
Returns:
the requester associated with this request
Definition at line 61 of file request.h.
References cyclus::Request< T >::requester_.
Referenced by cyclus::ExchangeContext< T >::AddRequest(), cyclus::ExchangeTranslator< T >::Translate(), and cyclus::RequestPortfolio< T >::VerifyRequester_().
template<class T> boost::shared_ptr<T> cyclus::Request< T >::target () const [inline]
Returns:
this request's target
Definition at line 58 of file request.h.
References cyclus::Request< T >::target_.
Referenced by cyclus::ExclusiveStatus< T >::ExclusiveStatus(), and cyclus::RequestPortfolio< T >::VerifyQty_().
Member Data Documentation
template<class T> std::string cyclus::Request< T >::commodity_ [private]
Definition at line 102 of file request.h.
Referenced by cyclus::Request< T >::commodity().
template<class T> bool cyclus::Request< T >::exclusive_ [private]
Definition at line 104 of file request.h.
Referenced by cyclus::Request< T >::exclusive().
template<class T> RequestPortfolio<T>::Ptr cyclus::Request< T >::portfolio_ [private]
Definition at line 103 of file request.h.
Referenced by cyclus::Request< T >::portfolio().
template<class T> double cyclus::Request< T >::preference_ [private]
Definition at line 101 of file request.h.
Referenced by cyclus::Request< T >::preference().
template<class T> Trader* cyclus::Request< T >::requester_ [private]
Definition at line 100 of file request.h.
Referenced by cyclus::Request< T >::requester().
template<class T> boost::shared_ptr<T> cyclus::Request< T >::target_ [private]
Definition at line 97 of file request.h.
Referenced by cyclus::Request< T >::target().
The documentation for this class was generated from the following file:
request.h