CYCLUS: cyclus::Facility Class Reference
cyclus::Facility Class Reference
The Facility class is the abstract class/interface used by all facility agents.
#include <facility.h>
Public Member Functions
virtual void Build (Agent *parent=NULL)
builds the facility in the simulation
virtual bool CheckDecommissionCondition ()
facilities over write this method if a condition must be met before their destructors can be called
virtual void Decommission ()
decommissions the facility, default behavior is for the facility to delete itself
virtual void DoRegistration ()
Called to give the agent an opportunity to register for services (e.g.
Facility (Context *ctx)
virtual void InfileToDb (InfileTree *qe, DbInit di)
Translates info for a agent from an input file to the database by reading parameters from the passed InfileTree and recording data via the DbInit variable.
virtual void InitFrom (QueryableBackend *b)
Intializes an agent's internal state from an output database.
void InitFrom (Facility *m)
Copy module members from a source agent.
virtual void Snapshot (DbInit di)
Snapshots agent-internal state to the output db via DbInit.
virtual std::string str ()
every agent should be able to print a verbose description
virtual ~Facility ()
Detailed Description
The Facility class is the abstract class/interface used by all facility agents.
This is all that is known externally about facilities
Introduction
The Facility type plays a primary role in Cyclus. A Facility facility is where offers and requests are generated and transmitted to a ResourceExchange and where shipments of material, issued by the exchange, are executed. The algorithms to determine what offers and requests are issued and how material shipments are handled are the primary differentiators between different Facility implementations.
Like all agent implementations, there are a number of implementations that are distributed as part of the core Cyclus application as well as implementations contributed by third-party developers. The links below describe additional parameters necessary for the complete definition of a facility of that implementation.
Available Core Implementations
SourceFacility: A facility that can produce a constant (or infinite) amount of some commodity
SinkFacility: A facility that can consume a constant (or infinite) amount of some commodity
NullFacility: A facility that consumes a constant amount of one commodity and produces a constant amount of another
Anticipated Core Implementations
Developers are encouraged to add to this list and create pages that describe the detailed behavior of these agents.
RecipeReactor: A facility that consumes a fixed fresh fuel recipe one a time scale governed by reactor cycle lengths and batch sizes, and produced a fixed/corresponding spent fuel recipe at the same frequency - SeparationsMatrixFacility: A facility that consumes a fixed quantity of material of one commodity and produces many different output streams with the input nuclides distributed across those output streams according to a fixed matrix
EnrichmentFacility: A facility that offers a fixed quantity of SWUs to accomplish enrichment of material
Third-party Implementations
Collaborators are encouraged to add to this list and link to external pages that describe how to get the agents and the detailed behavior
Definition at line 71 of file facility.h.
Constructor & Destructor Documentation
cyclus::Facility::Facility (Context * ctx)
Definition at line 18 of file facility.cc.
References cyclus::Agent::kind_.
cyclus::Facility::~Facility () [virtual]
Definition at line 24 of file facility.cc.
Member Function Documentation
void cyclus::Facility::Build (Agent * parent = NULL) [virtual]
builds the facility in the simulation
Parameters:
parent the parent of this facility
Reimplemented from cyclus::Agent.
Definition at line 30 of file facility.cc.
bool cyclus::Facility::CheckDecommissionCondition () [virtual]
facilities over write this method if a condition must be met before their destructors can be called
Definition at line 57 of file facility.cc.
Referenced by Decommission(), and cyclus::Institution::Tock().
void cyclus::Facility::Decommission () [virtual]
decommissions the facility, default behavior is for the facility to delete itself
Reimplemented from cyclus::Agent.
Definition at line 47 of file facility.cc.
References CheckDecommissionCondition(), cyclus::Agent::context(), cyclus::Agent::prototype(), cyclus::Context::UnregisterTimeListener(), and cyclus::Context::UnregisterTrader().
void cyclus::Facility::DoRegistration () [virtual]
Called to give the agent an opportunity to register for services (e.g.
ticks/tocks and resource exchange). Note that this may be called more than once, and so agents should track their registrations carefully.
Reimplemented from cyclus::Agent.
Definition at line 34 of file facility.cc.
References cyclus::Agent::context(), cyclus::Context::RegisterTimeListener(), and cyclus::Context::RegisterTrader().
virtual void cyclus::Facility::InfileToDb (InfileTree * qe, DbInit di) [inline, virtual]
Translates info for a agent from an input file to the database by reading parameters from the passed InfileTree and recording data via the DbInit variable.
The simulation and agent id's are automatically injected in all data transfered through DbInit. This method must be implemented by all agents. This method must call the superclass' InfileToDb method before doing any other work.
Agent parameters in the InfileTree are scoped in the "agent/[agent-class-name]" path. The agent's class-name can be retrieved from the agent_impl method. The superclass InitFrom expects the InfileTree passed to it to be scoped identically - do NOT pass a changed-scope InfileTree to the superclass.
Example:
 class MyAgentClass : virtual public cyclus::Facility {
   // ...
   void InfileToDb(InfileTree* qe, DbInit di) {
     cyclus::Facility::InitFrom(qe); //
     // now do MyAgentClass' initialitions, e.g.:
     qe = qe->Query("agent/" + agent_impl()); // rescope the InfileTree
     // retrieve all agent params
     std::string recipe = qe->GetString("recipe");
     std::string in_commod = qe->GetString("in_commod");
     std::string out_commod = qe->GetString("out_commod");
     di.NewDatum("MyAgentTable1")
       ->AddVal("recipe", recipe)
       ->AddVal("in_commod", in_commod)
       ->AddVal("out_commod", out_commod)
       ->Record();
     // ...
   };
   // ...
 };
Warning:
this method MUST NOT modify the agent's state.
Reimplemented from cyclus::Agent.
Definition at line 78 of file facility.h.
virtual void cyclus::Facility::InitFrom (QueryableBackend * b) [inline, virtual]
Intializes an agent's internal state from an output database.
Appropriate simulation id, agent id, and time filters are automatically included in all queries.
Warning:
Agents must NOT create any resource objects in this method.
Reimplemented from cyclus::Agent.
Definition at line 81 of file facility.h.
Referenced by InitFrom().
void cyclus::Facility::InitFrom (Facility * m)
Copy module members from a source agent.
Any facility subclassing facility agent should invoke their own InitFrom method, calling Facility's first!
Parameters:
m the agent to copy from
Definition at line 26 of file facility.cc.
References InitFrom().
virtual void cyclus::Facility::Snapshot (DbInit di) [inline, virtual]
Snapshots agent-internal state to the output db via DbInit.
This method MUST call the superclass' Snapshot method before doing any work. The simulation and agent id's in addition to the snapshot time are automatically included in all information transfered through DbInit.
Warning:
because 'SimId' 'SimTime', and 'AgentId' fields are automatically injected, those labels cannot be used for any other fields.
This method MUST NOT modify the agent's state.
Implements cyclus::Agent.
Definition at line 84 of file facility.h.
std::string cyclus::Facility::str () [virtual]
every agent should be able to print a verbose description
Reimplemented from cyclus::Agent.
Definition at line 39 of file facility.cc.
References cyclus::Agent::enter_time(), and cyclus::Agent::lifetime().
The documentation for this class was generated from the following files:
facility.h
facility.cc