CYCLUS: cyclus::Env Class Reference
cyclus::Env Class Reference
An environment utility to help locate files and find environment settings.
#include <env.h>
Static Public Member Functions
static std::string CheckEnv (std::string var)
Method to check the existence of and return an environment variable.
static const std::string EnvDelimiter ()
static bool FindModuleLib (std::string name, boost::filesystem::path &path_found)
Environment searches for a library and, if found, sets the path.
static const std::string GetBuildPath ()
the relative path to the root build directory (containing bin, lib, etc.)
static std::string GetCyclusOutputPath ()
the cyclus output path
static std::string GetCyclusPath ()
the relative cyclus path
static const std::string GetInstallPath ()
the relative path to the root install directory (containing bin, lib, etc.)
static std::vector< std::string > ListModules ()
Returns names of all dynamically loadable, discoverable modules.
static const std::string module_install_path ()
Returns the default path for installed cyclus simulation agent modules.
static const std::string ModuleEnvVar ()
static const std::string ModuleEnvVarName ()
static std::string PathBase (std::string path)
the path basis
static const std::string PathDelimiter ()
static void SetCyclusOutputPath (std::string path)
Allows the user to set the cyclus output path.
static void SetCyclusRelPath (std::string path)
Allows configuration and other files to be located independent of the working directory from which cyclus is executed.
static const void SetNucDataPath ()
Initializes the path to the nuclear data library to a default location.
static const void SetNucDataPath (std::string p)
Initializes the path to the nuclear data library to p.
Static Private Member Functions
static bool FindFile (const boost::filesystem::path &dir_path, const std::string &file_name, boost::filesystem::path &path_found)
Taken directly from http://www.boost.org/doc/libs/1_31_0/libs/filesystem/doc/index.htm.
Static Private Attributes
static boost::filesystem::path cwd_ = fs::current_path()
the cwd path
static boost::filesystem::path path_from_cwd_to_cyclus_
the relative path from cwd to cyclus
static boost::filesystem::path path_to_output_dir_
the cwd path
Detailed Description
An environment utility to help locate files and find environment settings.
The environment for a given simulation can be accessed via the simulation's Context.
Definition at line 16 of file env.h.
Member Function Documentation
std::string cyclus::Env::CheckEnv (std::string var) [static]
Method to check the existence of and return an environment variable.
Parameters:
var is the variable to check and return
Definition at line 71 of file env.cc.
const std::string cyclus::Env::EnvDelimiter () [static]
Returns:
the correct environment variable delimiter based on the file system
Definition at line 80 of file env.cc.
Referenced by FindModuleLib(), and ListModules().
bool cyclus::Env::FindFile (const boost::filesystem::path & dir_path, const std::string & file_name, boost::filesystem::path & path_found) [static, private]
Taken directly from http://www.boost.org/doc/libs/1_31_0/libs/filesystem/doc/index.htm.
This function recursively searches a directory and its sub-directories for the file name, returning a bool, and if successful, the path to the file that was found.
Parameters:
dir_path the directory path to search
file_name the file to search for
path_found the path, which is populated if the file is found
Returns:
true if the file is found, false if it isn't
Definition at line 166 of file env.cc.
Referenced by FindModuleLib().
bool cyclus::Env::FindModuleLib (std::string name, boost::filesystem::path & path_found) [static]
Environment searches for a library and, if found, sets the path.
The search occurs across the default install location as well as any included in the CYCLUS_MODULE_PATH environment variable.
Parameters:
name the name of the library to search for
path_found the variable to set with the path to the library
Returns:
true if the library is found, false if not
Definition at line 143 of file env.cc.
References EnvDelimiter(), FindFile(), module_install_path(), ModuleEnvVar(), and cyclus::split().
Referenced by cyclus::DynamicModule::DynamicModule().
const std::string cyclus::Env::GetBuildPath () [static]
the relative path to the root build directory (containing bin, lib, etc.)
Returns:
the absolute path to the build directory
Definition at line 58 of file env.cc.
Referenced by SetNucDataPath().
static std::string cyclus::Env::GetCyclusOutputPath () [static]
the cyclus output path
Returns:
the full path to the directory of the cyclus output
std::string cyclus::Env::GetCyclusPath () [static]
the relative cyclus path
Returns:
the relative path from the cwd to the cyclus executable
Definition at line 37 of file env.cc.
References CLOG, cwd_, cyclus::LEV_DEBUG4, and path_from_cwd_to_cyclus_.
const std::string cyclus::Env::GetInstallPath () [static]
the relative path to the root install directory (containing bin, lib, etc.)
Returns:
the absolute path to the build directory
Definition at line 51 of file env.cc.
Referenced by module_install_path().
std::vector< std::string > cyclus::Env::ListModules () [static]
Returns names of all dynamically loadable, discoverable modules.
Returned lists includes modules installed in the default location (module_install_path) as well as modules in directories listed in the CYCLUS_MODULE_PATH environment variable.
Returns:
module names without the "lib" prefix or file extension. Equivalent to the module class name (e.g. SourceFacility).
Definition at line 112 of file env.cc.
References EnvDelimiter(), module_install_path(), ModuleEnvVar(), cyclus::split(), and SUFFIX.
Referenced by cyclus::BuildFlatMasterSchema(), and cyclus::BuildMasterSchema().
static const std::string cyclus::Env::module_install_path () [inline, static]
Returns the default path for installed cyclus simulation agent modules.
Definition at line 36 of file env.h.
References GetInstallPath().
Referenced by FindModuleLib(), and ListModules().
const std::string cyclus::Env::ModuleEnvVar () [static]
Returns:
the current value of the module environment variable
Definition at line 103 of file env.cc.
References ModuleEnvVarName().
Referenced by FindModuleLib(), and ListModules().
const std::string cyclus::Env::ModuleEnvVarName () [static]
Returns:
the name of the environment variable used for module installations, currently set to CYCLUS_MODULE_PATH
Definition at line 98 of file env.cc.
Referenced by ModuleEnvVar().
std::string cyclus::Env::PathBase (std::string path) [static]
the path basis
Returns:
path with the last item removed
Definition at line 27 of file env.cc.
const std::string cyclus::Env::PathDelimiter () [static]
Returns:
the correct path delimiter based on the file system
Definition at line 89 of file env.cc.
static void cyclus::Env::SetCyclusOutputPath (std::string path) [static]
Allows the user to set the cyclus output path.
Parameters:
path this should be an argument flagged -o as passed to the main function (i.e. the relative path from the cwd to the desired output directory)
void cyclus::Env::SetCyclusRelPath (std::string path) [static]
Allows configuration and other files to be located independent of the working directory from which cyclus is executed.
Parameters:
path this should be argv[0] as passed to the main function (i.e. the relative path from the cwd to cyclus including the name of the cyclus executable)
Definition at line 65 of file env.cc.
References CLOG, cyclus::LEV_DEBUG3, and path_from_cwd_to_cyclus_.
static const void cyclus::Env::SetNucDataPath () [inline, static]
Initializes the path to the nuclear data library to a default location.
Definition at line 94 of file env.h.
References GetBuildPath().
static const void cyclus::Env::SetNucDataPath (std::string p) [inline, static]
Initializes the path to the nuclear data library to p.
Definition at line 99 of file env.h.
Member Data Documentation
fs::path cyclus::Env::cwd_ = fs::current_path() [static, private]
the cwd path
Definition at line 108 of file env.h.
Referenced by GetCyclusPath().
fs::path cyclus::Env::path_from_cwd_to_cyclus_ [static, private]
the relative path from cwd to cyclus
Definition at line 105 of file env.h.
Referenced by GetCyclusPath(), and SetCyclusRelPath().
boost::filesystem::path cyclus::Env::path_to_output_dir_ [static, private]
the cwd path
Definition at line 111 of file env.h.
The documentation for this class was generated from the following files:
env.h
env.cc