CYCLUS: cyclus::ProgTranslator Class Reference
cyclus::ProgTranslator Class Reference
a helper class to translate a product exchange into a mathematical program.
#include <prog_translator.h>
Classes
struct Context
struct to hold all problem instance state
Public Member Functions
const ProgTranslator::Context & ctx () const
void FromProg ()
translates solution from iface back into graph matches
void Populate ()
populates the solver interface with values from the translators Context
ProgTranslator (ExchangeGraph *g, OsiSolverInterface *iface, bool exclusive=false)
constructor
void ToProg ()
translates graph into mathematic program via iface.
void Translate ()
translates the graph, filling the translators Context
Private Member Functions
void XlateGrp_ (ExchangeNodeGroup *grp, bool req)
perform all translation for a node group
Private Attributes
int arc_offset_
int cost_add_
ProgTranslator::Context ctx_
bool excl_
ExchangeGraph * g_
OsiSolverInterface * iface_
double max_obj_coeff_
double min_row_coeff_
Detailed Description
a helper class to translate a product exchange into a mathematical program.
use as follows:
 // given a graph, g, and interface, iface
 ProgTranslator t(g, iface);
 t->ToProg();
 // solve the program via the interface
 t->FromProg();
Definition at line 26 of file prog_translator.h.
Constructor & Destructor Documentation
cyclus::ProgTranslator::ProgTranslator (ExchangeGraph * g, OsiSolverInterface * iface, bool exclusive = false)
constructor
Parameters:
g the exchange graph
iface the solver interface
exclusive whether or not to include binary-valued arcs
Definition at line 14 of file prog_translator.cc.
References arc_offset_, cyclus::ExchangeGraph::arcs(), cyclus::ProgTranslator::Context::col_lbs, cyclus::ProgTranslator::Context::col_ubs, cost_add_, ctx_, g_, cyclus::ProgTranslator::Context::m, max_obj_coeff_, min_row_coeff_, cyclus::ProgTranslator::Context::obj_coeffs, and cyclus::ExchangeGraph::request_groups().
Member Function Documentation
const ProgTranslator::Context& cyclus::ProgTranslator::ctx () const [inline]
Definition at line 60 of file prog_translator.h.
References ctx_.
void cyclus::ProgTranslator::FromProg ()
translates solution from iface back into graph matches
Definition at line 168 of file prog_translator.cc.
References cyclus::ExchangeGraph::AddMatch(), cyclus::ExchangeGraph::arc_by_id(), cyclus::ExchangeGraph::arcs(), cyclus::eps(), cyclus::Arc::excl_val, cyclus::Arc::exclusive, g_, and iface_.
Referenced by cyclus::ProgSolver::Solve().
void cyclus::ProgTranslator::Populate ()
populates the solver interface with values from the translators Context
Definition at line 58 of file prog_translator.cc.
References cyclus::ExchangeGraph::arc_ids(), cyclus::ExchangeGraph::arcs(), cyclus::ProgTranslator::Context::col_lbs, cyclus::ProgTranslator::Context::col_ubs, ctx_, excl_, cyclus::Arc::exclusive, g_, iface_, cyclus::ProgTranslator::Context::m, cyclus::ProgTranslator::Context::obj_coeffs, cyclus::ProgTranslator::Context::row_lbs, and cyclus::ProgTranslator::Context::row_ubs.
Referenced by ToProg().
void cyclus::ProgTranslator::ToProg ()
translates graph into mathematic program via iface.
This method is equivalent to calling Translate(), then Populate().
Definition at line 77 of file prog_translator.cc.
References Populate(), and Translate().
Referenced by cyclus::ProgSolver::Solve().
void cyclus::ProgTranslator::Translate ()
translates the graph, filling the translators Context
Definition at line 29 of file prog_translator.cc.
References arc_offset_, cyclus::ExchangeGraph::arcs(), cyclus::ProgTranslator::Context::col_lbs, cyclus::ProgTranslator::Context::col_ubs, cost_add_, ctx_, g_, iface_, cyclus::ProgTranslator::Context::m, max_obj_coeff_, min_row_coeff_, cyclus::ProgTranslator::Context::obj_coeffs, cyclus::ExchangeGraph::request_groups(), cyclus::ExchangeGraph::supply_groups(), and XlateGrp_().
Referenced by ToProg().
void cyclus::ProgTranslator::XlateGrp_ (ExchangeNodeGroup * grp, bool req) [private]
perform all translation for a node group
Parameters:
grp a pointer to the node group
req a boolean flag, true if grp is a request group
Definition at line 83 of file prog_translator.cc.
References cyclus::ExchangeGraph::arc_ids(), arc_offset_, cyclus::ExchangeNodeGroup::capacities(), cyclus::ProgTranslator::Context::col_lbs, cyclus::ProgTranslator::Context::col_ubs, ctx_, excl_, cyclus::Arc::excl_val, cyclus::Arc::exclusive, cyclus::Arc::first, g_, iface_, cyclus::ProgTranslator::Context::m, max_obj_coeff_, min_row_coeff_, cyclus::ExchangeNodeGroup::nodes(), cyclus::ProgTranslator::Context::obj_coeffs, cyclus::ProgTranslator::Context::row_lbs, and cyclus::ProgTranslator::Context::row_ubs.
Referenced by Translate().
Member Data Documentation
int cyclus::ProgTranslator::arc_offset_ [private]
Definition at line 71 of file prog_translator.h.
Referenced by ProgTranslator(), Translate(), and XlateGrp_().
int cyclus::ProgTranslator::cost_add_ [private]
Definition at line 75 of file prog_translator.h.
Referenced by ProgTranslator(), and Translate().
ProgTranslator::Context cyclus::ProgTranslator::ctx_ [private]
Definition at line 72 of file prog_translator.h.
Referenced by ctx(), Populate(), ProgTranslator(), Translate(), and XlateGrp_().
bool cyclus::ProgTranslator::excl_ [private]
Definition at line 70 of file prog_translator.h.
Referenced by Populate(), and XlateGrp_().
ExchangeGraph* cyclus::ProgTranslator::g_ [private]
Definition at line 68 of file prog_translator.h.
Referenced by FromProg(), Populate(), ProgTranslator(), Translate(), and XlateGrp_().
OsiSolverInterface* cyclus::ProgTranslator::iface_ [private]
Definition at line 69 of file prog_translator.h.
Referenced by FromProg(), Populate(), Translate(), and XlateGrp_().
double cyclus::ProgTranslator::max_obj_coeff_ [private]
Definition at line 73 of file prog_translator.h.
Referenced by ProgTranslator(), Translate(), and XlateGrp_().
double cyclus::ProgTranslator::min_row_coeff_ [private]
Definition at line 74 of file prog_translator.h.
Referenced by ProgTranslator(), Translate(), and XlateGrp_().
The documentation for this class was generated from the following files:
prog_translator.h
prog_translator.cc