CYCLUS: cyclus::ResTracker Class Reference
cyclus::ResTracker Class Reference
Tracks and records the state and parent-child relationships of resources as they are changed.
#include <res_tracker.h>
Public Member Functions
void Absorb (ResTracker *absorbed)
Should be called when a resource is combined with another.
void Create (Agent *creator)
Should be called when a resource instance is newly created.
void DontTrack ()
Prevent a resource's heritage from being tracked and recorded.
void Extract (ResTracker *removed)
Should be called when a resource has some quantity removed from it (e.g.
void Modify ()
Should be called when the state of a resource changes (e.g.
ResTracker (Context *ctx, Resource *r)
Create a new tracker following r.
Private Member Functions
void Record ()
Private Attributes
Context * ctx_
int parent1_
int parent2_
Resource * res_
bool tracked_
Detailed Description
Tracks and records the state and parent-child relationships of resources as they are changed.
Resource implementations embed this as a member variable and invoke its methods appropriately to have their state changes tracked in the canonical core resource table.
Invocations to Create, Extract, Absorb, and Modify result in one or more entries in the output db Resource table and also call the Record method of the tracker's tracked resource. A zero parent id indicates a resource id has no parent; if both are zeros the resource was newly created.
Definition at line 22 of file res_tracker.h.
Constructor & Destructor Documentation
cyclus::ResTracker::ResTracker (Context * ctx, Resource * r)
Create a new tracker following r.
Definition at line 8 of file res_tracker.cc.
Member Function Documentation
void cyclus::ResTracker::Absorb (ResTracker * absorbed)
Should be called when a resource is combined with another.
Parameters:
absorbed the tracker of the resource being absorbed.
Definition at line 58 of file res_tracker.cc.
References cyclus::Resource::id(), parent1_, parent2_, Record(), res_, and tracked_.
Referenced by cyclus::Product::Absorb(), and cyclus::Material::Absorb().
void cyclus::ResTracker::Create (Agent * creator)
Should be called when a resource instance is newly created.
Definition at line 19 of file res_tracker.cc.
References cyclus::Datum::AddVal(), ctx_, cyclus::Resource::id(), cyclus::Agent::id(), cyclus::Context::NewDatum(), parent1_, parent2_, Record(), res_, and tracked_.
void cyclus::ResTracker::DontTrack ()
Prevent a resource's heritage from being tracked and recorded.
Definition at line 15 of file res_tracker.cc.
References tracked_.
Referenced by cyclus::Product::Clone(), cyclus::Material::Clone(), and cyclus::Material::Material().
void cyclus::ResTracker::Extract (ResTracker * removed)
Should be called when a resource has some quantity removed from it (e.g.
resource is split).
Parameters:
removed the tracker of the extracted/removed resource.
Definition at line 43 of file res_tracker.cc.
References cyclus::Resource::id(), parent1_, parent2_, Record(), res_, and tracked_.
Referenced by cyclus::Product::Extract(), and cyclus::Material::ExtractComp().
void cyclus::ResTracker::Modify ()
Should be called when the state of a resource changes (e.g.
radioactive decay).
Definition at line 33 of file res_tracker.cc.
References cyclus::Resource::id(), parent1_, parent2_, Record(), res_, and tracked_.
Referenced by cyclus::Material::Transmute().
void cyclus::ResTracker::Record () [private]
Definition at line 68 of file res_tracker.cc.
References cyclus::Datum::AddVal(), cyclus::Resource::BumpId(), ctx_, cyclus::Resource::id(), cyclus::Context::NewDatum(), parent1_, parent2_, cyclus::Resource::quantity(), cyclus::Datum::Record(), cyclus::Resource::Record(), res_, cyclus::Resource::state_id(), cyclus::Context::time(), cyclus::Resource::type(), and cyclus::Resource::units().
Referenced by Absorb(), Create(), Extract(), and Modify().
Member Data Documentation
Context* cyclus::ResTracker::ctx_ [private]
Definition at line 53 of file res_tracker.h.
Referenced by Create(), and Record().
int cyclus::ResTracker::parent1_ [private]
Definition at line 49 of file res_tracker.h.
Referenced by Absorb(), Create(), Extract(), Modify(), and Record().
int cyclus::ResTracker::parent2_ [private]
Definition at line 50 of file res_tracker.h.
Referenced by Absorb(), Create(), Extract(), Modify(), and Record().
Resource* cyclus::ResTracker::res_ [private]
Definition at line 52 of file res_tracker.h.
Referenced by Absorb(), Create(), Extract(), Modify(), and Record().
bool cyclus::ResTracker::tracked_ [private]
Definition at line 51 of file res_tracker.h.
Referenced by Absorb(), Create(), DontTrack(), Extract(), and Modify().
The documentation for this class was generated from the following files:
res_tracker.h
res_tracker.cc