CYCLUS: cyclus::RequestPortfolio< T > Class Template Reference
cyclus::RequestPortfolio< T > Class Template Reference
A RequestPortfolio is a group of (possibly constrainted) requests for resources.
#include <request_portfolio.h>
Public Types
typedef boost::shared_ptr
< RequestPortfolio< T > > Ptr
Public Member Functions
void AddConstraint (const CapacityConstraint< T > &c)
add a capacity constraint associated with the portfolio, if it doesn't already exist
Request< T >::Ptr AddRequest (boost::shared_ptr< T > target, Trader *requester, std::string commodity="", double preference=0, bool exclusive=false)
add a request to the portfolio
const std::set
< CapacityConstraint< T > > & constraints () const
double qty () const
, all requests in a portfolio must have the same quantity, which is checked during AddRequest()
Trader * requester () const
RequestPortfolio ()
default constructor
const std::vector< typename
Request< T >::Ptr > & requests () const
Private Member Functions
RequestPortfolio (const RequestPortfolio &rhs)
copy constructor is private to prevent copying and preserve explicit single-ownership of requests
void VerifyQty_ (const typename Request< T >::Ptr r)
if the quantity has not been determined yet, it is set.
void VerifyRequester_ (const typename Request< T >::Ptr r)
if the requester has not been determined yet, it is set.
Private Attributes
std::set< CapacityConstraint< T > > constraints_
constraints_ is a set because constraints are assumed to be unique
double qty_
Trader * requester_
std::vector< typename Request
< T >::Ptr > requests_
requests_ is a vector because many requests may be identical, i.e., a set is not appropriate
Detailed Description
template<class T>
class cyclus::RequestPortfolio< T >
A RequestPortfolio is a group of (possibly constrainted) requests for resources.
The portfolio contains a grouping of resource requests that may be mutually met by suppliers. These requests may share a common set of constraints. Take, for instance, a facility that needs fuel, of which there are two commodity types, fuelA and fuelB. If some combination of the two suffice the facility's needs, then requests for both would be added to the portfolio along with a capacity constraint.
revise the request portfolio API/underlying data structures to allow exclusive constraints. Perhaps the easiest option would be to allow the AddRequest interface have an option boolean for exclusivity. This utility needs to be used first to determine what the appropriate way forward is.
Definition at line 37 of file request_portfolio.h.
Member Typedef Documentation
template<class T> typedef boost::shared_ptr< RequestPortfolio<T> > cyclus::RequestPortfolio< T >::Ptr
Definition at line 40 of file request_portfolio.h.
Constructor & Destructor Documentation
template<class T> cyclus::RequestPortfolio< T >::RequestPortfolio () [inline]
default constructor
Definition at line 43 of file request_portfolio.h.
template<class T> cyclus::RequestPortfolio< T >::RequestPortfolio (const RequestPortfolio< T > & rhs) [inline, private]
copy constructor is private to prevent copying and preserve explicit single-ownership of requests
Definition at line 99 of file request_portfolio.h.
References cyclus::RequestPortfolio< T >::constraints_, cyclus::RequestPortfolio< T >::qty_, cyclus::RequestPortfolio< T >::requester_, and cyclus::RequestPortfolio< T >::requests_.
Member Function Documentation
template<class T> void cyclus::RequestPortfolio< T >::AddConstraint (const CapacityConstraint< T > & c) [inline]
add a capacity constraint associated with the portfolio, if it doesn't already exist
Parameters:
c the constraint to add
Definition at line 72 of file request_portfolio.h.
References cyclus::RequestPortfolio< T >::constraints_.
template<class T> Request<T>::Ptr cyclus::RequestPortfolio< T >::AddRequest (boost::shared_ptr< T > target, Trader * requester, std::string commodity = "", double preference = 0, bool exclusive = false) [inline]
add a request to the portfolio
Parameters:
target the target resource associated with this request
requester the requester
commodity the commodity associated with this request
preference the preference associated with this request (relative to others in the portfolio)
exclusive a flag denoting that this request must be met exclusively, i.e., in its entirety by a single offer
Exceptions:
KeyError if a request is added from a different requester than the original or if the request quantity is different than the original
Definition at line 55 of file request_portfolio.h.
References cyclus::RequestPortfolio< T >::requests_, cyclus::RequestPortfolio< T >::VerifyQty_(), and cyclus::RequestPortfolio< T >::VerifyRequester_().
template<class T> const std::set< CapacityConstraint<T> >& cyclus::RequestPortfolio< T >::constraints () const [inline]
Returns:
const access to the request constraints
Definition at line 92 of file request_portfolio.h.
References cyclus::RequestPortfolio< T >::constraints_.
Referenced by cyclus::TranslateArc(), and cyclus::TranslateRequestPortfolio().
template<class T> double cyclus::RequestPortfolio< T >::qty () const [inline]
, all requests in a portfolio must have the same quantity, which is checked during AddRequest()
Returns:
the request quantity associated with the portfolio.
Definition at line 84 of file request_portfolio.h.
References cyclus::RequestPortfolio< T >::qty_.
Referenced by cyclus::TranslateRequestPortfolio(), and cyclus::RequestPortfolio< T >::VerifyQty_().
template<class T> Trader* cyclus::RequestPortfolio< T >::requester () const [inline]
Returns:
the agent associated with the portfolio. if no reqeusts have been added, the requester is NULL.
Definition at line 78 of file request_portfolio.h.
References cyclus::RequestPortfolio< T >::requester_.
template<class T> const std::vector<typename Request<T>::Ptr>& cyclus::RequestPortfolio< T >::requests () const [inline]
Returns:
const access to the unconstrained requests
Definition at line 87 of file request_portfolio.h.
References cyclus::RequestPortfolio< T >::requests_.
Referenced by cyclus::ExchangeContext< T >::AddRequestPortfolio(), and cyclus::TranslateRequestPortfolio().
template<class T> void cyclus::RequestPortfolio< T >::VerifyQty_ (const typename Request< T >::Ptr r) [inline, private]
if the quantity has not been determined yet, it is set.
otherwise VerifyRequester() verifies the the quantity is the same as all others in the portfolio
Exceptions:
KeyError if a quantity is different than the original
Definition at line 128 of file request_portfolio.h.
References cyclus::RequestPortfolio< T >::qty(), cyclus::RequestPortfolio< T >::qty_, and cyclus::Request< T >::target().
Referenced by cyclus::RequestPortfolio< T >::AddRequest().
template<class T> void cyclus::RequestPortfolio< T >::VerifyRequester_ (const typename Request< T >::Ptr r) [inline, private]
if the requester has not been determined yet, it is set.
otherwise VerifyRequester() verifies the the request is associated with the portfolio's requester
Exceptions:
KeyError if a request is added from a different requester than the original
Definition at line 115 of file request_portfolio.h.
References cyclus::Request< T >::requester(), and cyclus::RequestPortfolio< T >::requester_.
Referenced by cyclus::RequestPortfolio< T >::AddRequest().
Member Data Documentation
template<class T> std::set< CapacityConstraint<T> > cyclus::RequestPortfolio< T >::constraints_ [private]
constraints_ is a set because constraints are assumed to be unique
Definition at line 143 of file request_portfolio.h.
Referenced by cyclus::RequestPortfolio< T >::AddConstraint(), cyclus::RequestPortfolio< T >::constraints(), and cyclus::RequestPortfolio< T >::RequestPortfolio().
template<class T> double cyclus::RequestPortfolio< T >::qty_ [private]
Definition at line 145 of file request_portfolio.h.
Referenced by cyclus::RequestPortfolio< T >::qty(), cyclus::RequestPortfolio< T >::RequestPortfolio(), and cyclus::RequestPortfolio< T >::VerifyQty_().
template<class T> Trader* cyclus::RequestPortfolio< T >::requester_ [private]
Definition at line 146 of file request_portfolio.h.
Referenced by cyclus::RequestPortfolio< T >::requester(), cyclus::RequestPortfolio< T >::RequestPortfolio(), and cyclus::RequestPortfolio< T >::VerifyRequester_().
template<class T> std::vector<typename Request<T>::Ptr> cyclus::RequestPortfolio< T >::requests_ [private]
requests_ is a vector because many requests may be identical, i.e., a set is not appropriate
Definition at line 136 of file request_portfolio.h.
Referenced by cyclus::RequestPortfolio< T >::AddRequest(), cyclus::RequestPortfolio< T >::RequestPortfolio(), and cyclus::RequestPortfolio< T >::requests().
The documentation for this class was generated from the following file:
request_portfolio.h