CYCLUS: cyclus::Producer Class Reference
cyclus::Producer Class Reference
a small class defining a producer a producer is associated with: a commodity a capactiy for production of commodity a cost of production of commodity
#include <supply_demand.h>
Public Member Functions
double capacity () const
capacity getter
Commodity commodity () const
commodity getter
double cost () const
cost getter
std::string name () const
name getter
bool operator== (const Producer &other) const
equality operator
Producer (std::string name, Commodity p, double capacity, double cost)
constructor, sets name, commodity, capacity, and cost
Private Attributes
double capacity_
commodityion capcity
Commodity commodity_
commodity
std::string name_
name
double production_cost_
production cost
Detailed Description
a small class defining a producer a producer is associated with: a commodity a capactiy for production of commodity a cost of production of commodity
Definition at line 19 of file supply_demand.h.
Constructor & Destructor Documentation
cyclus::Producer::Producer (std::string name, Commodity p, double capacity, double cost) [inline]
constructor, sets name, commodity, capacity, and cost
Definition at line 24 of file supply_demand.h.
Member Function Documentation
double cyclus::Producer::capacity () const [inline]
capacity getter
Definition at line 38 of file supply_demand.h.
References capacity_.
Referenced by operator==().
Commodity cyclus::Producer::commodity () const [inline]
commodity getter
Definition at line 33 of file supply_demand.h.
References commodity_.
Referenced by operator==().
double cyclus::Producer::cost () const [inline]
cost getter
Definition at line 43 of file supply_demand.h.
References production_cost_.
Referenced by operator==().
std::string cyclus::Producer::name () const [inline]
name getter
Definition at line 28 of file supply_demand.h.
References name_.
Referenced by operator==().
bool cyclus::Producer::operator== (const Producer & other) const [inline]
equality operator
Definition at line 48 of file supply_demand.h.
References capacity(), capacity_, commodity(), commodity_, cost(), name(), name_, and production_cost_.
Member Data Documentation
double cyclus::Producer::capacity_ [private]
commodityion capcity
Definition at line 65 of file supply_demand.h.
Referenced by capacity(), and operator==().
Commodity cyclus::Producer::commodity_ [private]
commodity
Definition at line 62 of file supply_demand.h.
Referenced by commodity(), and operator==().
std::string cyclus::Producer::name_ [private]
name
Definition at line 59 of file supply_demand.h.
Referenced by name(), and operator==().
double cyclus::Producer::production_cost_ [private]
production cost
Definition at line 68 of file supply_demand.h.
Referenced by cost(), and operator==().
The documentation for this class was generated from the following file:
supply_demand.h