CYCLUS: cyclus::CsvBack Class Reference
cyclus::CsvBack Class Reference
An Recorder backend that writes data to a collection of csv files.
#include <csv_back.h>
Public Member Functions
CsvBack (std::string path, bool overwrite=false)
Creates a new csv backend that will write to a set of csv files in path.
void Flush ()
Writes any remaining csv lines to files.
std::string Name ()
Used to uniquely identify a backend - particularly if there are more than one in a simulation.
void Notify (DatumList data)
Collects Datum objects to be written to csv files.
virtual ~CsvBack ()
Protected Attributes
std::map< std::string, LineList > file_data_
maps filenames to pending csv lines
Private Member Functions
std::string ValAsString (boost::spirit::hold_any &v)
converts the value to a valid csv value string.
void WriteDatum (Datum *d)
constructs a valid csv line for the datum and queues it for writing
Private Attributes
boost::filesystem::path path_
Stores the database's path, declared during construction.
Detailed Description
An Recorder backend that writes data to a collection of csv files.
Identically named Datum objects have their data placed in the same file. Handles the following datum value types: int, float, double, std::string, cyclus::Blob.
Definition at line 21 of file csv_back.h.
Constructor & Destructor Documentation
cyclus::CsvBack::CsvBack (std::string path, bool overwrite = false)
Creates a new csv backend that will write to a set of csv files in path.
Parameters:
path directory to place csv file into
overwrite true to overwrite existing csv files with same path/name.
Definition at line 21 of file csv_back.cc.
cyclus::CsvBack::~CsvBack () [virtual]
Definition at line 28 of file csv_back.cc.
References CLOG, Flush(), and cyclus::LEV_ERROR.
Member Function Documentation
void cyclus::CsvBack::Flush () [virtual]
Writes any remaining csv lines to files.
Implements cyclus::RecBackend.
Definition at line 45 of file csv_back.cc.
References file_data_.
Referenced by Notify(), and ~CsvBack().
std::string cyclus::CsvBack::Name () [virtual]
Used to uniquely identify a backend - particularly if there are more than one in a simulation.
Implements cyclus::RecBackend.
Definition at line 61 of file csv_back.cc.
References path_.
Referenced by ValAsString().
void cyclus::CsvBack::Notify (DatumList data) [virtual]
Collects Datum objects to be written to csv files.
Parameters:
data group of Datum objects to write to the csv file collection.
Implements cyclus::RecBackend.
Definition at line 37 of file csv_back.cc.
References Flush(), and WriteDatum().
std::string cyclus::CsvBack::ValAsString (boost::spirit::hold_any & v) [private]
converts the value to a valid csv value string.
Definition at line 102 of file csv_back.cc.
References boost::spirit::basic_hold_any< Char >::cast(), CLOG, cyclus::LEV_ERROR, Name(), path_, and boost::spirit::basic_hold_any< Char >::type().
Referenced by WriteDatum().
void cyclus::CsvBack::WriteDatum (Datum * d) [private]
constructs a valid csv line for the datum and queues it for writing
Definition at line 66 of file csv_back.cc.
References file_data_, path_, cyclus::Datum::title(), ValAsString(), and cyclus::Datum::vals().
Referenced by Notify().
Member Data Documentation
std::map<std::string, LineList> cyclus::CsvBack::file_data_ [protected]
maps filenames to pending csv lines
Definition at line 41 of file csv_back.h.
Referenced by Flush(), and WriteDatum().
boost::filesystem::path cyclus::CsvBack::path_ [private]
Stores the database's path, declared during construction.
Definition at line 51 of file csv_back.h.
Referenced by Name(), ValAsString(), and WriteDatum().
The documentation for this class was generated from the following files:
csv_back.h
csv_back.cc