CYCLUS: cyclus::Bid< T > Class Template Reference
cyclus::Bid< T > Class Template Reference
A Bid encapsulates all the information required to communicate a bid response to a request for a resource, including the resource bid and the bidder.
#include <bid.h>
Public Types
typedef boost::shared_ptr< Bid
< T > > Ptr
Public Member Functions
Trader * bidder () const
bool exclusive () const
boost::shared_ptr< T > offer () const
BidPortfolio< T >::Ptr portfolio ()
Request< T >::Ptr request () const
Static Public Member Functions
static Bid< T >::Ptr Create (typename Request< T >::Ptr request, boost::shared_ptr< T > offer, Trader *bidder, typename BidPortfolio< T >::Ptr portfolio, bool exclusive=false)
a factory method for a bid
static Bid< T >::Ptr Create (typename Request< T >::Ptr request, boost::shared_ptr< T > offer, Trader *bidder, bool exclusive=false)
a factory method for a bid for a bid without a portfolio
Private Member Functions
Bid (typename Request< T >::Ptr request, boost::shared_ptr< T > offer, Trader *bidder, bool exclusive=false)
constructors are private to require use of factory methods
Bid (typename Request< T >::Ptr request, boost::shared_ptr< T > offer, Trader *bidder, typename BidPortfolio< T >::Ptr portfolio, bool exclusive=false)
Private Attributes
Trader * bidder_
bool exclusive_
boost::shared_ptr< T > offer_
BidPortfolio< T >::Ptr portfolio_
Request< T >::Ptr request_
Detailed Description
template<class T>
class cyclus::Bid< T >
A Bid encapsulates all the information required to communicate a bid response to a request for a resource, including the resource bid and the bidder.
Definition at line 19 of file bid.h.
Member Typedef Documentation
template<class T> typedef boost::shared_ptr< Bid<T> > cyclus::Bid< T >::Ptr
Definition at line 21 of file bid.h.
Constructor & Destructor Documentation
template<class T> cyclus::Bid< T >::Bid (typename Request< T >::Ptr request, boost::shared_ptr< T > offer, Trader * bidder, bool exclusive = false) [inline, private]
constructors are private to require use of factory methods
Definition at line 73 of file bid.h.
template<class T> cyclus::Bid< T >::Bid (typename Request< T >::Ptr request, boost::shared_ptr< T > offer, Trader * bidder, typename BidPortfolio< T >::Ptr portfolio, bool exclusive = false) [inline, private]
Definition at line 82 of file bid.h.
Member Function Documentation
template<class T> Trader* cyclus::Bid< T >::bidder () const [inline]
Returns:
the agent responding the request
Definition at line 57 of file bid.h.
References cyclus::Bid< T >::bidder_.
Referenced by cyclus::ExchangeContext< T >::AddBid(), and cyclus::BidPortfolio< T >::VerifyResponder_().
template<class T> static Bid<T>::Ptr cyclus::Bid< T >::Create (typename Request< T >::Ptr request, boost::shared_ptr< T > offer, Trader * bidder, typename BidPortfolio< T >::Ptr portfolio, bool exclusive = false) [inline, static]
a factory method for a bid
Parameters:
request the request being responded to by this bid
offer the resource being offered in response to the request
bidder the bidder
portfolio the porftolio of which this bid is a part
Definition at line 28 of file bid.h.
References cyclus::Bid< T >::exclusive().
template<class T> static Bid<T>::Ptr cyclus::Bid< T >::Create (typename Request< T >::Ptr request, boost::shared_ptr< T > offer, Trader * bidder, bool exclusive = false) [inline, static]
a factory method for a bid for a bid without a portfolio
Warning:
this factory should generally only be used for testing
Definition at line 39 of file bid.h.
References cyclus::Bid< T >::exclusive().
template<class T> bool cyclus::Bid< T >::exclusive () const [inline]
Returns:
whether or not this an exclusive bid
Definition at line 67 of file bid.h.
References cyclus::Bid< T >::exclusive_.
Referenced by cyclus::Bid< T >::Create(), and cyclus::ExclusiveStatus< T >::ExclusiveStatus().
template<class T> boost::shared_ptr<T> cyclus::Bid< T >::offer () const [inline]
Returns:
the bid object for the request
Definition at line 52 of file bid.h.
References cyclus::Bid< T >::offer_.
Referenced by cyclus::ExclusiveStatus< T >::ExclusiveStatus(), and cyclus::TranslateArc().
template<class T> BidPortfolio<T>::Ptr cyclus::Bid< T >::portfolio () [inline]
Returns:
the portfolio of which this bid is a part
Definition at line 62 of file bid.h.
References cyclus::Bid< T >::portfolio_.
Referenced by cyclus::TranslateArc().
template<class T> Request<T>::Ptr cyclus::Bid< T >::request () const [inline]
Returns:
the request being responded to
Definition at line 47 of file bid.h.
References cyclus::Bid< T >::request_.
Referenced by cyclus::ExchangeContext< T >::AddBid(), cyclus::ExchangeTranslator< T >::Translate(), cyclus::TranslateArc(), and cyclus::BidPortfolio< T >::VerifyCommodity_().
Member Data Documentation
template<class T> Trader* cyclus::Bid< T >::bidder_ [private]
Definition at line 95 of file bid.h.
Referenced by cyclus::Bid< T >::bidder().
template<class T> bool cyclus::Bid< T >::exclusive_ [private]
Definition at line 97 of file bid.h.
Referenced by cyclus::Bid< T >::exclusive().
template<class T> boost::shared_ptr<T> cyclus::Bid< T >::offer_ [private]
Definition at line 94 of file bid.h.
Referenced by cyclus::Bid< T >::offer().
template<class T> BidPortfolio<T>::Ptr cyclus::Bid< T >::portfolio_ [private]
Definition at line 96 of file bid.h.
Referenced by cyclus::Bid< T >::portfolio().
template<class T> Request<T>::Ptr cyclus::Bid< T >::request_ [private]
Definition at line 93 of file bid.h.
Referenced by cyclus::Bid< T >::request().
The documentation for this class was generated from the following file:
bid.h