CYCLUS: cyclus::Region Class Reference
cyclus::Region Class Reference
The Region class is the abstract class/interface used by all region agents.
#include <region.h>
Public Member Functions
virtual void Build (Agent *parent)
perform actions required when entering the simulation
virtual void Decommission ()
Decommissions the agent, removing it from the simulation.
virtual void DoRegistration ()
Called to give the agent an opportunity to register for services (e.g.
virtual void InfileToDb (InfileTree *qe, DbInit di)
Translates info for a agent from an input file to the database by reading parameters from the passed InfileTree and recording data via the DbInit variable.
virtual void InitFrom (QueryableBackend *b)
Intializes an agent's internal state from an output database.
virtual void InitInv (Inventories &inv)
Provides an agent's initial inventory of resources before a simulation begins.
Region (Context *ctx)
Default constructor for Region Class.
virtual void Snapshot (DbInit di)
Snapshots agent-internal state to the output db via DbInit.
virtual Inventories SnapshotInv ()
Snapshots and agent's resource inventories to the output db.
virtual std::string str ()
every agent should be able to print a verbose description
virtual void Tick (int time)
Simulation agents do their beginning-of-timestep activities in the Tick method.
virtual void Tock (int time)
Simulation agents do their end-of-timestep activities in the Tock method.
virtual ~Region ()
Regions should not be indestructible.
Protected Member Functions
void InitFrom (Region *m)
Detailed Description
The Region class is the abstract class/interface used by all region agents.
This is all that is known externally about Regions
Introduction
The Region type assists in defining the region-institution-facility hierarchy in Cyclus. A Region region is an actor associated with a set of institutions or facilities for which it is responsible. A Region may be used to adjust preferences in the ResourceExchange to make material routing decisions based on interfacility relationships. Deployment is a primary differentiator between different Region implementations.
Like all agent implementations, there are a number of implementations that are distributed as part of the core Cyclus application as well as implementations contributed by third-party developers. The links below describe additional parameters necessary for the complete definition of a region of that implementation.
Basic Functionality
All regions perform three major functions:
Schedule the deployment of facilities by either
Determining when new facilities need to be built, or
Deferring to an Institution to make this determination.
Manage the deployment of facilities by interacting with the Institutions to select a specific facility type and facility parameters
Different regional types will be required to fully define the first two functions while the third is a built-in capability for all region types. For instance, one may wish to include a region which has exponential growth as its driving factor for facility creation or one may wish to have pre-determined building order based on time step (e.g. the JAEA benchmark). Additionally, one may wish for there to be a one-to-one region-to-instituion deployment for simple agents and thus demand that each instiution simply build a facility when its region determines the facility's necessity. However, one may instead wish to have two competing instiutions in one region and have the institution which provides the best incentive to the region to build a required facility.
Available Core Implementation
NullRegion: This region is associated with a set of allowed facilities. It defers to an institution regarding facility deployment, making no demands on facility type or parameter (save the facility's allowability in the region). It makes no alterations to messages passed through it in either the up or down direction.
Definition at line 63 of file region.h.
Constructor & Destructor Documentation
cyclus::Region::Region (Context * ctx)
Default constructor for Region Class.
Definition at line 22 of file region.cc.
References cyclus::Agent::kind_.
virtual cyclus::Region::~Region () [inline, virtual]
Regions should not be indestructible.
Definition at line 77 of file region.h.
Member Function Documentation
void cyclus::Region::Build (Agent * parent) [virtual]
perform actions required when entering the simulation
Reimplemented from cyclus::Agent.
Definition at line 26 of file region.cc.
void cyclus::Region::Decommission () [virtual]
Decommissions the agent, removing it from the simulation.
Results in destruction of the agent object. If agents write their own Decommission method, they must call their superclass' Decommission method at the END of their Decommission method.
Reimplemented from cyclus::Agent.
Definition at line 34 of file region.cc.
References cyclus::Agent::context(), and cyclus::Context::UnregisterTimeListener().
void cyclus::Region::DoRegistration () [virtual]
Called to give the agent an opportunity to register for services (e.g.
ticks/tocks and resource exchange). Note that this may be called more than once, and so agents should track their registrations carefully.
Reimplemented from cyclus::Agent.
Definition at line 30 of file region.cc.
References cyclus::Agent::context(), and cyclus::Context::RegisterTimeListener().
virtual void cyclus::Region::InfileToDb (InfileTree * qe, DbInit di) [inline, virtual]
Translates info for a agent from an input file to the database by reading parameters from the passed InfileTree and recording data via the DbInit variable.
The simulation and agent id's are automatically injected in all data transfered through DbInit. This method must be implemented by all agents. This method must call the superclass' InfileToDb method before doing any other work.
Agent parameters in the InfileTree are scoped in the "agent/[agent-class-name]" path. The agent's class-name can be retrieved from the agent_impl method. The superclass InitFrom expects the InfileTree passed to it to be scoped identically - do NOT pass a changed-scope InfileTree to the superclass.
Example:
 class MyAgentClass : virtual public cyclus::Facility {
   // ...
   void InfileToDb(InfileTree* qe, DbInit di) {
     cyclus::Facility::InitFrom(qe); //
     // now do MyAgentClass' initialitions, e.g.:
     qe = qe->Query("agent/" + agent_impl()); // rescope the InfileTree
     // retrieve all agent params
     std::string recipe = qe->GetString("recipe");
     std::string in_commod = qe->GetString("in_commod");
     std::string out_commod = qe->GetString("out_commod");
     di.NewDatum("MyAgentTable1")
       ->AddVal("recipe", recipe)
       ->AddVal("in_commod", in_commod)
       ->AddVal("out_commod", out_commod)
       ->Record();
     // ...
   };
   // ...
 };
Warning:
this method MUST NOT modify the agent's state.
Reimplemented from cyclus::Agent.
Definition at line 80 of file region.h.
virtual void cyclus::Region::InitFrom (QueryableBackend * b) [inline, virtual]
Intializes an agent's internal state from an output database.
Appropriate simulation id, agent id, and time filters are automatically included in all queries.
Warning:
Agents must NOT create any resource objects in this method.
Reimplemented from cyclus::Agent.
Definition at line 83 of file region.h.
Referenced by InitFrom().
void cyclus::Region::InitFrom (Region * m) [protected]
Definition at line 18 of file region.cc.
References InitFrom().
virtual void cyclus::Region::InitInv (Inventories & inv) [inline, virtual]
Provides an agent's initial inventory of resources before a simulation begins.
The resources are keyed in the same way the InitInv method returned. Agents should iterate through each named inventory provided and populate the corresponding resource containers.
Warning:
agents should not modify any state outside the container filling
Implements cyclus::Agent.
Definition at line 88 of file region.h.
virtual void cyclus::Region::Snapshot (DbInit di) [inline, virtual]
Snapshots agent-internal state to the output db via DbInit.
This method MUST call the superclass' Snapshot method before doing any work. The simulation and agent id's in addition to the snapshot time are automatically included in all information transfered through DbInit.
Warning:
because 'SimId' 'SimTime', and 'AgentId' fields are automatically injected, those labels cannot be used for any other fields.
This method MUST NOT modify the agent's state.
Implements cyclus::Agent.
Definition at line 86 of file region.h.
virtual Inventories cyclus::Region::SnapshotInv () [inline, virtual]
Snapshots and agent's resource inventories to the output db.
The set of resources in each container should be stored under a string key specific to that container that will be used when re-initializing inventories for restarted simulations.
Warning:
This method should NOT modify the agent's state.
Implements cyclus::Agent.
Definition at line 90 of file region.h.
std::string cyclus::Region::str () [virtual]
every agent should be able to print a verbose description
Reimplemented from cyclus::Agent.
Definition at line 39 of file region.cc.
References cyclus::Agent::children().
virtual void cyclus::Region::Tick (int time) [inline, virtual]
Simulation agents do their beginning-of-timestep activities in the Tick method.
Parameters:
time is the current simulation timestep
Implements cyclus::TimeListener.
Definition at line 106 of file region.h.
virtual void cyclus::Region::Tock (int time) [inline, virtual]
Simulation agents do their end-of-timestep activities in the Tock method.
Parameters:
time is the current simulation timestep
Implements cyclus::TimeListener.
Definition at line 108 of file region.h.
The documentation for this class was generated from the following files:
region.h
region.cc