CYCLUS: cyclus::Commodity Class Reference
cyclus::Commodity Class Reference
a simple class defining a commodity; it is currently super simple.
#include <commodity.h>
Public Member Functions
Commodity ()
default constructor
Commodity (std::string name)
constructor
std::string name () const
the commodity's name
bool operator!= (const Commodity &other) const
inequality operator
bool operator== (const Commodity &other) const
equality operator
Private Attributes
std::string name_
the name of the commodity
Detailed Description
a simple class defining a commodity; it is currently super simple.
The reason this class exists is so that code may be cleaner and more straightforward while one could have chosen to typedef a string, there may be some reason to extend the class in the future.
Definition at line 13 of file commodity.h.
Constructor & Destructor Documentation
cyclus::Commodity::Commodity ()
default constructor
Definition at line 6 of file commodity.cc.
cyclus::Commodity::Commodity (std::string name)
constructor
Parameters:
name the name of the commodity
Definition at line 9 of file commodity.cc.
Member Function Documentation
std::string cyclus::Commodity::name () const
the commodity's name
Definition at line 12 of file commodity.cc.
References name_.
Referenced by cyclus::CommodityCompare::operator()(), operator==(), cyclus::SupplyDemandManager::ThrowErrorIfCommodityNotManaged(), and cyclus::CommodityProducer::ThrowErrorIfCommodityNotProduced().
bool cyclus::Commodity::operator!= (const Commodity & other) const
inequality operator
Definition at line 22 of file commodity.cc.
bool cyclus::Commodity::operator== (const Commodity & other) const
equality operator
Definition at line 17 of file commodity.cc.
References name(), and name_.
Member Data Documentation
std::string cyclus::Commodity::name_ [private]
the name of the commodity
Definition at line 37 of file commodity.h.
Referenced by name(), and operator==().
The documentation for this class was generated from the following files:
commodity.h
commodity.cc