CYCLUS: cyclus::CommodityProducer Class Reference
cyclus::CommodityProducer Class Reference
a mixin to provide information about produced commodities
#include <commodity_producer.h>
Public Member Functions
void AddCommodity (const Commodity &commodity)
register a commodity as being produced by this object
void AddCommodityWithInformation (const Commodity &commodity, const CommodInfo &info)
register a commodity as being produced by this object and set its relevant info
CommodityProducer ()
constructor
void CopyProducedCommoditiesFrom (CommodityProducer *source)
add all commodities produced by a source
std::set< Commodity,
CommodityCompare > ProducedCommodities ()
bool ProducesCommodity (const Commodity &commodity)
double ProductionCapacity (const Commodity &commodity)
double ProductionCost (const Commodity &commodity)
void SetCapacity (const Commodity &commodity, double capacity)
set the production capacity for a given commodity
void SetCost (const Commodity &commodity, double cost)
set the production cost for a given commodity
void ThrowErrorIfCommodityNotProduced (const Commodity &commodity)
checks if ProducesCommodity() is true.
virtual ~CommodityProducer ()
virtual destructor for inheritance
Public Attributes
double default_capacity_
a default production capacity
double default_cost_
a default production cost
Private Attributes
std::map< Commodity,
CommodInfo, CommodityCompare > produced_commodities_
a collection of commodities and their production capacities
Detailed Description
a mixin to provide information about produced commodities
Definition at line 20 of file commodity_producer.h.
Constructor & Destructor Documentation
cyclus::CommodityProducer::CommodityProducer ()
constructor
Definition at line 20 of file commodity_producer.cc.
cyclus::CommodityProducer::~CommodityProducer () [virtual]
virtual destructor for inheritance
Definition at line 25 of file commodity_producer.cc.
Member Function Documentation
void cyclus::CommodityProducer::AddCommodity (const Commodity & commodity)
register a commodity as being produced by this object
Parameters:
commodity the commodity being produced
Definition at line 58 of file commodity_producer.cc.
References AddCommodityWithInformation(), default_capacity_, and default_cost_.
Referenced by CopyProducedCommoditiesFrom().
void cyclus::CommodityProducer::AddCommodityWithInformation (const Commodity & commodity, const CommodInfo & info)
register a commodity as being produced by this object and set its relevant info
Parameters:
commodity the commodity being produced
info the information describing the commodity
Definition at line 78 of file commodity_producer.cc.
References produced_commodities_, and ProducesCommodity().
Referenced by AddCommodity().
void cyclus::CommodityProducer::CopyProducedCommoditiesFrom (CommodityProducer * source)
add all commodities produced by a source
Parameters:
source the original commodity producer
Definition at line 86 of file commodity_producer.cc.
References AddCommodity(), ProducedCommodities(), ProductionCapacity(), ProductionCost(), SetCapacity(), and SetCost().
std::set< Commodity, CommodityCompare > cyclus::CommodityProducer::ProducedCommodities ()
Returns:
the set of commodities produced by this producers
Definition at line 28 of file commodity_producer.cc.
References produced_commodities_.
Referenced by CopyProducedCommoditiesFrom().
bool cyclus::CommodityProducer::ProducesCommodity (const Commodity & commodity)
Parameters:
commodity the commodity in question
Returns:
true if the commodity is produced by this entity
Definition at line 40 of file commodity_producer.cc.
References produced_commodities_.
Referenced by AddCommodityWithInformation(), cyclus::BuildingManager::SetUpProblem(), and ThrowErrorIfCommodityNotProduced().
double cyclus::CommodityProducer::ProductionCapacity (const Commodity & commodity)
Parameters:
commodity the commodity in question
Returns:
the production capacity for a commodity
Definition at line 46 of file commodity_producer.cc.
References produced_commodities_, and ThrowErrorIfCommodityNotProduced().
Referenced by cyclus::BuildingManager::AddProducerVariableToProblem(), and CopyProducedCommoditiesFrom().
double cyclus::CommodityProducer::ProductionCost (const Commodity & commodity)
Returns:
the cost to produce a commodity at a given capacity
Parameters:
commodity the commodity in question
Definition at line 52 of file commodity_producer.cc.
References produced_commodities_, and ThrowErrorIfCommodityNotProduced().
Referenced by cyclus::BuildingManager::AddProducerVariableToProblem(), and CopyProducedCommoditiesFrom().
void cyclus::CommodityProducer::SetCapacity (const Commodity & commodity, double capacity)
set the production capacity for a given commodity
Parameters:
commodity the commodity being produced
capacity the production capacity
Definition at line 64 of file commodity_producer.cc.
References produced_commodities_, and ThrowErrorIfCommodityNotProduced().
Referenced by CopyProducedCommoditiesFrom().
void cyclus::CommodityProducer::SetCost (const Commodity & commodity, double cost)
set the production cost for a given commodity
Parameters:
commodity the commodity being produced
cost the production cost
Definition at line 71 of file commodity_producer.cc.
References produced_commodities_, and ThrowErrorIfCommodityNotProduced().
Referenced by CopyProducedCommoditiesFrom().
void cyclus::CommodityProducer::ThrowErrorIfCommodityNotProduced (const Commodity & commodity)
checks if ProducesCommodity() is true.
If it is false, an error is thrown.
Parameters:
commodity the commodity in question
Definition at line 98 of file commodity_producer.cc.
References cyclus::Commodity::name(), and ProducesCommodity().
Referenced by ProductionCapacity(), ProductionCost(), SetCapacity(), and SetCost().
Member Data Documentation
double cyclus::CommodityProducer::default_capacity_
a default production capacity
Definition at line 76 of file commodity_producer.h.
Referenced by AddCommodity().
double cyclus::CommodityProducer::default_cost_
a default production cost
Definition at line 79 of file commodity_producer.h.
Referenced by AddCommodity().
std::map<Commodity, CommodInfo, CommodityCompare> cyclus::CommodityProducer::produced_commodities_ [private]
a collection of commodities and their production capacities
Definition at line 83 of file commodity_producer.h.
Referenced by AddCommodityWithInformation(), ProducedCommodities(), ProducesCommodity(), ProductionCapacity(), ProductionCost(), SetCapacity(), and SetCost().
The documentation for this class was generated from the following files:
commodity_producer.h
commodity_producer.cc