CYCLUS: cyclus::ResourceExchange< T > Class Template Reference
cyclus::ResourceExchange< T > Class Template Reference
The ResourceExchange class manages the communication for the supply and demand of resources in a simulation.
#include <resource_exchange.h>
Public Member Functions
void AddAllBids ()
queries traders and collects all responses to requests for bids
void AddAllRequests ()
queries traders and collects all requests for bids
void AdjustAll ()
adjust preferences for requests given bid responses
ExchangeContext< T > & ex_ctx ()
ResourceExchange (Context *ctx)
default constructor
Private Member Functions
void AddBids_ (Trader *t)
queries a given facility agent for
void AddRequests_ (Trader *t)
queries a given facility agent for
void AdjustPrefs_ (Trader *t)
allows a trader and its parents to adjust any preferences in the system
Private Attributes
Context * ctx_
ExchangeContext< T > ex_ctx_
Detailed Description
template<class T>
class cyclus::ResourceExchange< T >
The ResourceExchange class manages the communication for the supply and demand of resources in a simulation.
At any given timestep, there are three main phases involved:
Request for Bids Agents that demand resources of a given type post their
demands to the exchange
Response to Request for Bids Agents that supply resources of a given type respond to
those requests
Preference Adjustment Preferences for each request-bid pair are set, informing
the evenutal soluation mechanism
For example, assuming a simulation Context, ctx, and resource type, ResourceType:
 ResourceExchange<ResourceType> exchng(ctx);
 exchng.AddAllRequests();
 exchng.AddAllBids();
 exchng.AdjustAll();
Definition at line 65 of file resource_exchange.h.
Constructor & Destructor Documentation
template<class T> cyclus::ResourceExchange< T >::ResourceExchange (Context * ctx) [inline]
default constructor
Parameters:
ctx the simulation context
Definition at line 70 of file resource_exchange.h.
References cyclus::ResourceExchange< T >::ctx_.
Member Function Documentation
template<class T> void cyclus::ResourceExchange< T >::AddAllBids () [inline]
queries traders and collects all responses to requests for bids
Definition at line 89 of file resource_exchange.h.
References cyclus::ResourceExchange< T >::ctx_, and cyclus::Context::traders().
Referenced by cyclus::ExchangeManager< T >::Execute().
template<class T> void cyclus::ResourceExchange< T >::AddAllRequests () [inline]
queries traders and collects all requests for bids
Definition at line 79 of file resource_exchange.h.
References cyclus::ResourceExchange< T >::ctx_, and cyclus::Context::traders().
Referenced by cyclus::ExchangeManager< T >::Execute().
template<class T> void cyclus::ResourceExchange< T >::AddBids_ (Trader * t) [inline, private]
queries a given facility agent for
Definition at line 120 of file resource_exchange.h.
References cyclus::ResourceExchange< T >::ex_ctx_.
template<class T> void cyclus::ResourceExchange< T >::AddRequests_ (Trader * t) [inline, private]
queries a given facility agent for
Definition at line 111 of file resource_exchange.h.
References cyclus::ResourceExchange< T >::ex_ctx_.
template<class T> void cyclus::ResourceExchange< T >::AdjustAll () [inline]
adjust preferences for requests given bid responses
Definition at line 99 of file resource_exchange.h.
References cyclus::ResourceExchange< T >::ex_ctx_.
Referenced by cyclus::ExchangeManager< T >::Execute().
template<class T> void cyclus::ResourceExchange< T >::AdjustPrefs_ (Trader * t) [inline, private]
allows a trader and its parents to adjust any preferences in the system
Definition at line 131 of file resource_exchange.h.
References cyclus::AdjustPrefs(), cyclus::ResourceExchange< T >::ex_ctx_, cyclus::Trader::manager(), and cyclus::Agent::parent().
template<class T> ExchangeContext<T>& cyclus::ResourceExchange< T >::ex_ctx () [inline]
Definition at line 74 of file resource_exchange.h.
References cyclus::ResourceExchange< T >::ex_ctx_.
Referenced by cyclus::ExchangeManager< T >::Execute().
Member Data Documentation
template<class T> Context* cyclus::ResourceExchange< T >::ctx_ [private]
Definition at line 139 of file resource_exchange.h.
Referenced by cyclus::ResourceExchange< T >::AddAllBids(), cyclus::ResourceExchange< T >::AddAllRequests(), and cyclus::ResourceExchange< T >::ResourceExchange().
template<class T> ExchangeContext<T> cyclus::ResourceExchange< T >::ex_ctx_ [private]
Definition at line 142 of file resource_exchange.h.
Referenced by cyclus::ResourceExchange< T >::AddBids_(), cyclus::ResourceExchange< T >::AddRequests_(), cyclus::ResourceExchange< T >::AdjustAll(), cyclus::ResourceExchange< T >::AdjustPrefs_(), and cyclus::ResourceExchange< T >::ex_ctx().
The documentation for this class was generated from the following file:
resource_exchange.h