CYCLUS: cyclus::SimInit Class Reference
cyclus::SimInit Class Reference
Handles initialization of a simulation from the output database.
#include <sim_init.h>
Public Member Functions
void Branch (QueryableBackend *b, boost::uuids::uuid prev_sim_id, int t, boost::uuids::uuid new_sim_id)
NOT IMPLEMENTED.
Context * context ()
Returns the initialized context.
void Init (Recorder *r, QueryableBackend *b)
Initialize a simulation with data from b for simulation id in r.
Recorder * recorder ()
Returns the initialized recorder with registered backends.
void Restart (QueryableBackend *b, boost::uuids::uuid sim_id, int t)
Restarts a simulation from time t with data from b identified by simid.
SimInit ()
Timer * timer ()
Returns the initialized timer.
~SimInit ()
Static Public Member Functions
static void Snapshot (Context *ctx)
Records a snapshot of the current state of the simulation being managed by ctx into the simulations output database.
Private Member Functions
void InitBase (QueryableBackend *b, boost::uuids::uuid simid, int t)
void LoadBuildSched ()
Composition::Ptr LoadComposition (int stateid)
void LoadDecomSched ()
void LoadInfo ()
void LoadInitialAgents ()
void LoadInventories ()
Resource::Ptr LoadMaterial (int resid)
void LoadNextIds ()
Resource::Ptr LoadProduct (int resid)
void LoadPrototypes ()
void LoadRecipes ()
Resource::Ptr LoadResource (int resid)
void LoadSolverInfo ()
Static Private Member Functions
static void SnapAgent (Agent *m)
Private Attributes
std::map< int, Agent * > agents_
QueryableBackend * b_
Context * ctx_
Recorder * rec_
boost::uuids::uuid simid_
int t_
Timer ti_
Detailed Description
Handles initialization of a simulation from the output database.
After calling Init, Restart, or Branch, the initialized Context, Timer, and Recorder can be retrieved.
Warning:
the Init, Restart, and Branch methods are NOT idempotent. Only one simulation should ever be initialized per SimInit object.
the SimInit class manages the memory of the initialized Context, Timer, and Recorder.
Definition at line 24 of file sim_init.h.
Constructor & Destructor Documentation
cyclus::SimInit::SimInit ()
Definition at line 16 of file sim_init.cc.
cyclus::SimInit::~SimInit ()
Definition at line 18 of file sim_init.cc.
References ctx_, and rec_.
Member Function Documentation
void cyclus::SimInit::Branch (QueryableBackend * b, boost::uuids::uuid prev_sim_id, int t, boost::uuids::uuid new_sim_id)
NOT IMPLEMENTED.
Initializes a simulation branched from prev_sim_id at time t with diverging state described in new_sim_id.
TODO: implement
Definition at line 38 of file sim_init.cc.
Context* cyclus::SimInit::context () [inline]
Returns the initialized context.
Note that either Init, Restart, or Branch must be called first.
Definition at line 50 of file sim_init.h.
References ctx_.
void cyclus::SimInit::Init (Recorder * r, QueryableBackend * b)
Initialize a simulation with data from b for simulation id in r.
Definition at line 27 of file sim_init.cc.
References ctx_, InitBase(), rec_, cyclus::Context::rec_, and cyclus::Recorder::sim_id().
void cyclus::SimInit::InitBase (QueryableBackend * b, boost::uuids::uuid simid, int t) [private]
Definition at line 44 of file sim_init.cc.
References b_, ctx_, cyclus::Recorder::Flush(), LoadBuildSched(), LoadDecomSched(), LoadInfo(), LoadInitialAgents(), LoadInventories(), LoadNextIds(), LoadPrototypes(), LoadRecipes(), LoadSolverInfo(), rec_, cyclus::Recorder::set_dump_count(), simid_, t_, and ti_.
Referenced by Init(), and Restart().
void cyclus::SimInit::LoadBuildSched () [private]
Definition at line 303 of file sim_init.cc.
References agents_, b_, ctx_, cyclus::QueryResult::GetVal(), cyclus::QueryableBackend::Query(), cyclus::QueryResult::rows, cyclus::Context::SchedBuild(), and t_.
Referenced by InitBase().
Composition::Ptr cyclus::SimInit::LoadComposition (int stateid) [private]
Definition at line 395 of file sim_init.cc.
References b_, cyclus::Composition::CreateFromMass(), cyclus::QueryResult::GetVal(), cyclus::QueryableBackend::Query(), and cyclus::QueryResult::rows.
Referenced by LoadMaterial().
void cyclus::SimInit::LoadDecomSched () [private]
Definition at line 319 of file sim_init.cc.
References agents_, b_, ctx_, cyclus::QueryResult::GetVal(), cyclus::QueryableBackend::Query(), cyclus::QueryResult::rows, cyclus::Context::SchedDecom(), and t_.
Referenced by InitBase().
void cyclus::SimInit::LoadInfo () [private]
Definition at line 133 of file sim_init.cc.
References b_, ctx_, cyclus::QueryResult::GetVal(), cyclus::Context::InitSim(), and cyclus::QueryableBackend::Query().
Referenced by InitBase().
void cyclus::SimInit::LoadInitialAgents () [private]
Definition at line 210 of file sim_init.cc.
References agents_, b_, cyclus::Agent::Connect(), cyclus::Context::CreateAgent(), ctx_, cyclus::Agent::DoRegistration(), cyclus::QueryResult::GetVal(), cyclus::Agent::id_, cyclus::QueryableBackend::Query(), cyclus::QueryResult::rows, and t_.
Referenced by InitBase().
void cyclus::SimInit::LoadInventories () [private]
Definition at line 281 of file sim_init.cc.
References agents_, b_, cyclus::QueryResult::GetVal(), cyclus::Agent::id(), cyclus::Agent::InitInv(), LoadResource(), cyclus::QueryableBackend::Query(), cyclus::QueryResult::rows, and t_.
Referenced by InitBase().
Resource::Ptr cyclus::SimInit::LoadMaterial (int resid) [private]
Definition at line 370 of file sim_init.cc.
References b_, cyclus::Material::Create(), ctx_, cyclus::QueryResult::GetVal(), LoadComposition(), cyclus::QueryableBackend::Query(), and t_.
Referenced by LoadResource().
void cyclus::SimInit::LoadNextIds () [private]
Definition at line 334 of file sim_init.cc.
References b_, ctx_, cyclus::QueryResult::GetVal(), cyclus::Composition::next_id_, cyclus::Agent::next_id_, cyclus::Product::next_state_, cyclus::Resource::nextid_, cyclus::QueryableBackend::Query(), cyclus::QueryResult::rows, t_, and cyclus::Context::trans_id_.
Referenced by InitBase().
Resource::Ptr cyclus::SimInit::LoadProduct (int resid) [private]
Definition at line 408 of file sim_init.cc.
References b_, cyclus::Product::Create(), ctx_, cyclus::QueryResult::GetVal(), cyclus::QueryableBackend::Query(), and cyclus::Product::stateids_.
Referenced by LoadResource().
void cyclus::SimInit::LoadPrototypes () [private]
Definition at line 185 of file sim_init.cc.
References cyclus::Context::AddPrototype(), b_, ctx_, cyclus::QueryResult::GetVal(), cyclus::DynamicModule::Make(), cyclus::QueryableBackend::Query(), cyclus::QueryResult::rows, and t_.
Referenced by InitBase().
void cyclus::SimInit::LoadRecipes () [private]
Definition at line 142 of file sim_init.cc.
References cyclus::Context::AddRecipe(), b_, cyclus::Composition::CreateFromMass(), ctx_, cyclus::QueryResult::GetVal(), cyclus::QueryableBackend::Query(), and cyclus::QueryResult::rows.
Referenced by InitBase().
Resource::Ptr cyclus::SimInit::LoadResource (int resid) [private]
Definition at line 356 of file sim_init.cc.
References b_, cyclus::QueryResult::GetVal(), cyclus::Product::kType, cyclus::Material::kType, LoadMaterial(), LoadProduct(), and cyclus::QueryableBackend::Query().
Referenced by LoadInventories().
void cyclus::SimInit::LoadSolverInfo () [private]
Definition at line 163 of file sim_init.cc.
References b_, ctx_, cyclus::QueryResult::GetVal(), cyclus::QueryableBackend::Query(), cyclus::GreedyPreconditioner::REVERSE, cyclus::QueryResult::rows, and cyclus::Context::solver().
Referenced by InitBase().
Recorder* cyclus::SimInit::recorder () [inline]
Returns the initialized recorder with registered backends.
Note that either Init, Restart, or Branch must be called first.
Definition at line 54 of file sim_init.h.
References rec_.
void cyclus::SimInit::Restart (QueryableBackend * b, boost::uuids::uuid sim_id, int t)
Restarts a simulation from time t with data from b identified by simid.
The newly configured simulation will run with a new simulation id.
Definition at line 33 of file sim_init.cc.
References InitBase(), and rec_.
void cyclus::SimInit::SnapAgent (Agent * m) [static, private]
Definition at line 109 of file sim_init.cc.
References cyclus::Datum::AddVal(), cyclus::Agent::context(), cyclus::Agent::id(), cyclus::Context::NewDatum(), cyclus::Datum::Record(), cyclus::Agent::Snapshot(), cyclus::Agent::SnapshotInv(), and cyclus::Context::time().
Referenced by Snapshot().
void cyclus::SimInit::Snapshot (Context * ctx) [static]
Records a snapshot of the current state of the simulation being managed by ctx into the simulations output database.
Definition at line 70 of file sim_init.cc.
References cyclus::Datum::AddVal(), cyclus::Context::agent_list_, cyclus::Agent::enter_time(), cyclus::Context::NewDatum(), cyclus::Composition::next_id_, cyclus::Agent::next_id_, cyclus::Product::next_state_, cyclus::Resource::nextid_, cyclus::Datum::Record(), SnapAgent(), cyclus::Context::time(), and cyclus::Context::trans_id_.
Referenced by cyclus::XMLFileLoader::LoadSim().
Timer* cyclus::SimInit::timer () [inline]
Returns the initialized timer.
Note that either Init, Restart, or Branch must be called first.
Definition at line 58 of file sim_init.h.
References ti_.
Member Data Documentation
std::map<int, Agent*> cyclus::SimInit::agents_ [private]
Definition at line 81 of file sim_init.h.
Referenced by LoadBuildSched(), LoadDecomSched(), LoadInitialAgents(), and LoadInventories().
QueryableBackend* cyclus::SimInit::b_ [private]
Definition at line 87 of file sim_init.h.
Referenced by InitBase(), LoadBuildSched(), LoadComposition(), LoadDecomSched(), LoadInfo(), LoadInitialAgents(), LoadInventories(), LoadMaterial(), LoadNextIds(), LoadProduct(), LoadPrototypes(), LoadRecipes(), LoadResource(), and LoadSolverInfo().
Context* cyclus::SimInit::ctx_ [private]
Definition at line 83 of file sim_init.h.
Referenced by context(), Init(), InitBase(), LoadBuildSched(), LoadDecomSched(), LoadInfo(), LoadInitialAgents(), LoadMaterial(), LoadNextIds(), LoadProduct(), LoadPrototypes(), LoadRecipes(), LoadSolverInfo(), and ~SimInit().
Recorder* cyclus::SimInit::rec_ [private]
Definition at line 84 of file sim_init.h.
Referenced by Init(), InitBase(), recorder(), Restart(), and ~SimInit().
boost::uuids::uuid cyclus::SimInit::simid_ [private]
Definition at line 86 of file sim_init.h.
Referenced by InitBase().
int cyclus::SimInit::t_ [private]
Definition at line 88 of file sim_init.h.
Referenced by InitBase(), LoadBuildSched(), LoadDecomSched(), LoadInitialAgents(), LoadInventories(), LoadMaterial(), LoadNextIds(), and LoadPrototypes().
Timer cyclus::SimInit::ti_ [private]
Definition at line 85 of file sim_init.h.
Referenced by InitBase(), and timer().
The documentation for this class was generated from the following files:
sim_init.h
sim_init.cc