CYCLUS: cyclus::SqliteBack Class Reference
cyclus::SqliteBack Class Reference
An Recorder backend that writes data to an sqlite database.
#include <sqlite_back.h>
Public Member Functions
void Flush ()
Executes all pending commands.
std::string Name ()
Returns a unique name for this backend.
void Notify (DatumList data)
Writes Datum objects immediately to the database as a single transaction.
virtual QueryResult Query (std::string table, std::vector< Cond > *conds)
Return a set of rows from the specificed table that match all given conditions.
SqliteBack (std::string path)
Creates a new sqlite backend that will write to the database file specified by path.
virtual ~SqliteBack ()
Protected Attributes
StrList cmds_
pending sql commands.
Private Member Functions
void CreateTable (Datum *d)
Queue up a table-create command for d.
QueryResult GetTableInfo (std::string table)
boost::spirit::hold_any StringAsVal (std::string s, std::string type)
converts the string value in s to a c++ value corresponding the the supported sqlite datatype type in a hold_any object.
bool TableExists (std::string name)
returns true if the table name already exists.
std::string ValAsString (boost::spirit::hold_any v)
converts the value to a string insertable into the sqlite db.
std::string ValType (boost::spirit::hold_any v)
returns a valid sql data type name for v (e.g. INTEGER, REAL, TEXT, etc).
void WriteDatum (Datum *d)
constructs an SQL INSERT command for d and queues it for db insertion.
Private Attributes
SqliteDb db_
An interface to a sqlite db managed by the SqliteBack class.
std::string path_
Stores the database's path+name, declared during construction.
StrList tbl_names_
table names already existing (created) in the sqlite db.
Detailed Description
An Recorder backend that writes data to an sqlite database.
Identically named Datum objects have their data placed as rows in a single table. Handles the following datum value types: int, float, double, std::string, cyclus::Blob. Unsupported value types are stored as an empty string.
Definition at line 17 of file sqlite_back.h.
Constructor & Destructor Documentation
cyclus::SqliteBack::SqliteBack (std::string path)
Creates a new sqlite backend that will write to the database file specified by path.
If the file doesn't exist, a new one is created.
Parameters:
path the filepath (including name) to write the sqlite file.
Definition at line 37 of file sqlite_back.cc.
References db_, cyclus::SqliteDb::open(), path_, cyclus::SqliteDb::Query(), and tbl_names_.
cyclus::SqliteBack::~SqliteBack () [virtual]
Definition at line 28 of file sqlite_back.cc.
References CLOG, cyclus::SqliteDb::close(), db_, Flush(), cyclus::LEV_ERROR, and cyclus::Error::what().
Member Function Documentation
void cyclus::SqliteBack::CreateTable (Datum * d) [private]
Queue up a table-create command for d.
Definition at line 123 of file sqlite_back.cc.
References cmds_, tbl_names_, cyclus::Datum::title(), cyclus::Datum::vals(), and ValType().
Referenced by Notify().
void cyclus::SqliteBack::Flush () [virtual]
Executes all pending commands.
Implements cyclus::RecBackend.
Definition at line 250 of file sqlite_back.cc.
References cmds_, db_, and cyclus::SqliteDb::Execute().
Referenced by Notify(), and ~SqliteBack().
QueryResult cyclus::SqliteBack::GetTableInfo (std::string table) [private]
Definition at line 87 of file sqlite_back.cc.
References db_, cyclus::QueryResult::fields, cyclus::SqliteDb::Query(), cyclus::split(), and cyclus::QueryResult::types.
Referenced by Query().
std::string cyclus::SqliteBack::Name () [virtual]
Returns a unique name for this backend.
Implements cyclus::RecBackend.
Definition at line 119 of file sqlite_back.cc.
References path_.
Referenced by StringAsVal(), and ValAsString().
void cyclus::SqliteBack::Notify (DatumList data) [virtual]
Writes Datum objects immediately to the database as a single transaction.
Parameters:
data group of Datum objects to write to the database together.
Implements cyclus::RecBackend.
Definition at line 49 of file sqlite_back.cc.
References CreateTable(), Flush(), TableExists(), and WriteDatum().
QueryResult cyclus::SqliteBack::Query (std::string table, std::vector< Cond > * conds) [virtual]
Return a set of rows from the specificed table that match all given conditions.
Conditions are AND'd together. conds may be NULL.
Implements cyclus::QueryableBackend.
Definition at line 59 of file sqlite_back.cc.
References db_, cyclus::Cond::field, cyclus::QueryResult::fields, GetTableInfo(), cyclus::Cond::op, cyclus::SqliteDb::Query(), cyclus::QueryResult::rows, StringAsVal(), cyclus::QueryResult::types, cyclus::Cond::val, and ValAsString().
boost::spirit::hold_any cyclus::SqliteBack::StringAsVal (std::string s, std::string type) [private]
converts the string value in s to a c++ value corresponding the the supported sqlite datatype type in a hold_any object.
Definition at line 233 of file sqlite_back.cc.
References CLOG, cyclus::LEV_ERROR, and Name().
Referenced by Query().
bool cyclus::SqliteBack::TableExists (std::string name) [private]
returns true if the table name already exists.
Definition at line 152 of file sqlite_back.cc.
References tbl_names_.
Referenced by Notify().
std::string cyclus::SqliteBack::ValAsString (boost::spirit::hold_any v) [private]
converts the value to a string insertable into the sqlite db.
Definition at line 204 of file sqlite_back.cc.
References boost::spirit::basic_hold_any< Char >::cast(), CLOG, cyclus::LEV_ERROR, Name(), cyclus::StringToHex(), and boost::spirit::basic_hold_any< Char >::type().
Referenced by Query(), and WriteDatum().
std::string cyclus::SqliteBack::ValType (boost::spirit::hold_any v) [private]
returns a valid sql data type name for v (e.g. INTEGER, REAL, TEXT, etc).
Definition at line 141 of file sqlite_back.cc.
References boost::spirit::basic_hold_any< Char >::type().
Referenced by CreateTable().
void cyclus::SqliteBack::WriteDatum (Datum * d) [private]
constructs an SQL INSERT command for d and queues it for db insertion.
Definition at line 156 of file sqlite_back.cc.
References cmds_, cyclus::Datum::title(), ValAsString(), and cyclus::Datum::vals().
Referenced by Notify().
Member Data Documentation
StrList cyclus::SqliteBack::cmds_ [protected]
pending sql commands.
Definition at line 40 of file sqlite_back.h.
Referenced by CreateTable(), Flush(), and WriteDatum().
SqliteDb cyclus::SqliteBack::db_ [private]
An interface to a sqlite db managed by the SqliteBack class.
Definition at line 65 of file sqlite_back.h.
Referenced by Flush(), GetTableInfo(), Query(), SqliteBack(), and ~SqliteBack().
std::string cyclus::SqliteBack::path_ [private]
Stores the database's path+name, declared during construction.
Definition at line 68 of file sqlite_back.h.
Referenced by Name(), and SqliteBack().
StrList cyclus::SqliteBack::tbl_names_ [private]
table names already existing (created) in the sqlite db.
Definition at line 71 of file sqlite_back.h.
Referenced by CreateTable(), SqliteBack(), and TableExists().
The documentation for this class was generated from the following files:
sqlite_back.h
sqlite_back.cc