CYCLUS: cyclus::SqliteDb Class Reference
cyclus::SqliteDb Class Reference
#include <sqlite_db.h>
Public Member Functions
void close ()
void Execute (std::string cmd)
void open ()
void Overwrite ()
std::vector< StrList > Query (std::string cmd)
SqliteDb (std::string path, bool readonly=false)
virtual ~SqliteDb ()
Private Attributes
sqlite3 * db_
bool isOpen_
bool overwrite_
indicates if open() will overwrite a file at 'path'.
std::string path_
bool readonly_
indicates true if the db is readonly false otherwise
Detailed Description
An abstraction over the Sqlite native C interface to simplify database creation and data insertion.
Definition at line 17 of file sqlite_db.h.
Constructor & Destructor Documentation
cyclus::SqliteDb::SqliteDb (std::string path, bool readonly = false)
Creates a new Sqlite database to be stored at the specified path.
Parameters:
path the path+name for the sqlite database file
readonly a boolean indicating true if db is readonly
Definition at line 14 of file sqlite_db.cc.
cyclus::SqliteDb::~SqliteDb () [virtual]
Definition at line 22 of file sqlite_db.cc.
Member Function Documentation
void cyclus::SqliteDb::close ()
Finishes any incomplete operations and closes the database.
Exceptions:
IOError if failed to close the database properly
Definition at line 30 of file sqlite_db.cc.
References db_, isOpen_, and path_.
Referenced by cyclus::SqliteBack::~SqliteBack().
void cyclus::SqliteDb::Execute (std::string cmd)
Execute an SQL command.
Parameters:
cmd an Sqlite compatible SQL command
Exceptions:
IOError SQL command execution failed (e.g. invalid SQL)
Definition at line 66 of file sqlite_db.cc.
References db_, and open().
Referenced by cyclus::SqliteBack::Flush().
void cyclus::SqliteDb::open ()
Opens the sqlite database by either opening/creating a file (default) or creating/overwriting a file (see the overwrite method).
Exceptions:
IOError if failed to open existing database
Definition at line 41 of file sqlite_db.cc.
References db_, isOpen_, overwrite_, path_, and readonly_.
Referenced by Execute(), Query(), and cyclus::SqliteBack::SqliteBack().
void cyclus::SqliteDb::Overwrite ()
Instead of opening a file of the specified name (if it already exists), overwrite it with a new empty database.
Definition at line 25 of file sqlite_db.cc.
References overwrite_.
std::vector< StrList > cyclus::SqliteDb::Query (std::string cmd)
Execute an SQL query and return its results
Parameters:
cmd an Sqlite compatible SQL query
Returns:
a list of row entries
Exceptions:
IOError SQL command execution failed (e.g. invalid SQL)
Definition at line 85 of file sqlite_db.cc.
References db_, and open().
Referenced by cyclus::SqliteBack::GetTableInfo(), cyclus::SqliteBack::Query(), and cyclus::SqliteBack::SqliteBack().
Member Data Documentation
sqlite3* cyclus::SqliteDb::db_ [private]
Definition at line 69 of file sqlite_db.h.
Referenced by close(), Execute(), open(), and Query().
bool cyclus::SqliteDb::isOpen_ [private]
Definition at line 71 of file sqlite_db.h.
Referenced by close(), and open().
bool cyclus::SqliteDb::overwrite_ [private]
indicates if open() will overwrite a file at 'path'.
Definition at line 76 of file sqlite_db.h.
Referenced by open(), and Overwrite().
std::string cyclus::SqliteDb::path_ [private]
Definition at line 73 of file sqlite_db.h.
Referenced by close(), and open().
bool cyclus::SqliteDb::readonly_ [private]
indicates true if the db is readonly false otherwise
Definition at line 79 of file sqlite_db.h.
Referenced by open().
The documentation for this class was generated from the following files:
sqlite_db.h
sqlite_db.cc