CYCLUS: cyclus::UniformTaylor Class Reference
cyclus::UniformTaylor Class Reference
A class that solves the matrix exponential problem using the Taylor Series with Uniformization method.
#include <uniform_taylor.h>
Static Public Member Functions
static Vector MatrixExpSolver (const Matrix &A, const Vector &x_o, const double t)
Solves the matrix exponential problem:
Static Private Member Functions
static Vector GetSolutionVector (const Matrix &B, const Vector &x_o, double alpha, double t, double tol)
Computes the solution Vector x_t using the Taylor Series with Uniformization method.
static double MaxAbsDiag (const Matrix &A)
Returns the diagonal element in the Matrix A that has the largest absolute value.
static int MaxNumTerms (long double alpha_t, double epsilon)
Computes the maximum number of terms needed to obtain an accuracy of epsilon when using the Taylor Series with Uniformization method.
Detailed Description
A class that solves the matrix exponential problem using the Taylor Series with Uniformization method.
Definition at line 17 of file uniform_taylor.h.
Member Function Documentation
Vector cyclus::UniformTaylor::GetSolutionVector (const Matrix & B, const Vector & x_o, double alpha, double t, double tol) [static, private]
Computes the solution Vector x_t using the Taylor Series with Uniformization method.
Parameters:
B the Matrix B = A + alpha * I
x_o the initial condition Vector
alpha the diagonal element of A with the largest absolute value
t the value for which the solution is being evaluated
tol the accuracy desired
Returns:
the solution Vector x_t for the given value of t
Exceptions:
<string> if exp(-alpha * t) or exp(alpha * t) exceeds range
Definition at line 67 of file uniform_taylor.cc.
References MaxNumTerms().
Referenced by MatrixExpSolver().
Vector cyclus::UniformTaylor::MatrixExpSolver (const Matrix & A, const Vector & x_o, const double t) [static]
Solves the matrix exponential problem:
dx(t) ----- = A * x(t) dt
where A is an nxn Matrix and x(t) is a nx1 Vector. The solution to this equation can be determined by calculating:
x(t) = e^(tA) * x(t=0)
Parameters:
A the Matrix
x_o the initial condition Vector x(t=0)
t the value for which the solution is being evaluated
Returns:
the solution Vector x(t)
Exceptions:
<string> if the Uniform Taylor method cannot be used
Definition at line 13 of file uniform_taylor.cc.
References GetSolutionVector(), cyclus::identity(), MaxAbsDiag(), and cyclus::LMatrix::NumRows().
Referenced by cyclus::Decayer::Decay().
double cyclus::UniformTaylor::MaxAbsDiag (const Matrix & A) [static, private]
Returns the diagonal element in the Matrix A that has the largest absolute value.
Parameters:
A the Matrix
Returns:
the diagonal element of A with the largest absolute value
Definition at line 44 of file uniform_taylor.cc.
References cyclus::LMatrix::NumRows().
Referenced by MatrixExpSolver().
int cyclus::UniformTaylor::MaxNumTerms (long double alpha_t, double epsilon) [static, private]
Computes the maximum number of terms needed to obtain an accuracy of epsilon when using the Taylor Series with Uniformization method.
Parameters:
alpha_t the product alpha * t
epsilon the accuracy desired in the series computation
Returns:
the maximum number of terms needed
Exceptions:
<string> if exp(alpha * t) exceeds range
Definition at line 112 of file uniform_taylor.cc.
Referenced by GetSolutionVector().
The documentation for this class was generated from the following files:
uniform_taylor.h
uniform_taylor.cc