CYCLUS: cyclus::DynamicModule Class Reference
cyclus::DynamicModule Class Reference
#include <dynamic_module.h>
Classes
class Closer
Convenience class for using a stack variable to auto-destruct all loaded dynamic modules.
Public Member Functions
std::string name ()
std::string path ()
If this path for this module has not been discovered yet, path searches for it.
Static Public Member Functions
static void CloseAll ()
Closes all statically loaded dynamic modules.
static Agent * Make (Context *ctx, std::string name)
Returns a newly constructed agent for the given module name.
static const std::string Suffix ()
Private Member Functions
void CloseLibrary ()
closes the loaded module dynamic lib
Agent * ConstructInstance (Context *ctx)
construct an instance of this module
DynamicModule (std::string name)
Creates a new dynamically loadable module.
void OpenLibrary ()
uses dlopen to open the module shared lib
void SetConstructor ()
sets the constructor member
Private Attributes
std::string abs_path_
the path to the library
AgentCtor * constructor_
a functor for the constructor
std::string constructor_name_
the name of all module constructor functions
void * module_library_
the library to open and close
std::string module_name_
the name of the module
Static Private Attributes
static std::map< std::string,
DynamicModule * > modules_
all dynamically loaded modules are added to this map when loaded.
Detailed Description
Definition at line 15 of file dynamic_module.h.
Constructor & Destructor Documentation
cyclus::DynamicModule::DynamicModule (std::string name) [private]
Creates a new dynamically loadable module.
Parameters:
name the name of the module
Definition at line 43 of file dynamic_module.cc.
References abs_path_, cyclus::Env::FindModuleLib(), module_name_, OpenLibrary(), SetConstructor(), and Suffix().
Referenced by Make().
Member Function Documentation
void cyclus::DynamicModule::CloseAll () [static]
Closes all statically loaded dynamic modules.
This should always be called before process termination. This must be called AFTER all agents have been destructed.
Definition at line 30 of file dynamic_module.cc.
References modules_.
Referenced by cyclus::DynamicModule::Closer::~Closer().
void cyclus::DynamicModule::CloseLibrary () [private]
closes the loaded module dynamic lib
Definition at line 41 of file unix_helper_functions.h.
References module_library_.
Agent * cyclus::DynamicModule::ConstructInstance (Context * ctx) [private]
construct an instance of this module
Returns:
a fresh instance
Definition at line 59 of file dynamic_module.cc.
References constructor_.
Referenced by Make().
Agent * cyclus::DynamicModule::Make (Context * ctx, std::string name) [static]
Returns a newly constructed agent for the given module name.
Definition at line 20 of file dynamic_module.cc.
References ConstructInstance(), DynamicModule(), modules_, and name().
Referenced by cyclus::BuildFlatMasterSchema(), cyclus::BuildMasterSchema(), cyclus::XMLFlatLoader::LoadInitialAgents(), cyclus::XMLFileLoader::LoadInitialAgents(), and cyclus::SimInit::LoadPrototypes().
std::string cyclus::DynamicModule::name ()
Returns:
the module name
Definition at line 63 of file dynamic_module.cc.
References module_name_.
Referenced by Make().
void cyclus::DynamicModule::OpenLibrary () [private]
uses dlopen to open the module shared lib
Definition at line 14 of file unix_helper_functions.h.
References abs_path_, and module_library_.
Referenced by DynamicModule().
std::string cyclus::DynamicModule::path ()
If this path for this module has not been discovered yet, path searches for it.
Exceptions:
IOError the library path was not found
Returns:
the filepath of the dynamic library.
Definition at line 67 of file dynamic_module.cc.
References abs_path_.
void cyclus::DynamicModule::SetConstructor () [private]
sets the constructor member
Definition at line 27 of file unix_helper_functions.h.
References constructor_, constructor_name_, and module_library_.
Referenced by DynamicModule().
const std::string cyclus::DynamicModule::Suffix () [static]
Returns:
the global library suffix
Definition at line 39 of file dynamic_module.cc.
References SUFFIX.
Referenced by DynamicModule().
Member Data Documentation
std::string cyclus::DynamicModule::abs_path_ [private]
the path to the library
Definition at line 64 of file dynamic_module.h.
Referenced by DynamicModule(), OpenLibrary(), and path().
AgentCtor* cyclus::DynamicModule::constructor_ [private]
a functor for the constructor
Definition at line 76 of file dynamic_module.h.
Referenced by ConstructInstance(), and SetConstructor().
std::string cyclus::DynamicModule::constructor_name_ [private]
the name of all module constructor functions
Definition at line 70 of file dynamic_module.h.
Referenced by SetConstructor().
void* cyclus::DynamicModule::module_library_ [private]
the library to open and close
Definition at line 73 of file dynamic_module.h.
Referenced by CloseLibrary(), OpenLibrary(), and SetConstructor().
std::string cyclus::DynamicModule::module_name_ [private]
the name of the module
Definition at line 67 of file dynamic_module.h.
Referenced by DynamicModule(), and name().
std::map< std::string, DynamicModule * > cyclus::DynamicModule::modules_ [static, private]
all dynamically loaded modules are added to this map when loaded.
Definition at line 61 of file dynamic_module.h.
Referenced by CloseAll(), and Make().
The documentation for this class was generated from the following files:
dynamic_module.h
dynamic_module.cc
unix_helper_functions.h
windows_helper_functions.h