CYCLUS: cyclus::GreedyPreconditioner Class Reference
cyclus::GreedyPreconditioner Class Reference
A GreedyPreconditioner conditions an ExchangeGraph for a GreedySolver by ordering the RequestGroups and ExchangeNodes within each RequestGroup weighted by their commodity's importance.
#include <greedy_preconditioner.h>
Public Types
enum WgtOrder { REVERSE, END }
the order of commodity weights
Public Member Functions
void Condition (ExchangeGraph *graph)
conditions the graph as described above
GreedyPreconditioner (const std::map< std::string, double > &commod_weights)
constructor if weights are given in heaviest-first order
GreedyPreconditioner (const std::map< std::string, double > &commod_weights, WgtOrder order)
constructor if weights may not be given in heaviest-first order
bool GroupComp (const RequestGroup::Ptr l, const RequestGroup::Ptr r)
a comparitor for ordering containers of Request::Ptrs in descending order based on their average commodity weight
bool NodeComp (const ExchangeNode::Ptr l, const ExchangeNode::Ptr r)
a comparitor for ordering containers of ExchangeNode::Ptrs in descending order based on their commodity's weight
Private Member Functions
void ProcessWeights_ (WgtOrder order)
normalizes all weights to 1 and puts them in the heaviest-first direction
Private Attributes
std::map< std::string, double > commod_weights_
std::map< RequestGroup::Ptr,
double > group_weights_
Detailed Description
A GreedyPreconditioner conditions an ExchangeGraph for a GreedySolver by ordering the RequestGroups and ExchangeNodes within each RequestGroup weighted by their commodity's importance.
The Graph is conditioned in-place.
Weighting
Weights are provided to the conditioner via its constructor. A larger weight implies a higher level of importance for solving. First, the ExchangeNodes of each RequestGroup are sorted according to their weights. Then, the average weight of each RequestGroup is determined. Finally, each RequestGroup is sorted according to their average weight.
Example
Consider the following commodity-to-weight mapping: {"spam": 5, "eggs": 2}. Now consider two RequestGroups with the following commodities: #. g1 = {"eggs", "spam", "eggs"} #. g2 = {"eggs", "spam"}
First, the groups will be ordered and averaged weights will be determined: #. g1 = {"spam", "eggs", "eggs"}, weight = 9/3 #. g2 = {"spam", "eggs"}, weight = 7/2
Finally, the groups themselves will be ordered by average weight: #. {g2, g1}
Definition at line 44 of file greedy_preconditioner.h.
Member Enumeration Documentation
enum cyclus::GreedyPreconditioner::WgtOrder
the order of commodity weights
Enumerator:
REVERSE
a flag for commodity weights given in the reverse order, i.e., lightest first
END
default flag, indicating heaviest-first ordering
Definition at line 47 of file greedy_preconditioner.h.
Constructor & Destructor Documentation
cyclus::GreedyPreconditioner::GreedyPreconditioner (const std::map< std::string, double > & commod_weights) [inline]
constructor if weights are given in heaviest-first order
Warning:
weights are assumed to be positive
Definition at line 55 of file greedy_preconditioner.h.
References END, and ProcessWeights_().
cyclus::GreedyPreconditioner::GreedyPreconditioner (const std::map< std::string, double > & commod_weights, WgtOrder order) [inline]
constructor if weights may not be given in heaviest-first order
Warning:
weights are assumed to be positive
Definition at line 62 of file greedy_preconditioner.h.
References ProcessWeights_().
Member Function Documentation
void cyclus::GreedyPreconditioner::Condition (ExchangeGraph * graph)
conditions the graph as described above
Exceptions:
KeyError if a commodity is in the graph but not in the weight mapping
Definition at line 19 of file greedy_preconditioner.cc.
References CLOG, commod_weights_, group_weights_, GroupComp(), cyclus::GroupWeight(), cyclus::LEV_DEBUG1, NodeComp(), and cyclus::ExchangeGraph::request_groups().
Referenced by cyclus::GreedySolver::Solve().
bool cyclus::GreedyPreconditioner::GroupComp (const RequestGroup::Ptr l, const RequestGroup::Ptr r) [inline]
a comparitor for ordering containers of Request::Ptrs in descending order based on their average commodity weight
Definition at line 82 of file greedy_preconditioner.h.
References group_weights_.
Referenced by Condition().
bool cyclus::GreedyPreconditioner::NodeComp (const ExchangeNode::Ptr l, const ExchangeNode::Ptr r) [inline]
a comparitor for ordering containers of ExchangeNode::Ptrs in descending order based on their commodity's weight
Definition at line 75 of file greedy_preconditioner.h.
References commod_weights_, and cyclus::NodeWeight().
Referenced by Condition().
void cyclus::GreedyPreconditioner::ProcessWeights_ (WgtOrder order) [private]
normalizes all weights to 1 and puts them in the heaviest-first direction
Definition at line 49 of file greedy_preconditioner.cc.
References CLOG, commod_weights_, cyclus::LEV_INFO1, and REVERSE.
Referenced by GreedyPreconditioner().
Member Data Documentation
std::map<std::string, double> cyclus::GreedyPreconditioner::commod_weights_ [private]
Definition at line 92 of file greedy_preconditioner.h.
Referenced by Condition(), NodeComp(), and ProcessWeights_().
std::map<RequestGroup::Ptr, double> cyclus::GreedyPreconditioner::group_weights_ [private]
Definition at line 93 of file greedy_preconditioner.h.
Referenced by Condition(), and GroupComp().
The documentation for this class was generated from the following files:
greedy_preconditioner.h
greedy_preconditioner.cc