CYCLUS: cyclus::GreedySolver Class Reference
cyclus::GreedySolver Class Reference
The GreedySolver provides the implementation for a "greedy" solution to a resource exchange graph.
#include <greedy_solver.h>
Public Member Functions
GreedySolver (bool exclusive_orders=false, GreedyPreconditioner *c=NULL)
virtual ~GreedySolver ()
Protected Member Functions
virtual void Solve ()
the GreedySolver solves an ExchangeGraph by iterating over each RequestGroup and matching requests with the minimum bids possible, starting from the beginning of the the respective request and bid containers.
Private Member Functions
void GreedilySatisfySet_ (RequestGroup::Ptr prs)
Private Attributes
GreedyPreconditioner * conditioner_
Detailed Description
The GreedySolver provides the implementation for a "greedy" solution to a resource exchange graph.
Given an ExchangeGraph, the greedy solver will march through each RequestGroup in the graph, matching request nodes "greedily" with supply nodes. Each request node will attempt to be supplied by supplier arcs as long as those supplier arcs have some excess capacity. The possible suppliers will be ordered by descending preference. The algorithm terminates when one of the following conditions is met: 1) All RequestGroups are satisfied 2) All SupplySets are at capacity
Warning:
the GreedySolver is responsible for deleting is conditioner!
Definition at line 33 of file greedy_solver.h.
Constructor & Destructor Documentation
cyclus::GreedySolver::GreedySolver (bool exclusive_orders = false, GreedyPreconditioner * c = NULL)
Definition at line 13 of file greedy_solver.cc.
cyclus::GreedySolver::~GreedySolver () [virtual]
Definition at line 18 of file greedy_solver.cc.
References conditioner_.
Member Function Documentation
void cyclus::GreedySolver::GreedilySatisfySet_ (RequestGroup::Ptr prs) [private]
Definition at line 37 of file greedy_solver.cc.
References cyclus::ExchangeGraph::AddMatch(), cyclus::Capacity(), CLOG, cyclus::eps(), cyclus::ExchangeSolver::graph_, cyclus::LEV_DEBUG1, cyclus::ExchangeGraph::node_arc_map(), and cyclus::ReqPrefComp().
Referenced by Solve().
void cyclus::GreedySolver::Solve () [protected, virtual]
the GreedySolver solves an ExchangeGraph by iterating over each RequestGroup and matching requests with the minimum bids possible, starting from the beginning of the the respective request and bid containers.
Implements cyclus::ExchangeSolver.
Definition at line 24 of file greedy_solver.cc.
References cyclus::GreedyPreconditioner::Condition(), conditioner_, cyclus::ExchangeSolver::graph_, GreedilySatisfySet_(), and cyclus::ExchangeGraph::request_groups().
Member Data Documentation
GreedyPreconditioner* cyclus::GreedySolver::conditioner_ [private]
Definition at line 48 of file greedy_solver.h.
Referenced by Solve(), and ~GreedySolver().
The documentation for this class was generated from the following files:
greedy_solver.h
greedy_solver.cc