CYCLUS: cyclus::CBCSolver Class Reference
cyclus::CBCSolver Class Reference
the coin branch-and-cut solver, see https://projects.coin-or.org/Cbc.
#include <cbc_solver.h>
Public Member Functions
virtual void Solve (std::vector< Variable::Ptr > &variables, ObjectiveFunction::Ptr obj, std::vector< Constraint::Ptr > &constraints)
Solve an Mixed-Integer Program.
Private Member Functions
std::pair< double, double > ConstraintBounds (Constraint::Ptr c)
get coin-specific bound for a constraint
double ObjDirection (ObjectiveFunction::Ptr obj)
set the objective direction
void PopulateSolution (CbcModel &agent, std::vector< Variable::Ptr > &variables)
populate the solution in the variable vector
void Print (int n_const, int n_vars)
prints each other printing function
void PrintConstraints (int n_const, int n_vars)
print constraint info
void PrintObjFunction (int n_vars)
print objective function info
void PrintVariables (int n_const)
print variables info
void SetUpConstraints (std::vector< Constraint::Ptr > &constraints)
set up constraints
void SetUpVariablesAndObj (std::vector< Variable::Ptr > &variables, ObjectiveFunction::Ptr obj)
set variable/objective function values
void SolveAgent (CbcModel &agent)
solve the agent
Private Attributes
CoinModel builder_
the agent builder
Detailed Description
the coin branch-and-cut solver, see https://projects.coin-or.org/Cbc.
Definition at line 19 of file cbc_solver.h.
Member Function Documentation
std::pair< double, double > cyclus::CBCSolver::ConstraintBounds (Constraint::Ptr c) [private]
get coin-specific bound for a constraint
Definition at line 18 of file cbc_solver.cc.
References cyclus::Constraint::EQ, cyclus::Constraint::GT, cyclus::Constraint::GTEQ, cyclus::kConstraintEps, cyclus::Constraint::LT, and cyclus::Constraint::LTEQ.
Referenced by SetUpConstraints().
double cyclus::CBCSolver::ObjDirection (ObjectiveFunction::Ptr obj) [private]
set the objective direction
Definition at line 78 of file cbc_solver.cc.
References cyclus::ObjectiveFunction::MAX, and cyclus::ObjectiveFunction::MIN.
Referenced by Solve().
void cyclus::CBCSolver::PopulateSolution (CbcModel & agent, std::vector< Variable::Ptr > & variables) [private]
populate the solution in the variable vector
Definition at line 99 of file cbc_solver.cc.
References cyclus::Variable::INT.
Referenced by Solve().
void cyclus::CBCSolver::Print (int n_const, int n_vars) [private]
prints each other printing function
Definition at line 154 of file cbc_solver.cc.
References PrintConstraints(), PrintObjFunction(), and PrintVariables().
void cyclus::CBCSolver::PrintConstraints (int n_const, int n_vars) [private]
print constraint info
Definition at line 140 of file cbc_solver.cc.
References builder_.
Referenced by Print().
void cyclus::CBCSolver::PrintObjFunction (int n_vars) [private]
print objective function info
Definition at line 129 of file cbc_solver.cc.
References builder_.
Referenced by Print().
void cyclus::CBCSolver::PrintVariables (int n_const) [private]
print variables info
Definition at line 118 of file cbc_solver.cc.
References builder_.
Referenced by Print().
void cyclus::CBCSolver::SetUpConstraints (std::vector< Constraint::Ptr > & constraints) [private]
set up constraints
Definition at line 65 of file cbc_solver.cc.
References builder_, ConstraintBounds(), and cyclus::Solver::index_.
Referenced by Solve().
void cyclus::CBCSolver::SetUpVariablesAndObj (std::vector< Variable::Ptr > & variables, ObjectiveFunction::Ptr obj) [private]
set variable/objective function values
Definition at line 42 of file cbc_solver.cc.
References builder_, cyclus::GetIntBounds(), cyclus::GetLinBounds(), cyclus::Variable::INT, and cyclus::Variable::LINEAR.
Referenced by Solve().
void cyclus::CBCSolver::Solve (std::vector< Variable::Ptr > & variables, ObjectiveFunction::Ptr obj, std::vector< Constraint::Ptr > & constraints) [virtual]
Solve an Mixed-Integer Program.
Parameters:
variables A container of variables. The solution is preserved in the value() member.
obj A pointer to the objective function.
constraints A container of pointers to the problem's constraints.
Implements cyclus::Solver.
Definition at line 161 of file cbc_solver.cc.
References builder_, ObjDirection(), cyclus::Solver::PopulateIndices(), PopulateSolution(), SetUpConstraints(), SetUpVariablesAndObj(), and SolveAgent().
void cyclus::CBCSolver::SolveAgent (CbcModel & agent) [private]
solve the agent
Definition at line 92 of file cbc_solver.cc.
Referenced by Solve().
Member Data Documentation
CoinModel cyclus::CBCSolver::builder_ [private]
the agent builder
Definition at line 32 of file cbc_solver.h.
Referenced by PrintConstraints(), PrintObjFunction(), PrintVariables(), SetUpConstraints(), SetUpVariablesAndObj(), and Solve().
The documentation for this class was generated from the following files:
cbc_solver.h
cbc_solver.cc