CYCLUS: cyclus::Hdf5Back Class Reference
cyclus::Hdf5Back Class Reference
An Recorder backend that writes data to an hdf5 file.
#include <hdf5_back.h>
Public Member Functions
virtual void Flush ()
Flushes all buffered data in the backend to its final format/location.
Hdf5Back (std::string path)
Creates a new backend writing data to the specified file.
virtual std::string Name ()
Used to uniquely identify a backend - particularly if there are more than one in a simulation.
virtual void Notify (DatumList data)
Used to pass a list of new/collected Datum objects.
virtual ~Hdf5Back ()
cleans up resources and closes the file.
Private Member Functions
void CreateTable (Datum *d)
creates and initializes an hdf5 table
void FillBuf (char *buf, DatumList &group, size_t *sizes, size_t rowsize)
fill a contiguous memory buffer with data from group for writing to an hdf5 dataset.
void WriteGroup (DatumList &group)
write a group of Datum objects with the same title to their corresponding hdf5 dataset
Private Attributes
hid_t blob_type_
hid_t file_
An interface to a sqlite db managed by the SqliteBack class.
std::string path_
Stores the database's path+name, declared during construction.
hid_t string_type_
std::map< std::string, size_t * > tbl_offset_
std::map< std::string, size_t > tbl_size_
std::map< std::string, size_t * > tbl_sizes_
Detailed Description
An Recorder backend that writes data to an hdf5 file.
Identically named Datum objects have their data placed as rows in a single table. Handles the following datum value types: int, float, double, std::string, cyclus::Blob
Definition at line 16 of file hdf5_back.h.
Constructor & Destructor Documentation
cyclus::Hdf5Back::Hdf5Back (std::string path)
Creates a new backend writing data to the specified file.
Parameters:
path the file to write to. If it exists, it will be overwritten.
Definition at line 13 of file hdf5_back.cc.
References blob_type_, file_, path_, STR_SIZE, and string_type_.
cyclus::Hdf5Back::~Hdf5Back () [virtual]
cleans up resources and closes the file.
Definition at line 24 of file hdf5_back.cc.
References blob_type_, file_, Flush(), string_type_, tbl_offset_, and tbl_sizes_.
Member Function Documentation
void cyclus::Hdf5Back::CreateTable (Datum * d) [private]
creates and initializes an hdf5 table
Definition at line 60 of file hdf5_back.cc.
References blob_type_, file_, STR_SIZE, string_type_, tbl_offset_, tbl_size_, tbl_sizes_, cyclus::Datum::title(), and cyclus::Datum::vals().
Referenced by Notify().
void cyclus::Hdf5Back::FillBuf (char * buf, DatumList & group, size_t * sizes, size_t rowsize) [private]
fill a contiguous memory buffer with data from group for writing to an hdf5 dataset.
Definition at line 134 of file hdf5_back.cc.
References boost::spirit::basic_hold_any< Char >::cast(), boost::spirit::basic_hold_any< Char >::castsmallvoid(), and STR_SIZE.
Referenced by WriteGroup().
virtual void cyclus::Hdf5Back::Flush () [inline, virtual]
Flushes all buffered data in the backend to its final format/location.
Implements cyclus::RecBackend.
Definition at line 30 of file hdf5_back.h.
Referenced by ~Hdf5Back().
std::string cyclus::Hdf5Back::Name () [virtual]
Used to uniquely identify a backend - particularly if there are more than one in a simulation.
Implements cyclus::RecBackend.
Definition at line 56 of file hdf5_back.cc.
References path_.
void cyclus::Hdf5Back::Notify (DatumList data) [virtual]
Used to pass a list of new/collected Datum objects.
Implements cyclus::RecBackend.
Definition at line 39 of file hdf5_back.cc.
References CreateTable(), tbl_size_, and WriteGroup().
void cyclus::Hdf5Back::WriteGroup (DatumList & group) [private]
write a group of Datum objects with the same title to their corresponding hdf5 dataset
Definition at line 115 of file hdf5_back.cc.
References file_, FillBuf(), tbl_offset_, tbl_size_, and tbl_sizes_.
Referenced by Notify().
Member Data Documentation
hid_t cyclus::Hdf5Back::blob_type_ [private]
Definition at line 46 of file hdf5_back.h.
Referenced by CreateTable(), Hdf5Back(), and ~Hdf5Back().
hid_t cyclus::Hdf5Back::file_ [private]
An interface to a sqlite db managed by the SqliteBack class.
Definition at line 43 of file hdf5_back.h.
Referenced by CreateTable(), Hdf5Back(), WriteGroup(), and ~Hdf5Back().
std::string cyclus::Hdf5Back::path_ [private]
Stores the database's path+name, declared during construction.
Definition at line 49 of file hdf5_back.h.
Referenced by Hdf5Back(), and Name().
hid_t cyclus::Hdf5Back::string_type_ [private]
Definition at line 45 of file hdf5_back.h.
Referenced by CreateTable(), Hdf5Back(), and ~Hdf5Back().
std::map<std::string, size_t*> cyclus::Hdf5Back::tbl_offset_ [private]
Definition at line 51 of file hdf5_back.h.
Referenced by CreateTable(), WriteGroup(), and ~Hdf5Back().
std::map<std::string, size_t> cyclus::Hdf5Back::tbl_size_ [private]
Definition at line 53 of file hdf5_back.h.
Referenced by CreateTable(), Notify(), and WriteGroup().
std::map<std::string, size_t*> cyclus::Hdf5Back::tbl_sizes_ [private]
Definition at line 52 of file hdf5_back.h.
Referenced by CreateTable(), WriteGroup(), and ~Hdf5Back().
The documentation for this class was generated from the following files:
hdf5_back.h
hdf5_back.cc