CYCLUS: cyclus::Product Class Reference
cyclus::Product Class Reference
A Product is a general type of resource in the Cyclus simulation, and is a catch-all for non-standard resources.
#include <product.h>
Public Types
typedef boost::shared_ptr
< Product > Ptr
Public Member Functions
void Absorb (Product::Ptr other)
Absorbs the contents of the given 'other' resource into this resource.
virtual Resource::Ptr Clone () const
Returns an untracked (not part of the simulation) copy of the resource.
Product::Ptr Extract (double quantity)
Extracts the specified mass from this resource and returns it as a new product object with the same quality/type.
virtual Resource::Ptr ExtractRes (double quantity)
Splits the resource and returns the extracted portion as a new resource object.
virtual const std::string & quality () const
Returns the quality of this resource (e.g. bananas, human labor, water, etc.).
virtual double quantity () const
Returns the quantity of this resource with dimensions as specified by the return value of units().
virtual void Record (Context *ctx) const
Records the resource's state to the output database.
virtual int state_id () const
Returns 0 (for now).
virtual const ResourceType type () const
Returns Product::kType.
virtual std::string units () const
Returns the units this resource is based in (e.g. "kg").
Static Public Member Functions
static Ptr Create (Agent *creator, double quantity, std::string quality)
Creates a new product that is "live" and tracked.
static Ptr CreateUntracked (double quantity, std::string quality)
Creates a new product that does not actually exist as part of the simulation and is untracked.
Static Public Attributes
static const ResourceType kType = "Product"
Private Member Functions
Product (Context *ctx, double quantity, std::string quality)
Private Attributes
Context * ctx_
std::string quality_
double quantity_
ResTracker tracker_
Static Private Attributes
static int next_state_ = 1
static std::map< std::string, int > stateids_
Friends
class SimInit
Detailed Description
A Product is a general type of resource in the Cyclus simulation, and is a catch-all for non-standard resources.
It implements the Resource class interface in a simple way usable for things such as: bananas, man-hours, water, buying power, etc.
Definition at line 17 of file product.h.
Member Typedef Documentation
typedef boost::shared_ptr<Product> cyclus::Product::Ptr
Reimplemented from cyclus::Resource.
Definition at line 22 of file product.h.
Constructor & Destructor Documentation
cyclus::Product::Product (Context * ctx, double quantity, std::string quality) [private]
Parameters:
ctx the simulation context
quantity is a double indicating the quantity
quality the resource quality
Definition at line 79 of file product.cc.
Referenced by Clone(), Create(), CreateUntracked(), and Extract().
Member Function Documentation
void cyclus::Product::Absorb (Product::Ptr other)
Absorbs the contents of the given 'other' resource into this resource.
Exceptions:
ValueError 'other' resource is of different quality
Definition at line 50 of file product.cc.
References cyclus::ResTracker::Absorb(), quality(), quantity_, and tracker_.
Resource::Ptr cyclus::Product::Clone () const [virtual]
Returns an untracked (not part of the simulation) copy of the resource.
A cloned resource should never record anything in the output database.
Implements cyclus::Resource.
Definition at line 42 of file product.cc.
References cyclus::ResTracker::DontTrack(), cyclus::units::g, Product(), and tracker_.
Product::Ptr cyclus::Product::Create (Agent * creator, double quantity, std::string quality) [static]
Creates a new product that is "live" and tracked.
creator is a pointer to the agent creating the resource (usually will be the caller's "this" pointer). All future output data recorded will be done using the creator's context.
Definition at line 16 of file product.cc.
References cyclus::Datum::AddVal(), cyclus::Agent::context(), cyclus::Context::NewDatum(), next_state_, Product(), quality(), quantity(), cyclus::Datum::Record(), and stateids_.
Referenced by cyclus::SimInit::LoadProduct().
Product::Ptr cyclus::Product::CreateUntracked (double quantity, std::string quality) [static]
Creates a new product that does not actually exist as part of the simulation and is untracked.
Definition at line 34 of file product.cc.
References Product().
Product::Ptr cyclus::Product::Extract (double quantity)
Extracts the specified mass from this resource and returns it as a new product object with the same quality/type.
Exceptions:
ValueError tried to extract more than exists.
Definition at line 61 of file product.cc.
References ctx_, cyclus::ResTracker::Extract(), Product(), quality_, quantity(), quantity_, and tracker_.
Referenced by ExtractRes().
Resource::Ptr cyclus::Product::ExtractRes (double quantity) [virtual]
Splits the resource and returns the extracted portion as a new resource object.
Allows for things like ResourceBuff and Traders to split offers/requests of arbitrary resource implementation type.
Returns:
a new resource object with same state id and quantity == quantity
Implements cyclus::Resource.
Definition at line 74 of file product.cc.
References Extract().
virtual const std::string& cyclus::Product::quality () const [inline, virtual]
Returns the quality of this resource (e.g. bananas, human labor, water, etc.).
Definition at line 57 of file product.h.
References quality_.
Referenced by Absorb(), and Create().
virtual double cyclus::Product::quantity () const [inline, virtual]
Returns the quantity of this resource with dimensions as specified by the return value of units().
Implements cyclus::Resource.
Definition at line 52 of file product.h.
References quantity_.
Referenced by Create(), and Extract().
virtual void cyclus::Product::Record (Context * ctx) const [inline, virtual]
Records the resource's state to the output database.
This method should generally NOT record data accessible via the Resource class public methods (e.g. state_id, units, type, quantity).
Parameters:
ctx the simulation context used to record the data.
Implements cyclus::Resource.
Definition at line 48 of file product.h.
virtual int cyclus::Product::state_id () const [inline, virtual]
Returns 0 (for now).
Implements cyclus::Resource.
Definition at line 37 of file product.h.
virtual const ResourceType cyclus::Product::type () const [inline, virtual]
Returns Product::kType.
Implements cyclus::Resource.
Definition at line 42 of file product.h.
References kType.
virtual std::string cyclus::Product::units () const [inline, virtual]
Returns the units this resource is based in (e.g. "kg").
Implements cyclus::Resource.
Definition at line 50 of file product.h.
Friends And Related Function Documentation
friend class SimInit [friend]
Reimplemented from cyclus::Resource.
Definition at line 18 of file product.h.
Member Data Documentation
Context* cyclus::Product::ctx_ [private]
Definition at line 83 of file product.h.
Referenced by Extract().
const ResourceType cyclus::Product::kType = "Product" [static]
Definition at line 23 of file product.h.
Referenced by cyclus::SimInit::LoadResource(), and type().
int cyclus::Product::next_state_ = 1 [static, private]
Definition at line 81 of file product.h.
Referenced by Create(), cyclus::SimInit::LoadNextIds(), and cyclus::SimInit::Snapshot().
std::string cyclus::Product::quality_ [private]
Definition at line 84 of file product.h.
Referenced by Extract(), and quality().
double cyclus::Product::quantity_ [private]
Definition at line 85 of file product.h.
Referenced by Absorb(), Extract(), and quantity().
std::map< std::string, int > cyclus::Product::stateids_ [static, private]
Definition at line 80 of file product.h.
Referenced by Create(), and cyclus::SimInit::LoadProduct().
ResTracker cyclus::Product::tracker_ [private]
Definition at line 86 of file product.h.
Referenced by Absorb(), Clone(), and Extract().
The documentation for this class was generated from the following files:
product.h
product.cc