CYCLUS: cyclus::enrichment Namespace Reference
cyclus::enrichment Namespace Reference
Classes
class Assays
a simple container class for enrichment assays
Functions
double FeedQty (double product_qty, const Assays &assays)
inline double UraniumQty(Material::Ptr mat) { return UraniumQty(mat.get()); }
double SwuRequired (double product_qty, const Assays &assays)
double TailsQty (double product_qty, const Assays &assays)
double UraniumAssay (Material::Ptr mat)
double UraniumQty (Material::Ptr mat)
inline double UraniumAssay(Material::Ptr mat) { return UraniumAssay(mat.get()); }
double ValueFunc (double frac)
Function Documentation
double cyclus::enrichment::FeedQty (double product_qty, const Assays & assays)
inline double UraniumQty(Material::Ptr mat) { return UraniumQty(mat.get()); }
Parameters:
product_qty the amount of product Uranium
assays the assay of product, feed, and tails
Returns:
the quantity of feedstock required to make the product whose units match those of the given product
Definition at line 60 of file enrichment.cc.
References cyclus::enrichment::Assays::Feed(), cyclus::enrichment::Assays::Product(), and cyclus::enrichment::Assays::Tails().
Referenced by SwuRequired().
double cyclus::enrichment::SwuRequired (double product_qty, const Assays & assays)
Parameters:
product_qty the amount of product Uranium
assays the assay of product, feed, and tails
Returns:
the amount of swu required to enrich the product
Definition at line 97 of file enrichment.cc.
References cyclus::enrichment::Assays::Feed(), FeedQty(), cyclus::enrichment::Assays::Product(), cyclus::enrichment::Assays::Tails(), TailsQty(), and ValueFunc().
double cyclus::enrichment::TailsQty (double product_qty, const Assays & assays)
Parameters:
product_qty the amount of product Uranium
assays the assay of product, feed, and tails
Returns:
the quantity of tails resulting from enriching the product whose units match those of the given product
Definition at line 69 of file enrichment.cc.
References cyclus::enrichment::Assays::Feed(), cyclus::enrichment::Assays::Product(), and cyclus::enrichment::Assays::Tails().
Referenced by SwuRequired().
double cyclus::enrichment::UraniumAssay (Material::Ptr mat)
Parameters:
mat the material inquired about
Returns:
the atom percent of U-235 w.r.t Uranium in a material
Definition at line 35 of file enrichment.cc.
References cyclus::MatQuery::atom_frac(), cyclus::LEV_DEBUG1, and LOG.
double cyclus::enrichment::UraniumQty (Material::Ptr mat)
inline double UraniumAssay(Material::Ptr mat) { return UraniumAssay(mat.get()); }
Parameters:
mat the material inquired about
Returns:
the quantity of uranium in a material whose units match those of the given material
Definition at line 54 of file enrichment.cc.
References cyclus::MatQuery::mass().
double cyclus::enrichment::ValueFunc (double frac)
Parameters:
frac the fraction input, this will throw if the fraction value is not in [0,1)
Returns:
the value function for a given fraction in [0,1)
Definition at line 78 of file enrichment.cc.
Referenced by SwuRequired().