CYCLUS: cyclus Namespace Reference
cyclus Namespace Reference
taken directly from OsiSolverInterface.cpp on 2/17/14 from https://projects.coin-or.org/Osi/browser/trunk.
Namespaces
namespace compmath
Contains functions for performing fundamental operations on CompMap's.
namespace enrichment
namespace units
namespace version
Classes
class Agent
The abstract base class used by all types of agents that live and interact in a simulation.
struct Arc
by convention, arc.first == request node (unode), arc.second == bid node (vnode)
class BasicFunctionFactory
a concrete factory that can provide access to basic symbolic functions
class Bid
A Bid encapsulates all the information required to communicate a bid response to a request for a resource, including the resource bid and the bidder.
class BidPortfolio
A BidPortfolio is a collection of bids as responses to requests for resources and associated constraints on those bids.
class Blob
A type to represent variable-length array of bytes for dumping to a cyclus output database.
class Builder
a mixin to provide information about commodity producers that can be built
class BuildingManager
The BuildingManager class is a managing entity that makes decisions about which objects to build given certain conditions.
struct BuildOrder
a struct for a build order: the number of producers to build
class CapacityConstraint
A CapacityConstraint provides an ability to determine an agent's constraints on resource allocation given a capacity.
class CastError
For failed casts that shouldn't.
class CBCSolver
the coin branch-and-cut solver, see https://projects.coin-or.org/Cbc.
struct CommodInfo
a container to hold information about a commodity
class Commodity
a simple class defining a commodity; it is currently super simple.
struct CommodityCompare
a comparator so that commodities may be used in maps we do not care how they are compared, only that they can be
class CommodityInformation
a simple container class to hold commodity information the supply of a commodity the demand function the producers of a commodity
class CommodityProducer
a mixin to provide information about produced commodities
class CommodityProducerManager
a mixin to provide information about commodity producers
class CommodityRecipeContext
a CommodityRecipeContext contains relationships between commodities, recipes and resources
struct CommodMap
class Composition
An immutable object responsible for holding a nuclide composition.
class Cond
Represents a condition used to filter rows returned by a query.
class CondInjector
Wrapper class for QueryableBackends that injects a set of Cond's into every query before being executed.
class Constraint
derived class for constraints
class Context
A simulation context provides access to necessary simulation-global functions and state.
class Converter
a simple interface for converting resource objects to unit capacities
class CsvBack
An Recorder backend that writes data to a collection of csv files.
class CycArithmetic
CycArithmetic is a toolkit for arithmetic.
class Datum
class DbInit
DbInit provides an interface for agents to record data to the output db that automatically injects the agent's id and current timestep alongside all recorded data.
class Decayer
class Dummy
class DynamicModule
class Env
An environment utility to help locate files and find environment settings.
class Error
A generic mechanism to manually manage exceptions.
class ExchangeContext
The ExchangeContext is designed to provide an ease-of-use interface for querying and reaggregating information regarding requests and bids of a resource exchange.
class ExchangeGraph
An ExchangeGraph is a resource-neutral representation of a ResourceExchange.
class ExchangeManager
The ExchangeManager is designed to house all of the internals involved in executing a resource exchange.
class ExchangeNode
ExchangeNodes are used in ExchangeGraphs to house information about a given translated Bid or Request.
class ExchangeNodeGroup
A ExchangeNodeGroup is a collection of ExchangeNodes, and is the ExchangeGraph representation of a BidPortfolio or RequestPortfolio.
class ExchangeSolver
a very simple interface for solving translated resource exchanges
class ExchangeTranslationContext
An ExchangeTranslationContext is a simple holder class for any information needed to translate a ResourceExchange to and from an ExchangeGraph.
class ExchangeTranslator
An ExchangeTranslator facilitates translation from a resource specific exchange to a resource-neutral exchange, upon which generic solvers can be applied.
struct ExclusiveStatus
information container for the exclusive status of an arc
class ExpFunctionFactory
a concrete factory for exponential functions
class ExponentialFunction
exponential functions f(x) = constant_ * exp (exponent_ * x) + intercept_
class Facility
The Facility class is the abstract class/interface used by all facility agents.
class FullBackend
Interface implemented by backends that support recording and querying.
class Function
function base class
class GreedyPreconditioner
A GreedyPreconditioner conditions an ExchangeGraph for a GreedySolver by ordering the RequestGroups and ExchangeNodes within each RequestGroup weighted by their commodity's importance.
class GreedySolver
The GreedySolver provides the implementation for a "greedy" solution to a resource exchange graph.
class Hdf5Back
An Recorder backend that writes data to an hdf5 file.
class InfileTree
A class for extracting information from a given XML parser.
class Institution
The Institution class is the abstract class/interface used by all institution agents.
class IntegerVariable
derived class for integer variables
class IntrusiveBase
IntrusiveBase provides a base class that fulfulls basic requirements for a (sub) class to be used in a boost::intrusive_ptr.
class IOError
for failed reading/writing to files, network connections, etc..
class KeyError
For failed retrieval/insertion of key-based data into/from data structures.
class LinearFunction
linear functions f(x) = slope_ * x + intercept_
class LinearVariable
derived class for linear variables
class LinFunctionFactory
a concrete factory for linear functions
class LMatrix
class Logger
A logging tool providing finer grained control over standard output for debugging and other purposes.
class Material
The material class is primarily responsible for enabling basic material manipulation while helping enforce mass conservation.
class MatQuery
A class that provides convenience methods for querying a material's properties.
class ObjectiveFunction
derived class for objective functions
class PiecewiseFunction
piecewise function f(x) for all x in [lhs,rhs] 0 otherwise
class PiecewiseFunctionFactory
a concrete factory for piecewise functions
class PrefixInjector
Wrapper class for QueryableBackends that injects prefix in front of the title/table for every query before being executed.
struct PrefMap
struct ProblemInstance
a struct for a problem instance
class Producer
a small class defining a producer a producer is associated with: a commodity a capactiy for production of commodity a cost of production of commodity
class Product
A Product is a general type of resource in the Cyclus simulation, and is a catch-all for non-standard resources.
class ProgSolver
The ProgSolver provides the implementation for a mathematical programming solution to a resource exchange graph.
class ProgTranslator
a helper class to translate a product exchange into a mathematical program.
class QueryableBackend
Interface implemented by backends that support rudimentary querying.
class QueryResult
Meta data and results of a query.
class RecBackend
An abstract base class for listeners (e.g.
class Recorder
Collects and manages output data generation for the cyclus core and agents during a simulation.
class Region
The Region class is the abstract class/interface used by all region agents.
class RelaxNGValidator
RelaxNGValidator.
class Request
A Request encapsulates all the information required to communicate the needs of an agent in the Dynamic Resource Exchange, including the commodity it needs as well as a resource specification for that commodity.
class RequestGroup
A RequestGroup is a specific ExchangeNodeGroup with a notion of an total requested quantity.
class RequestPortfolio
A RequestPortfolio is a group of (possibly constrainted) requests for resources.
class Resource
Resource defines an abstract interface implemented by types that are offered, requested, and transferred between simulation agents.
class ResourceBuff
ResourceBuff is a helper function that provides semi-automated management of resource buffers (e.g.
class ResourceExchange
The ResourceExchange class manages the communication for the supply and demand of resources in a simulation.
class ResTracker
Tracks and records the state and parent-child relationships of resources as they are changed.
struct SecondLT
a less-than comparison for pairs
class SimInfo
Container for a static simulation-global parameters that both describe the simulation and affect its behavior.
class SimInit
Handles initialization of a simulation from the output database.
class Solver
abstract base class for different types of constraint program solvers
class SolverFactory
A factory class that, given a configuration, returns a Coin::OsiSolverInterface for a solver.
class SolverInterface
A general interface class for all derived optim solvers to set up and solve a constraint program.
class SqliteBack
An Recorder backend that writes data to an sqlite database.
class SqliteDb
class StateError
For failed object state expectations.
class StateWrangler
An abjstract interface that must be implemented by all simulation agents and all agent member variables that have unexported internal state.
class SupplyDemandManager
This is a manager class that manages a set of commodities.
class SymbFunctionFactory
An abstract factory for pointers to symbolic functions.
class SymFunction
abstract base class for symbolic functions
class TimeListener
The TimeListener class is an inheritable class for any Agent that requires knowlege of ticks and tocks.
class Timer
Controls simulation timestepping and inter-timestep phases.
class Trade
A Trade is a simple container that associates a request for a resource with a bid for that resource.
struct TradeExecutionContext
class TradeExecutor
The TradeExecutor is an object whose task is to execute a collection of Trades.
class Trader
A simple API for agents that wish to exchange resources in the simulation.
class TrivialConverter
The default converter returns the resource's quantity.
class UniformTaylor
A class that solves the matrix exponential problem using the Taylor Series with Uniformization method.
class ValidationError
For validating files received via IO.
class ValueError
For values that are too big, too small, etc.
class Variable
Variable base class.
class XMLFileLoader
Handles initialization of a database with information from a cyclus xml input file.
class XMLFlatLoader
a class that encapsulates the methods needed to load input to a cyclus simulation from xml
class XMLParser
A helper class to hold xml file data and provide automatic validation.
Typedefs
typedef Agent * AgentCtor (Context *)
typedef std::map< Nuc, double > CompMap
a raw definition of nuclides and corresponding (dimensionless quantities).
typedef std::vector< Datum * > DatumList
typedef boost::singleton_pool
< Datum, sizeof(Datum)> DatumPool
typedef std::map< int,
std::vector< std::pair< int,
double > > > DaughtersMap
A map type to represent all of the daughter nuclides tracked.
typedef std::map< std::string,
std::vector< Resource::Ptr > > Inventories
map<internal-inventory-name, vector<resources-inside-inventory> >
typedef std::vector< std::string > LineList
typedef std::vector
< Resource::Ptr > Manifest
typedef std::pair< Arc, double > Match
typedef LMatrix Matrix
typedef int Nuc
typedef std::vector< int > NucList
typedef std::map< int,
std::pair< int, double > > ParentMap
A map type to represent all of the parent nuclides tracked.
typedef std::set< std::string >
::iterator PrototypeIterator
typedef std::set< std::string > PrototypeSet
typedef std::vector
< boost::spirit::hold_any > QueryRow
typedef std::string ResourceType
typedef std::vector< std::string > StrList
typedef LMatrix Vector
Enumerations
enum LogLevel {
LEV_ERROR, LEV_WARN, LEV_INFO1, LEV_INFO2,
LEV_INFO3, LEV_INFO4, LEV_INFO5, LEV_DEBUG1,
LEV_DEBUG2, LEV_DEBUG3, LEV_DEBUG4, LEV_DEBUG5
}
categorical (verbosity) levels for log statements.
Functions
template<class T >
static void AcceptTrades (Trader *trader, const std::vector< std::pair< Trade< T >, typename T::Ptr > > &responses)
template<>
void AcceptTrades (Trader *trader, const std::vector< std::pair< Trade< Material >, typename Material::Ptr > > &responses)
template<>
void AcceptTrades (Trader *trader, const std::vector< std::pair< Trade< Product >, typename Product::Ptr > > &responses)
template<class T >
void AddBid (ExchangeTranslationContext< T > &translation_ctx, typename Bid< T >::Ptr b, ExchangeNode::Ptr n)
Adds a bid-node mapping.
template<class T >
void AddRequest (ExchangeTranslationContext< T > &translation_ctx, typename Request< T >::Ptr r, ExchangeNode::Ptr n)
Adds a request-node mapping.
template<class T >
static void AdjustPrefs (Agent *m, typename PrefMap< T >::type &prefs)
Preference adjustment method helpers to convert from templates to the Agent inheritance hierarchy.
static void AdjustPrefs (Agent *m, PrefMap< Material >::type &prefs)
static void AdjustPrefs (Agent *m, PrefMap< Product >::type &prefs)
static void AdjustPrefs (Trader *t, PrefMap< Material >::type &prefs)
static void AdjustPrefs (Trader *t, PrefMap< Product >::type &prefs)
bool AlmostEq (double d1, double d2)
returns true if two doubles are within eps() of one another
template<class T >
Trade< T > BackTranslateMatch (const ExchangeTranslationContext< T > &translation_ctx, const Match &match)
simple translation from a Match to a Trade, given internal state
std::string BuildFlatMasterSchema (std::string schema_path)
Builds and returns a master cyclus input xml schema defining a flat prototype and instance structure that includes the sub-schemas defined by all installed cyclus modules (e.g.
std::string BuildMasterSchema (std::string schema_path)
Builds and returns a master cyclus input xml schema that includes the sub-schemas defined by all installed cyclus modules (e.g.
double Capacity (const Arc &a)
the capacity of the arc
double Capacity (ExchangeNode &n, const Arc &a)
the capacity of a node
double Capacity (ExchangeNode::Ptr pn, const Arc &a)
int differentAgent (OsiSolverInterface &lhs, OsiSolverInterface &rhs, bool ignoreNames=true)
Check two agents against each other.
double eps ()
a generic epsilon value
double eps_rsrc ()
an epsilon value to be used by resources
std::pair< int, int > GetIntBounds (Variable::Ptr v)
std::pair< double, double > GetLinBounds (Variable::Ptr v)
template<class T >
T GetOptionalQuery (InfileTree *qe, std::string query, T default_val)
a query method for optional parameters
template<class T >
static void GetTradeResponses (TradeExecutionContext< T > &trade_ctx)
queries each supplier for the responses to thier matched trade and populates trades_by_requester_ and all_trades_ with the results
template<class T >
void GroupTradesBySupplier (TradeExecutionContext< T > &trade_ctx, const std::vector< Trade< T > > &trades)
populates suppliers_, requesters_, and trades_by_supplier_
double GroupWeight (RequestGroup::Ptr g, std::map< std::string, double > *weights)
bool HasInt (OsiSolverInterface *si)
LMatrix identity (int n)
bool IsNegative (double d)
returns true if a double is less than 0 - eps()
void LoadStringstreamFromFile (std::stringstream &stream, std::string file)
Reads the given file path into the passed stream.
template<typename Map >
bool map_compare (Map const &lhs, Map const &rhs)
Material::Ptr NewBlankMaterial (double qty)
Creates and returns a new material with the specified quantity and a default, meaningless composition.
double NodeWeight (ExchangeNode::Ptr n, std::map< std::string, double > *weights)
LMatrix operator* (const LMatrix &lhs, const LMatrix &rhs)
LMatrix operator* (const long double k, const LMatrix &A)
LMatrix operator* (const LMatrix &A, const long double k)
LMatrix operator+ (const LMatrix &lhs, const LMatrix &rhs)
LMatrix operator- (const LMatrix &lhs, const LMatrix &rhs)
bool operator< (const Arc &l, const Arc &r)
template<class T >
bool operator< (const CapacityConstraint< T > &lhs, const CapacityConstraint< T > &rhs)
CapacityConstraint-CapacityConstraint comparison operator, allows usage in ordered containers.
bool operator== (const ExchangeNode &lhs, const ExchangeNode &rhs)
ExchangeNode-ExchangeNode equality operator.
template<class T >
bool operator== (const cyclus::Trade< T > &lhs, const cyclus::Trade< T > &rhs)
Trade-Trade equality operator.
bool operator== (const Arc &l, const Arc &r)
template<class T >
bool operator== (const CapacityConstraint< T > &lhs, const CapacityConstraint< T > &rhs)
CapacityConstraint-CapacityConstraint equality operator.
LMatrix operator^ (const LMatrix &A, const int k)
template<class T >
static void PopulateTradeResponses (Trader *trader, const std::vector< Trade< T > > &trades, std::vector< std::pair< Trade< T >, typename T::Ptr > > &responses)
template<>
void PopulateTradeResponses< Material > (Trader *trader, const std::vector< Trade< Material > > &trades, std::vector< std::pair< Trade< Material >, Material::Ptr > > &responses)
template<>
void PopulateTradeResponses< Product > (Trader *trader, const std::vector< Trade< Product > > &trades, std::vector< std::pair< Trade< Product >, Product::Ptr > > &responses)
template<class T >
static std::set< typename
BidPortfolio< T >::Ptr > QueryBids (Trader *t, const typename CommodMap< T >::type &map)
template<>
std::set< BidPortfolio
< Material >::Ptr > QueryBids< Material > (Trader *t, const CommodMap< Material >::type &map)
template<>
std::set< BidPortfolio
< Product >::Ptr > QueryBids< Product > (Trader *t, const CommodMap< Product >::type &map)
template<class T >
static std::set< typename
RequestPortfolio< T >::Ptr > QueryRequests (Trader *t)
template<>
std::set< RequestPortfolio
< Material >::Ptr > QueryRequests< Material > (Trader *t)
template<>
std::set< RequestPortfolio
< Product >::Ptr > QueryRequests< Product > (Trader *t)
Composition::Ptr ReadRecipe (InfileTree *qe)
Creates a composition from the recipe in the query engine.
bool ReqPrefComp (const Arc &l, const Arc &r)
A comparison function for sorting a container of Arcs by the requester's (unode's) preference, in decensing order (i.e., most preferred Arc first)
template<class T >
std::vector< typename T::Ptr > ResCast (Manifest rs)
Casts a vector of Resources into a vector of a specific resource type T.
template<class T >
T::Ptr ResCast (Resource::Ptr r)
Casts a Resource::Ptr into a pointer of a specific resource type T.
template<class T >
static void SendTradeResources (TradeExecutionContext< T > &trade_ctx)
void SolveProg (OsiSolverInterface *si)
std::vector< std::string > split (const std::string &s, char delim)
std::string StringFromHex (const std::string &in)
std::string StringToHex (const std::string &s)
template<class T >
Arc TranslateArc (const ExchangeTranslationContext< T > &translation_ctx, typename Bid< T >::Ptr bid)
translates an arc given a bid and subsequent data, and also updates the unit capacities for the associated nodes on the arc
template<class T >
ExchangeNodeGroup::Ptr TranslateBidPortfolio (ExchangeTranslationContext< T > &translation_ctx, const typename BidPortfolio< T >::Ptr bp)
translates a bid portfolio by adding bid nodes and accounting for capacities.
template<typename T >
void TranslateCapacities (typename T::Ptr offer, const typename std::set< CapacityConstraint< T > > &constr, ExchangeNode::Ptr n, const Arc &a)
updates a node's unit capacities given, a target resource and constraints
template<class T >
RequestGroup::Ptr TranslateRequestPortfolio (ExchangeTranslationContext< T > &translation_ctx, const typename RequestPortfolio< T >::Ptr rp)
translates a request portfolio by adding request nodes and accounting for capacities.
void UpdateCapacity (ExchangeNode &n, const Arc &a, double qty)
updates the capacity of a given ExchangeNode (i.e., its max_qty and the capacities of its ExchangeNodeGroup)
void UpdateCapacity (ExchangeNode::Ptr pn, const Arc &a, double qty)
Variables
static double const kBuffInfinity = std::numeric_limits<double>::max()
static const double kConstraintEps = 1e-08
epsilon value to turn determine difference between constraint values
static unsigned int const kDefaultDumpCount = 500
default number of Datum objects to collect before flushing to backends.
static const int kIntBoundLimit = std::numeric_limits<int>::max()
maximum (+ or -) value for an integer variable
static const double kLinBoundLimit = std::numeric_limits<double>::max()
maximum (+ or -) value for a linear variable
static const double kModifierLimit = pow(10, 10)
maximum value for a function modifier (i.e., a_i for variable x_i)
Detailed Description
taken directly from OsiSolverInterface.cpp on 2/17/14 from https://projects.coin-or.org/Osi/browser/trunk.
institution.cc
a collection of tools that are standard-library like
Thanks to John Forrest for his assistance! Some small changes have been made to the original file.
Typedef Documentation
typedef Agent* cyclus::AgentCtor(Context *)
Definition at line 13 of file dynamic_module.h.
typedef std::map<Nuc, double> cyclus::CompMap
a raw definition of nuclides and corresponding (dimensionless quantities).
Definition at line 14 of file composition.h.
typedef std::vector< Datum * > cyclus::DatumList
Definition at line 13 of file rec_backend.h.
typedef boost::singleton_pool<Datum, sizeof(Datum)> cyclus::DatumPool
Definition at line 10 of file datum.cc.
typedef std::map<int, std::vector<std::pair<int, double> > > cyclus::DaughtersMap
A map type to represent all of the daughter nuclides tracked.
The key for this map type is the decay matrix column associated with the parent, and the value is a vector of pairs of all the daughters for that parent. Each of the daughters are represented by a pair that contains the daughter's Nuc number and its branching ratio.
Definition at line 25 of file decayer.h.
typedef std::map<std::string, std::vector<Resource::Ptr> > cyclus::Inventories
map<internal-inventory-name, vector<resources-inside-inventory> >
Definition at line 25 of file agent.h.
typedef std::vector<std::string> cyclus::LineList
Definition at line 16 of file csv_back.h.
typedef std::vector<Resource::Ptr> cyclus::Manifest
Definition at line 20 of file resource_buff.h.
typedef std::pair<Arc, double> cyclus::Match
Definition at line 171 of file exchange_graph.h.
typedef LMatrix cyclus::Matrix
Definition at line 17 of file use_matrix_lib.h.
typedef int cyclus::Nuc
Definition at line 9 of file composition.h.
typedef std::vector<int> cyclus::NucList
Definition at line 27 of file decayer.h.
typedef std::map< int, std::pair<int, double> > cyclus::ParentMap
A map type to represent all of the parent nuclides tracked.
The key for this map type is the parent's Nuc number, and the value is a pair that contains the corresponding decay matrix column and decay constant associated with that parent.
Definition at line 18 of file decayer.h.
typedef std::set<std::string>::iterator cyclus::PrototypeIterator
Definition at line 19 of file institution.h.
typedef std::set<std::string> cyclus::PrototypeSet
Definition at line 15 of file institution.h.
typedef std::vector<boost::spirit::hold_any> cyclus::QueryRow
Definition at line 27 of file query_backend.h.
typedef std::string cyclus::ResourceType
Definition at line 11 of file resource.h.
typedef std::vector<std::string> cyclus::StrList
Definition at line 11 of file sqlite_db.h.
typedef LMatrix cyclus::Vector
Definition at line 22 of file use_matrix_lib.h.
Enumeration Type Documentation
enum cyclus::LogLevel
categorical (verbosity) levels for log statements.
Enumerator:
LEV_ERROR
Use for errors that require agent code or input file modification (use extremely sparingly)
LEV_WARN
Use to report questionable simulation state (use extremely sparingly)
LEV_INFO1
Information helpful for simulation users and developers alike - least verbose.
LEV_INFO2
Information helpful for simulation users and developers alike.
LEV_INFO3
Information helpful for simulation users and developers alike.
LEV_INFO4
Information helpful for simulation users and developers alike.
LEV_INFO5
Information helpful for simulation users and developers alike - most verbose.
LEV_DEBUG1
debugging information - least verbose
LEV_DEBUG2
debugging information
LEV_DEBUG3
debugging information
LEV_DEBUG4
debugging information
LEV_DEBUG5
debugging information - most verbose
Definition at line 54 of file logger.h.
Function Documentation
template<class T > static void cyclus::AcceptTrades (Trader * trader, const std::vector< std::pair< Trade< T >, typename T::Ptr > > & responses) [inline, static]
Definition at line 77 of file trader_management.h.
Referenced by SendTradeResources().
template<> void cyclus::AcceptTrades (Trader * trader, const std::vector< std::pair< Trade< Material >, typename Material::Ptr > > & responses) [inline]
Definition at line 84 of file trader_management.h.
References cyclus::Trader::AcceptMatlTrades().
template<> void cyclus::AcceptTrades (Trader * trader, const std::vector< std::pair< Trade< Product >, typename Product::Ptr > > & responses) [inline]
Definition at line 92 of file trader_management.h.
References cyclus::Trader::AcceptProductTrades().
template<class T > void cyclus::AddBid (ExchangeTranslationContext< T > & translation_ctx, typename Bid< T >::Ptr b, ExchangeNode::Ptr n) [inline]
Adds a bid-node mapping.
Definition at line 126 of file exchange_translator.h.
References cyclus::ExchangeTranslationContext< T >::bid_to_node, and cyclus::ExchangeTranslationContext< T >::node_to_bid.
Referenced by TranslateBidPortfolio().
template<class T > void cyclus::AddRequest (ExchangeTranslationContext< T > & translation_ctx, typename Request< T >::Ptr r, ExchangeNode::Ptr n) [inline]
Adds a request-node mapping.
Definition at line 118 of file exchange_translator.h.
References cyclus::ExchangeTranslationContext< T >::node_to_request, and cyclus::ExchangeTranslationContext< T >::request_to_node.
Referenced by TranslateRequestPortfolio().
template<class T > static void cyclus::AdjustPrefs (Agent * m, typename PrefMap< T >::type & prefs) [inline, static]
Preference adjustment method helpers to convert from templates to the Agent inheritance hierarchy.
Definition at line 22 of file resource_exchange.h.
Referenced by cyclus::ResourceExchange< T >::AdjustPrefs_().
static void cyclus::AdjustPrefs (Agent * m, PrefMap< Material >::type & prefs) [inline, static]
Definition at line 23 of file resource_exchange.h.
References cyclus::Agent::AdjustMatlPrefs().
static void cyclus::AdjustPrefs (Agent * m, PrefMap< Product >::type & prefs) [inline, static]
Definition at line 27 of file resource_exchange.h.
References cyclus::Agent::AdjustProductPrefs().
static void cyclus::AdjustPrefs (Trader * t, PrefMap< Material >::type & prefs) [inline, static]
Definition at line 31 of file resource_exchange.h.
References cyclus::Trader::AdjustMatlPrefs().
static void cyclus::AdjustPrefs (Trader * t, PrefMap< Product >::type & prefs) [inline, static]
Definition at line 35 of file resource_exchange.h.
References cyclus::Trader::AdjustProductPrefs().
bool cyclus::AlmostEq (double d1, double d2) [inline]
returns true if two doubles are within eps() of one another
Definition at line 24 of file cyc_limits.h.
References eps().
template<class T > Trade<T> cyclus::BackTranslateMatch (const ExchangeTranslationContext< T > & translation_ctx, const Match & match)
simple translation from a Match to a Trade, given internal state
Definition at line 244 of file exchange_translator.h.
References cyclus::Trade< T >::amt, cyclus::Trade< T >::bid, cyclus::ExchangeTranslationContext< T >::node_to_bid, cyclus::ExchangeTranslationContext< T >::node_to_request, and cyclus::Trade< T >::request.
Referenced by cyclus::ExchangeTranslator< T >::BackTranslateSolution().
std::string cyclus::BuildFlatMasterSchema (std::string schema_path)
Builds and returns a master cyclus input xml schema defining a flat prototype and instance structure that includes the sub-schemas defined by all installed cyclus modules (e.g.
facility agents). This is used to validate simulation input files.
Definition at line 16 of file xml_flat_loader.cc.
References cyclus::Context::DelAgent(), cyclus::Env::ListModules(), LoadStringstreamFromFile(), cyclus::DynamicModule::Make(), and cyclus::Agent::schema().
Referenced by cyclus::XMLFlatLoader::master_schema().
std::string cyclus::BuildMasterSchema (std::string schema_path)
Builds and returns a master cyclus input xml schema that includes the sub-schemas defined by all installed cyclus modules (e.g.
facility agents). This is used to validate simulation input files.
Definition at line 39 of file xml_file_loader.cc.
References cyclus::Context::DelAgent(), cyclus::Agent::kind(), cyclus::Env::ListModules(), LoadStringstreamFromFile(), cyclus::DynamicModule::Make(), and cyclus::Agent::schema().
Referenced by cyclus::XMLFileLoader::master_schema().
double cyclus::Capacity (const Arc & a)
the capacity of the arc
Exceptions:
StateError if either ExchangeNode does not have a ExchangeNodeGroup
Parameters:
a the arc
Returns:
The minimum of the unode and vnode's capacities
Definition at line 36 of file exchange_graph.cc.
References CLOG, cyclus::Arc::first, LEV_DEBUG1, and cyclus::Arc::second.
Referenced by Capacity(), and cyclus::GreedySolver::GreedilySatisfySet_().
double cyclus::Capacity (ExchangeNode & n, const Arc & a)
the capacity of a node
Exceptions:
StateError if ExchangeNode does not have a ExchangeNodeGroup
Parameters:
n the node
Returns:
The minimum of the node's nodegroup capacities / the node's unit capacities, or the ExchangeNode's remaining qty -- whichever is smaller.
Definition at line 49 of file exchange_graph.cc.
References cyclus::ExchangeNodeGroup::capacities(), CLOG, cyclus::ExchangeNode::group, LEV_DEBUG1, cyclus::ExchangeNode::max_qty, cyclus::ExchangeNode::qty, and cyclus::ExchangeNode::unit_capacities.
double cyclus::Capacity (ExchangeNode::Ptr pn, const Arc & a)
Definition at line 80 of file exchange_graph.cc.
References Capacity().
int cyclus::differentAgent (OsiSolverInterface & lhs, OsiSolverInterface & rhs, bool ignoreNames = true)
Check two agents against each other.
Return nonzero if different. Ignore names if that set. (Note initial version does not check names) May modify both agents by cleaning up
Definition at line 21 of file coin_helpers.cc.
double cyclus::eps () [inline]
a generic epsilon value
Definition at line 9 of file cyc_limits.h.
Referenced by AlmostEq(), cyclus::Material::Decay(), cyclus::ProgTranslator::FromProg(), cyclus::GreedySolver::GreedilySatisfySet_(), and IsNegative().
double cyclus::eps_rsrc () [inline]
an epsilon value to be used by resources
Definition at line 14 of file cyc_limits.h.
Referenced by cyclus::ResourceBuff::Push(), cyclus::ResourceBuff::PushAll(), and cyclus::ResourceBuff::set_capacity().
std::pair< int, int > cyclus::GetIntBounds (Variable::Ptr v)
Returns:
a pair of integers representing the lower and upper bounds of an integer variable
Definition at line 133 of file variable.cc.
References cyclus::IntegerVariable::lbound_val(), and cyclus::IntegerVariable::ubound_val().
Referenced by cyclus::CBCSolver::SetUpVariablesAndObj().
std::pair< double, double > cyclus::GetLinBounds (Variable::Ptr v)
Returns:
a pair of doubles representing the lower and upper bounds of a linear variable
Definition at line 139 of file variable.cc.
References cyclus::LinearVariable::lbound_val(), and cyclus::LinearVariable::ubound_val().
Referenced by cyclus::CBCSolver::SetUpVariablesAndObj().
template<class T > T cyclus::GetOptionalQuery (InfileTree * qe, std::string query, T default_val) [inline]
a query method for optional parameters
Parameters:
qe the query engine to use
query the query to be made
default_val the default value to use
Returns:
either return the optional value if it exists or return the default value
Definition at line 86 of file infile_tree.h.
References cyclus::InfileTree::GetString(), and cyclus::InfileTree::NMatches().
template<class T > static void cyclus::GetTradeResponses (TradeExecutionContext< T > & trade_ctx) [static]
queries each supplier for the responses to thier matched trade and populates trades_by_requester_ and all_trades_ with the results
Definition at line 118 of file trade_executor.h.
References cyclus::TradeExecutionContext< T >::all_trades, PopulateTradeResponses(), cyclus::TradeExecutionContext< T >::suppliers, cyclus::TradeExecutionContext< T >::trades_by_requester, and cyclus::TradeExecutionContext< T >::trades_by_supplier.
Referenced by cyclus::TradeExecutor< T >::ExecuteTrades().
template<class T > void cyclus::GroupTradesBySupplier (TradeExecutionContext< T > & trade_ctx, const std::vector< Trade< T > > & trades)
populates suppliers_, requesters_, and trades_by_supplier_
Definition at line 105 of file trade_executor.h.
References cyclus::TradeExecutionContext< T >::requesters, cyclus::TradeExecutionContext< T >::suppliers, and cyclus::TradeExecutionContext< T >::trades_by_supplier.
Referenced by cyclus::TradeExecutor< T >::ExecuteTrades().
double cyclus::GroupWeight (RequestGroup::Ptr g, std::map< std::string, double > * weights)
Returns:
average RequestGroup weight
Definition at line 94 of file greedy_preconditioner.cc.
References NodeWeight().
Referenced by cyclus::GreedyPreconditioner::Condition().
bool cyclus::HasInt (OsiSolverInterface * si)
Definition at line 29 of file solver_factory.cc.
Referenced by SolveProg().
LMatrix cyclus::identity (int n)
Definition at line 284 of file l_matrix.cc.
References cyclus::LMatrix::SetElement().
Referenced by cyclus::UniformTaylor::MatrixExpSolver().
bool cyclus::IsNegative (double d) [inline]
returns true if a double is less than 0 - eps()
Definition at line 19 of file cyc_limits.h.
References eps().
Referenced by UpdateCapacity().
void cyclus::LoadStringstreamFromFile (std::stringstream & stream, std::string file)
Reads the given file path into the passed stream.
Definition at line 28 of file xml_file_loader.cc.
Referenced by BuildFlatMasterSchema(), BuildMasterSchema(), and cyclus::XMLFileLoader::XMLFileLoader().
template<typename Map > bool cyclus::map_compare (Map const & lhs, Map const & rhs)
Definition at line 20 of file cyc_std.h.
Referenced by cyclus::CommodityRecipeContext::operator==().
Material::Ptr cyclus::NewBlankMaterial (double qty)
Creates and returns a new material with the specified quantity and a default, meaningless composition.
This is intended only for testing purposes.
Definition at line 169 of file material.cc.
References cyclus::Composition::CreateFromMass(), and cyclus::Material::CreateUntracked().
double cyclus::NodeWeight (ExchangeNode::Ptr n, std::map< std::string, double > * weights)
Returns:
the node's weight given the node and commodity weight
Definition at line 106 of file greedy_preconditioner.cc.
References CLOG, and LEV_DEBUG5.
Referenced by GroupWeight(), and cyclus::GreedyPreconditioner::NodeComp().
LMatrix cyclus::operator* (const LMatrix & lhs, const LMatrix & rhs)
Definition at line 226 of file l_matrix.cc.
LMatrix cyclus::operator* (const long double k, const LMatrix & A)
Definition at line 234 of file l_matrix.cc.
References cyclus::LMatrix::cols_, cyclus::LMatrix::M_, and cyclus::LMatrix::rows_.
LMatrix cyclus::operator* (const LMatrix & A, const long double k)
Definition at line 251 of file l_matrix.cc.
References cyclus::LMatrix::cols_, cyclus::LMatrix::M_, and cyclus::LMatrix::rows_.
LMatrix cyclus::operator+ (const LMatrix & lhs, const LMatrix & rhs)
Definition at line 210 of file l_matrix.cc.
LMatrix cyclus::operator- (const LMatrix & lhs, const LMatrix & rhs)
Definition at line 218 of file l_matrix.cc.
bool cyclus::operator< (const Arc & l, const Arc & r) [inline]
Definition at line 49 of file exchange_graph.h.
References cyclus::Arc::first, and cyclus::Arc::second.
template<class T > bool cyclus::operator< (const CapacityConstraint< T > & lhs, const CapacityConstraint< T > & rhs) [inline]
CapacityConstraint-CapacityConstraint comparison operator, allows usage in ordered containers.
Definition at line 116 of file capacity_constraint.h.
bool cyclus::operator== (const ExchangeNode & lhs, const ExchangeNode & rhs) [inline]
ExchangeNode-ExchangeNode equality operator.
Definition at line 20 of file exchange_graph.cc.
References cyclus::ExchangeNode::group, cyclus::ExchangeNode::max_qty, and cyclus::ExchangeNode::unit_capacities.
template<class T > bool cyclus::operator== (const cyclus::Trade< T > & lhs, const cyclus::Trade< T > & rhs)
Trade-Trade equality operator.
Definition at line 33 of file trade.h.
References cyclus::Trade< T >::amt, cyclus::Trade< T >::bid, cyclus::Trade< T >::price, and cyclus::Trade< T >::request.
bool cyclus::operator== (const Arc & l, const Arc & r) [inline]
Definition at line 53 of file exchange_graph.h.
References cyclus::Arc::first, and cyclus::Arc::second.
template<class T > bool cyclus::operator== (const CapacityConstraint< T > & lhs, const CapacityConstraint< T > & rhs) [inline]
CapacityConstraint-CapacityConstraint equality operator.
Definition at line 107 of file capacity_constraint.h.
References cyclus::CapacityConstraint< T >::capacity(), and cyclus::CapacityConstraint< T >::converter().
LMatrix cyclus::operator^ (const LMatrix & A, const int k)
Definition at line 269 of file l_matrix.cc.
References cyclus::LMatrix::cols_, and cyclus::LMatrix::rows_.
template<class T > static void cyclus::PopulateTradeResponses (Trader * trader, const std::vector< Trade< T > > & trades, std::vector< std::pair< Trade< T >, typename T::Ptr > > & responses) [inline, static]
Definition at line 51 of file trader_management.h.
Referenced by GetTradeResponses().
template<> void cyclus::PopulateTradeResponses< Material > (Trader * trader, const std::vector< Trade< Material > > & trades, std::vector< std::pair< Trade< Material >, Material::Ptr > > & responses) [inline]
Definition at line 60 of file trader_management.h.
template<> void cyclus::PopulateTradeResponses< Product > (Trader * trader, const std::vector< Trade< Product > > & trades, std::vector< std::pair< Trade< Product >, Product::Ptr > > & responses) [inline]
Definition at line 68 of file trader_management.h.
template<class T > static std::set<typename BidPortfolio<T>::Ptr> cyclus::QueryBids (Trader * t, const typename CommodMap< T >::type & map) [inline, static]
Definition at line 33 of file trader_management.h.
template<> std::set<BidPortfolio<Material>::Ptr> cyclus::QueryBids< Material > (Trader * t, const CommodMap< Material >::type & map) [inline]
Definition at line 39 of file trader_management.h.
template<> std::set<BidPortfolio<Product>::Ptr> cyclus::QueryBids< Product > (Trader * t, const CommodMap< Product >::type & map) [inline]
Definition at line 45 of file trader_management.h.
template<class T > static std::set<typename RequestPortfolio<T>::Ptr> cyclus::QueryRequests (Trader * t) [inline, static]
Definition at line 15 of file trader_management.h.
template<> std::set<RequestPortfolio<Material>::Ptr> cyclus::QueryRequests< Material > (Trader * t) [inline]
Definition at line 21 of file trader_management.h.
template<> std::set<RequestPortfolio<Product>::Ptr> cyclus::QueryRequests< Product > (Trader * t) [inline]
Definition at line 27 of file trader_management.h.
Composition::Ptr cyclus::ReadRecipe (InfileTree * qe)
Creates a composition from the recipe in the query engine.
Definition at line 71 of file xml_file_loader.cc.
References CLOG, cyclus::Composition::CreateFromAtom(), cyclus::Composition::CreateFromMass(), cyclus::InfileTree::GetString(), LEV_DEBUG3, cyclus::InfileTree::NMatches(), and cyclus::InfileTree::Query().
Referenced by cyclus::XMLFileLoader::LoadRecipes().
bool cyclus::ReqPrefComp (const Arc & l, const Arc & r) [inline]
A comparison function for sorting a container of Arcs by the requester's (unode's) preference, in decensing order (i.e., most preferred Arc first)
Definition at line 13 of file greedy_solver.h.
References cyclus::Arc::first.
Referenced by cyclus::GreedySolver::GreedilySatisfySet_().
template<class T > std::vector<typename T::Ptr> cyclus::ResCast (Manifest rs)
Casts a vector of Resources into a vector of a specific resource type T.
Definition at line 24 of file resource_buff.h.
template<class T > T::Ptr cyclus::ResCast (Resource::Ptr r)
Casts a Resource::Ptr into a pointer of a specific resource type T.
Definition at line 34 of file resource_buff.h.
template<class T > static void cyclus::SendTradeResources (TradeExecutionContext< T > & trade_ctx) [static]
Definition at line 144 of file trade_executor.h.
References AcceptTrades(), cyclus::TradeExecutionContext< T >::requesters, and cyclus::TradeExecutionContext< T >::trades_by_requester.
Referenced by cyclus::TradeExecutor< T >::ExecuteTrades().
void cyclus::SolveProg (OsiSolverInterface * si)
Definition at line 21 of file solver_factory.cc.
References HasInt().
Referenced by cyclus::ProgSolver::Solve().
std::vector<std::string> cyclus::split (const std::string & s, char delim)
Definition at line 18 of file sqlite_back.cc.
Referenced by cyclus::Env::FindModuleLib(), cyclus::SqliteBack::GetTableInfo(), and cyclus::Env::ListModules().
std::string cyclus::StringFromHex (const std::string & in)
Definition at line 183 of file sqlite_back.cc.
std::string cyclus::StringToHex (const std::string & s)
Definition at line 175 of file sqlite_back.cc.
Referenced by cyclus::SqliteBack::ValAsString().
template<class T > Arc cyclus::TranslateArc (const ExchangeTranslationContext< T > & translation_ctx, typename Bid< T >::Ptr bid)
translates an arc given a bid and subsequent data, and also updates the unit capacities for the associated nodes on the arc
Definition at line 223 of file exchange_translator.h.
References cyclus::ExchangeTranslationContext< T >::bid_to_node, cyclus::BidPortfolio< T >::constraints(), cyclus::RequestPortfolio< T >::constraints(), cyclus::ExclusiveStatus< T >::exclusive, cyclus::Bid< T >::offer(), cyclus::Bid< T >::portfolio(), cyclus::Request< T >::portfolio(), cyclus::ExclusiveStatus< T >::qty, cyclus::Bid< T >::request(), cyclus::ExchangeTranslationContext< T >::request_to_node, and TranslateCapacities().
Referenced by cyclus::ExchangeTranslator< T >::Translate().
template<class T > ExchangeNodeGroup::Ptr cyclus::TranslateBidPortfolio (ExchangeTranslationContext< T > & translation_ctx, const typename BidPortfolio< T >::Ptr bp)
translates a bid portfolio by adding bid nodes and accounting for capacities.
Bid unit capcities must be added when arcs are known
Definition at line 168 of file exchange_translator.h.
References AddBid(), cyclus::BidPortfolio< T >::bids(), CLOG, cyclus::BidPortfolio< T >::constraints(), and LEV_DEBUG4.
Referenced by cyclus::ExchangeTranslator< T >::Translate().
template<typename T > void cyclus::TranslateCapacities (typename T::Ptr offer, const typename std::set< CapacityConstraint< T > > & constr, ExchangeNode::Ptr n, const Arc & a)
updates a node's unit capacities given, a target resource and constraints
Definition at line 259 of file exchange_translator.h.
References CLOG, and LEV_DEBUG1.
Referenced by TranslateArc().
template<class T > RequestGroup::Ptr cyclus::TranslateRequestPortfolio (ExchangeTranslationContext< T > & translation_ctx, const typename RequestPortfolio< T >::Ptr rp)
translates a request portfolio by adding request nodes and accounting for capacities.
Request unit capcities must be added when arcs are known
Definition at line 137 of file exchange_translator.h.
References AddRequest(), CLOG, cyclus::RequestPortfolio< T >::constraints(), LEV_DEBUG2, LEV_DEBUG4, cyclus::RequestPortfolio< T >::qty(), and cyclus::RequestPortfolio< T >::requests().
Referenced by cyclus::ExchangeTranslator< T >::Translate().
void cyclus::UpdateCapacity (ExchangeNode & n, const Arc & a, double qty)
updates the capacity of a given ExchangeNode (i.e., its max_qty and the capacities of its ExchangeNodeGroup)
Exceptions:
StateError if ExchangeNode does not have a ExchangeNodeGroup
ValueError if the update results in a negative ExchangeNodeGroup capacity or a negative ExchangeNode max_qty
Parameters:
n the ExchangeNode
qty the quantity for the node to update
Definition at line 85 of file exchange_graph.cc.
References cyclus::ExchangeNodeGroup::capacities(), CLOG, cyclus::ExchangeNode::group, IsNegative(), LEV_DEBUG1, cyclus::ExchangeNode::max_qty, cyclus::ExchangeNode::qty, and cyclus::ExchangeNode::unit_capacities.
Referenced by cyclus::ExchangeGraph::AddMatch(), and UpdateCapacity().
void cyclus::UpdateCapacity (ExchangeNode::Ptr pn, const Arc & a, double qty)
Definition at line 116 of file exchange_graph.cc.
References UpdateCapacity().
Variable Documentation
double const cyclus::kBuffInfinity = std::numeric_limits<double>::max() [static]
Definition at line 18 of file resource_buff.h.
const double cyclus::kConstraintEps = 1e-08 [static]
epsilon value to turn determine difference between constraint values
Definition at line 38 of file cyc_limits.h.
Referenced by cyclus::CBCSolver::ConstraintBounds().
unsigned int const cyclus::kDefaultDumpCount = 500 [static]
default number of Datum objects to collect before flushing to backends.
Definition at line 21 of file recorder.h.
Referenced by cyclus::Recorder::Recorder().
const int cyclus::kIntBoundLimit = std::numeric_limits<int>::max() [static]
maximum (+ or -) value for an integer variable
Definition at line 32 of file cyc_limits.h.
const double cyclus::kLinBoundLimit = std::numeric_limits<double>::max() [static]
maximum (+ or -) value for a linear variable
Definition at line 35 of file cyc_limits.h.
const double cyclus::kModifierLimit = pow(10, 10) [static]
maximum value for a function modifier (i.e., a_i for variable x_i)
Definition at line 29 of file cyc_limits.h.
Referenced by cyclus::SolverInterface::SolverInterface().