CYCLUS: cyclus::ExchangeContext< T > Class Template Reference
cyclus::ExchangeContext< T > Class Template Reference
The ExchangeContext is designed to provide an ease-of-use interface for querying and reaggregating information regarding requests and bids of a resource exchange.
#include <exchange_context.h>
Public Member Functions
void AddBid (typename Bid< T >::Ptr pb)
adds a bid to the appropriate containers, default trade preference between request and bid is set
void AddBidPortfolio (const typename BidPortfolio< T >::Ptr port)
adds a bid to the context
void AddRequest (typename Request< T >::Ptr pr)
Adds an individual request.
void AddRequestPortfolio (const typename RequestPortfolio< T >::Ptr port)
adds a request to the context
Public Attributes
std::set< Trader * > bidders
known bidders
std::vector< typename
BidPortfolio< T >::Ptr > bids
a reference to an exchange's set of bids
std::map< typename Request< T >
::Ptr, std::vector< typename
Bid< T >::Ptr > > bids_by_request
maps request to all bids for request
CommodMap< T >::type commod_requests
maps commodity name to requests for that commodity
std::set< Trader * > requesters
known requesters
std::vector< typename
RequestPortfolio< T >::Ptr > requests
a reference to an exchange's set of requests
std::map< Trader *, typename
PrefMap< T >::type > trader_prefs
maps commodity name to requests for that commodity
Detailed Description
template<class T>
class cyclus::ExchangeContext< T >
The ExchangeContext is designed to provide an ease-of-use interface for querying and reaggregating information regarding requests and bids of a resource exchange.
The ExchangeContext is used by a ResourceExchange or related class to provide introspection into the requests and bids it collects. Specifically, this class is designed to assist in phases of the Dynamic Resource Exchange. The second phase, Response to Request for Bids, is assisted by grouping requests by commodity type. The third phase, preference adjustment, is assisted by grouping bids by the requester being responded to.
Definition at line 42 of file exchange_context.h.
Member Function Documentation
template<class T> void cyclus::ExchangeContext< T >::AddBid (typename Bid< T >::Ptr pb) [inline]
adds a bid to the appropriate containers, default trade preference between request and bid is set
Parameters:
pb the bid
Definition at line 78 of file exchange_context.h.
References cyclus::Bid< T >::bidder(), cyclus::ExchangeContext< T >::bidders, cyclus::ExchangeContext< T >::bids_by_request, cyclus::Bid< T >::request(), and cyclus::ExchangeContext< T >::trader_prefs.
Referenced by cyclus::ExchangeContext< T >::AddBidPortfolio().
template<class T> void cyclus::ExchangeContext< T >::AddBidPortfolio (const typename BidPortfolio< T >::Ptr port) [inline]
adds a bid to the context
Definition at line 64 of file exchange_context.h.
References cyclus::ExchangeContext< T >::AddBid(), cyclus::BidPortfolio< T >::bids(), and cyclus::ExchangeContext< T >::bids.
template<class T> void cyclus::ExchangeContext< T >::AddRequest (typename Request< T >::Ptr pr) [inline]
Adds an individual request.
Definition at line 57 of file exchange_context.h.
References cyclus::ExchangeContext< T >::commod_requests, cyclus::Request< T >::commodity(), cyclus::Request< T >::requester(), and cyclus::ExchangeContext< T >::requesters.
Referenced by cyclus::ExchangeContext< T >::AddRequestPortfolio().
template<class T> void cyclus::ExchangeContext< T >::AddRequestPortfolio (const typename RequestPortfolio< T >::Ptr port) [inline]
adds a request to the context
Definition at line 45 of file exchange_context.h.
References cyclus::ExchangeContext< T >::AddRequest(), cyclus::RequestPortfolio< T >::requests(), and cyclus::ExchangeContext< T >::requests.
Member Data Documentation
template<class T> std::set<Trader*> cyclus::ExchangeContext< T >::bidders
known bidders
Definition at line 98 of file exchange_context.h.
Referenced by cyclus::ExchangeContext< T >::AddBid().
template<class T> std::vector<typename BidPortfolio<T>::Ptr> cyclus::ExchangeContext< T >::bids
a reference to an exchange's set of bids
Definition at line 92 of file exchange_context.h.
Referenced by cyclus::ExchangeContext< T >::AddBidPortfolio().
template<class T> std::map< typename Request<T>::Ptr, std::vector<typename Bid<T>::Ptr> > cyclus::ExchangeContext< T >::bids_by_request
maps request to all bids for request
Definition at line 105 of file exchange_context.h.
Referenced by cyclus::ExchangeContext< T >::AddBid().
template<class T> CommodMap<T>::type cyclus::ExchangeContext< T >::commod_requests
maps commodity name to requests for that commodity
Definition at line 101 of file exchange_context.h.
Referenced by cyclus::ExchangeContext< T >::AddRequest().
template<class T> std::set<Trader*> cyclus::ExchangeContext< T >::requesters
known requesters
Definition at line 95 of file exchange_context.h.
Referenced by cyclus::ExchangeContext< T >::AddRequest().
template<class T> std::vector<typename RequestPortfolio<T>::Ptr> cyclus::ExchangeContext< T >::requests
a reference to an exchange's set of requests
Definition at line 89 of file exchange_context.h.
Referenced by cyclus::ExchangeContext< T >::AddRequestPortfolio().
template<class T> std::map<Trader*, typename PrefMap<T>::type> cyclus::ExchangeContext< T >::trader_prefs
maps commodity name to requests for that commodity
Definition at line 108 of file exchange_context.h.
Referenced by cyclus::ExchangeContext< T >::AddBid().
The documentation for this class was generated from the following file:
exchange_context.h