CYCLUS: cyclus::ExclusiveStatus< T > Struct Template Reference
cyclus::ExclusiveStatus< T > Struct Template Reference
information container for the exclusive status of an arc
#include <exchange_translator.h>
Public Member Functions
ExclusiveStatus (typename Request< T >::Ptr r, typename Bid< T >::Ptr b)
Public Attributes
bool exclusive
double qty
Detailed Description
template<class T>
struct cyclus::ExclusiveStatus< T >
information container for the exclusive status of an arc
Definition at line 198 of file exchange_translator.h.
Constructor & Destructor Documentation
template<class T> cyclus::ExclusiveStatus< T >::ExclusiveStatus (typename Request< T >::Ptr r, typename Bid< T >::Ptr b) [inline]
Definition at line 202 of file exchange_translator.h.
References cyclus::Bid< T >::exclusive(), cyclus::Request< T >::exclusive(), cyclus::ExclusiveStatus< T >::exclusive, cyclus::Bid< T >::offer(), cyclus::ExclusiveStatus< T >::qty, and cyclus::Request< T >::target().
Member Data Documentation
template<class T> bool cyclus::ExclusiveStatus< T >::exclusive
Definition at line 199 of file exchange_translator.h.
Referenced by cyclus::ExclusiveStatus< T >::ExclusiveStatus(), and cyclus::TranslateArc().
template<class T> double cyclus::ExclusiveStatus< T >::qty
Definition at line 200 of file exchange_translator.h.
Referenced by cyclus::ExclusiveStatus< T >::ExclusiveStatus(), and cyclus::TranslateArc().
The documentation for this struct was generated from the following file:
exchange_translator.h